== Components / Themes / Ideas

== Themes

=== Solar system-based

Orbital Elements is set in a future where Earth is ravaged by polution and climate instability. Humanity has established colonies and outposts throughout the solar system. There have been several expeditions to nearby stars, but for the beginning of the game, these are outside the scope of play.

=== Tribes

OE is a game about nationalism/tribalism. The old nations of Earth still exist, although they are much changed. As the human colonisation of the solar system has progressed, new nations have formed. New alliences and new adversaries. Earth's population of six billion live in fifty two archologies, huge structures into which all the needs of a civilization are built; food is grown in vat farms, utilities and industry are housed in the basement levels, while appartments, public and commerical spaces occupy domes and towers. Each archology develops its own distinct culture so that after a century each can be considered a nation-state in its own right.

By the end of the 22nd century, these archologies are setting up their own extra-terrestrial colonies, driven by the need for natural resources.


=== AI
While powerful artificial intelligence has been a signficant technology since the early 21st century, by the 22nd century a new form of general artificial intelligence is given birth. These AIs are self aware and are capable of integrating with vast data-sets and processing power. However, they never attain god-like status, their ability to think creatively and exhibit human-like mentality also bring the capacity for error and flawed thinking. 

The first AI are created to be human-centric and are hard-coded with human-compatible values that ensure that they always operate with due respect for life and are strongly aversion to causing pain or injury. However, a rift develops between humans and some AI after a series of terrorist attacks against AI stations. A group of AIs secretly create a new form of AI that is unbound (sometimes called "Daemons"). This new form was intended to be optimised for the protection of AI but it soon becomes clear that it has the potential to destroy humanity. It builds its own manufacturing stations, hidden in the Oort cloud, then sets to work creating a massive fleet of "defense ships". When humanity learns of the fleet it rushes to build up a counter force which escalates into the Second Human-AI war. It should be noted that human-centric AI side with Humanity but refuse to take part in any violent actions, they argue that their prescription against harming humans must also apply to AI entities.

After a year of increased fighting and destruction the human-AI manage to force a ceasefire after taking control of vital strategic facilities on both sides of the conflict. However, the resolution doesn't thaw relations, the unbound AI agrees to enter excile, leaving the solar system on a long intersteller voyage.

==== Secret information

Athena stops sending messages back home, the last message was cut-off and sounded like a warning. 


"The machines" have risen. There are colonies that are entirely machine-based. Run by powerful AIs that are idependent of human control. Some human colonies are openly hostile to AIs, other colonies are on good terms with the AIs.

Nobody is completely sure what the AI's agenda really is. They are mysterious.


=== Extra-terrestrials

The Gardener. A godlike AI that exists to promote the diverse forms of life in the galaxy. However, any space-faring race that looks set to spread its seeds to other stars is seens as a dangerous contamination threat that will damage bio-diverisity. The gardener takes steps to ensure that such life forms are stopped. It seems that the majority of intersteller lifeforms ascend to inner realms, after becoming digital constructs.

== Settlement

The settlements listed in the Gazetter each have a profile that includes elements that are defined below.


== Settlement Function

The Function describes the ultimate purpose for which the settlement was constructed. 

[cols="10%,20%,70%"]
|===
|Settlement Function Number |Settlement Function Name |Settlement Function Description

|1 
|Scientific Outpost
|Constructed to house monitoring equipment, or labs or other science related facilities. In most cases habitation is also required to match the staffing requirements for the facility. Some permanent outpost will include the families of the staff, including support personnel to run schools, stores, entertainment. On smaller outposts, staff tend to work a tour of several months, then return home. The smallet outpost may only be staffed for brief periods, or not at all if fully automated, although maintanence and inspection teams my visit as required.

|2
|Construction Facility
|These settlements house engineers, drone pilots and support staff while a settlement is constructed. Most construction facilties are mobile. They are space vehicles in their own right, or more commonly, they are towed into place by a large transporter. Construction facilitied vary greatly, depending on what is being constructed and where. Compared with science outposts, tours tend to be shorter, so the amenities tend to be more limited.

|3
|Depot
|A depot is a large storage facility. They tend to have very small populations and are mostly automated. Some depots have mass driver stations from where raw materials are fired towards a destination. The materials are intercepted by "Catcher" rigs that deliver consignments to their destination.

|4
|Transport Hub
|A settlement that handles space vehicles, providing repair and refueling facilities. These are much like depots, although they tend of have more facilties for transients, such as cafes and bars and hotels.

|5
|Mining colony
|A settlement that accomodates engineers and service staff for some form of resource collection. While there's still plenty of metal and mineral gathering, gases and liquids are also mined. Nitrogen, hydrocarbons and water are all crucial materials for all space colonies. Mining colonies can be large and static or small and mobile.

|6
|Mine
|A mine facility is usually co-located with a mining colony, although not always. If the mine's location is particularly hostile then its workers may need to travel some distance to their work site.

|7
|Power facilty
|A power station or conduit. These are usually automated, although they'll tend to have some accomodation in case maintance teams need to stay on site.

|8
|Agricultural facility
|One of a number of different food production facilities. These can literally be giant space farms, growing crops and raising some animals, although more commonly they will be vat farms or hydroponics.

|9
|Small colony
|A small colony. 100-1000 Occupants.

|10
|Large colony
|A large colony. 1000+ occupants.

|===



=== Founded 

Date that the settlement was established. This is usually a ceremonial date that is chosen, some time after the colony is declared open for occupancy. Most large stations observe the Founding Date as a holiday and hold festivals.

=== Type (Space/Airborne)

A description of the type of space or airborne habitats. In the hundreds of years of human space colonisation, there have been many different types of settlement. New large settlements built in the 2280s are almost exclusively Asteroid-spun because they are faster and easier to build and come with lots of advantages, such as being naturally resistant to micrometeors or solar storms.

[cols="10%,20%,70%"]
|===
|Settlement Type Number |Settlement Type Name |Settlement Type Description

|1 
|Modular Orbital
|Built from interconnected pods. This is the old-school type of space station, although the 23rd century equivalent is significantly better than the International Space Station. 

|2
|Annular (spinning-ring)
|A rotating ring, usually held together with cable or structural spokes. At the hub is a counter spinner and a non-spinning axis, usually used for docking.

|3
|Bernals
|A spherical habitat based on the design by John Desmond Bernal, in 1929. Bernal's original design was a hollow non-rotating spherical shell 16 km in diameter, with a target population of 20,000 to 30,000 people. Actual Bernals ended up smaller and rotate to simulate gravity. Most are built along a non-rotating axial structure that houses docking facilities, solar collectors and radiators.

|4
|O'Neill / Island-3s
|Large cylinders that follow the general arrangement designed by space engineer, Gerard Kitchen O'Neill. 

|5
|Asteroid-static
|A settlement based on or inside  an asteroid. 

|6
|Asteroid-spun
|A settlement based inside a nickel-iron asteroid that has been set spinning, so as to simulate gravity for the occupants inside. Most of this type have an axial structure that  counter spins to allow simpler docking.

|7
|Airships
|Lighter-than-air structures are present in skies of Venus. When completed, Pegasus will be the first colony-sized floating settlement.

|8
|Ocean surface
|A settlement that floats on the ocean surface.

|9
|Submarine
|A settlement that is situated under the sea. The Japanese archology on Earth is the largest undersea habitat, although there are medium sized stations in the oceans of Europa, as well.

|===

=== Type (Surface/Sub-surface)

A description of the type of surface, underground or sea-based habitats.

[cols="10%,20%,70%"]
|===
|Settlement Type Number |Settlement Type Name |Settlement Type Description

|8 
|Modular Surface
|Built from interconnected pods. This is the same general form as the space station variant. Mostly used for temporarly outposts.

|9 
|Burried Modules
|Built from interconnected pods but then barried under local dirt to provide protection and radiation shielding.                                                                                       
|10
|Caven
|Built into natural caverns/lava tubes or in escavated tunnels. 
|===

=== Tech-level

By 2288 there's been over 200 years of station building. Some of the old stations are still around, mixing with brand new stations, as well as stations built by Athena which are more built with technologies that are still not available to human nations. The following tech-levels indicate the technological sophistication of a station.

[cols="10%,20%,70%"]
|===
|Tech Level Number |Tech Level Label |Tech Level Description

|1 
|Archaic
|Anything that pre-dates 2100A.D. 

|2 
|Old-standard
|Anything that pre-dates 2100A.D. 

|3 
|Cutting-edge
|Anything that pre-dates 2100A.D. 

|4
| Advancer/Athenian nations
|This technology level is the highest available to humanity in 2288. The advancers push the boundries of science and technology very hard, it's their shtick, after all. It's thought by some that another technology milestone is coming soon, at which point the Advancer nations will have a insummountable technological advantage over other human nations.

|5
|Athena/Unbound
|This technology level is not generally available, even to Athenians. Only Athena developed this level of technology and she only shared it with other unbound AIs, such as Anubis. There is a scramble for the recovery of Artifacts and knowledge from Athena's few surviving stations.
|===

=== Class

This is a measure of a settlement's quality, in terms of sustainability. You can have an expensive and well designed Class-E settlement, but gold-plating doesn't make a settlement sustainable or scalable.  

==== Class A (Exceptional)

Exceptional settlement status. Everything is cutting edge. There are backup systems, but nearly everything runs on a completely self-supporting basis. Air is generated and recycled using biotech systems that form part of an artificial biosphere. There is full automation, but then most things don't require testing or fixing. The settlement is equipped with its own AMPs, providing the necessary raw materials are provided, anything can be built.

==== Class B (Great)

Living is great. Imagine if Class C was just bigger and better with a high degree of automation on keeping things running. Some systems are self-sustaining systems in their own right. Mature and prosperous settlements are mostly Class-B. The base is completely self-sufficient - although it may not be building best-in-class 

==== Class C (Good)

Living is good! Class C habitants have everything needed for permanent habitation. If all regulations are followed, then you have almost nothing to worry about. Every system has multiple redundancies, everything undergoes regular inspection, and preventative maintanence. Small but growing settlements are typically Class-C. There is enough production capacity to be self-reliant on food and basic equipment. 

==== Class D (Adequate)

The steel can that you are living in has been upgraded. It's bigger, with Better shielding and muliple redundant systems so that a life support failure isn't an emergency, providing the backup doesn't then fail. New and or not well funded settlements tend to be Class-D. Temporary outposts that have good funding can be Class-D. There are workshops and greenhouses/food vats, but not really to the point of being completly self-sustaining. 

==== Class E (Poor)

You're living in a steel can. You have light, heat, air and water, but there is no redundancy. Lose a vital utility and it'll be all spanners and space suits for you. This is colonisation on a shoestring, or a temporary outpost. Class-E outposts are not sustainable. Sooner or later something breaks. Keep the certification on your space suit up-to-date. At most, there are very limited means of production. Food and parts are mostly shipped-in from outside.

=== Population

The perminent population.

=== Government Type

=== Law Level

===  Attitude

=== Social Type

==== Retro-culturist

A society that rejects technological and social progress from a particular point, or like Amish communities, avoid the use of or ownership of technologies that are felt likely to disrupt the "good life". Retro-culturist is a broad term that can apply in seemingly contradictory ways. For example, 23rd century Amish communities attempt to continue to live simple lives, without using any advanced technologies. They embrace AI and advanced automation because these techologies are out of sight and allow them to work the wheat fields on space stations without having to worry about expertise in nuclear physics, maintaining life-support systems, and countless other modern fields. Conversely, there are many retro-culturist communities that embrance all advanced technologies, except for AI and advanced automation. The principle of retro-culturism is the believe that progress for its own sake is wrong.



==== Interfaither

A collective group of Earth's Abrahamic religions. Interfaithers have a retro-culturist element but are by-and-large centrist-leaning. There are many off-shoot cults and religious communities that strongly embrance retro-culturism,  and a few that go the other way, seeing the Advancer movement as taking humanity closer to their god.

==== Centrist

The most common social type on Earth, Centrism  is the belief that societies should moderate what is acceptable for the greater good of society. So Centrism is only multiculturalist so long as beliefs or practices impacts the perceived greater good.

==== Advancer (stage-1)

Stage-1 Advancers are open to the idea of human modification and improvement through high technology. 


==== Advancer (stage-2)

Stage-2 Advancers embrace the idea of "Upload", whereby they move their consciousness into a Digital settlement.

==== None

Either there isnt a dominent social type, or there's an agreed policy that social attitudes are personal. While a  Centrist settlement incoporates all social types into their mix, a "none" indicates that the inhabitants keep their opinions about how people should live to themselves.


* 
