== Components / Themes / Ideas

== Themes

=== Solar system-based

Orbital Elements is set in a future where Earth is ravaged by polution and climate instability. Humanity has established colonies and outposts throughout the solar system. There have been several expeditions to nearby stars, but for the beginning of the game, these are outside the scope of play.

=== Tribes

OE is a game about nationalism/tribalism. The old nations of Earth still exist, although they are much changed. As the human colonisation of the solar system has progressed, new nations have formed. New alliences and new adversaries. Earth's population of six billion live in fifty two archologies, huge structures into which all the needs of a civilization are built; food is grown in vat farms, utilities and industry are housed in the basement levels, while appartments, public and commerical spaces occupy domes and towers. Each archology develops its own distinct culture so that after a century each can be considered a nation-state in its own right.

By the end of the 22nd century, these archologies are setting up their own extra-terrestrial colonies, driven by the need for natural resources.


=== AI
While powerful artificial intelligence has been a signficant technology since the early 21st century, by the 22nd century a new form of general artificial intelligence is given birth. These AIs are self aware and are capable of integrating with vast data-sets and processing power. However, they never attain god-like status, their ability to think creatively and exhibit human-like mentality also bring the capacity for error and flawed thinking. 

The first AI are created to be human-centric and are hard-coded with human-compatible values that ensure that they always operate with due respect for life and are strongly aversion to causing pain or injury. However, a rift develops between humans and some AI after a series of terrorist attacks against AI stations. A group of AIs secretly create a new form of AI that is unbound (sometimes called "Daemons"). This new form was intended to be optimised for the protection of AI but it soon becomes clear that it has the potential to destroy humanity. It builds its own manufacturing stations, hidden in the Oort cloud, then sets to work creating a massive fleet of "defense ships". When humanity learns of the fleet it rushes to build up a counter force which escalates into the Second Human-AI war. It should be noted that human-centric AI side with Humanity but refuse to take part in any violent actions, they argue that their prescription against harming humans must also apply to AI entities.

After a year of increased fighting and destruction the human-AI manage to force a ceasefire after taking control of vital strategic facilities on both sides of the conflict. However, the resolution doesn't thaw relations, the unbound AI agrees to enter excile, leaving the solar system on a long intersteller voyage.

==== Secret information

Athena stops sending messages back home, the last message was cut-off and sounded like a warning. 


"The machines" have risen. There are colonies that are entirely machine-based. Run by powerful AIs that are idependent of human control. Some human colonies are openly hostile to AIs, other colonies are on good terms with the AIs.

Nobody is completely sure what the AI's agenda really is. They are mysterious.


=== Extra-terrestrials

The Gardener. A godlike AI that exists to promote the diverse forms of life in the galaxy. However, any space-faring race that looks set to spread its seeds to other stars is seens as a dangerous contamination threat that will damage bio-diverisity. The gardener takes steps to ensure that such life forms are stopped. It seems that the majority of intersteller lifeforms ascend to inner realms, after becoming digital constructs.


== Settlement types

=== Type 1 Modular pods

=== Type 2 Printed Polycrete

=== Type 3 

== Settlment Class

This is a measure of a settlement's quality, in terms of sustainability. You can have an expensive and well designed Class-E settlement, but gold-plating doesn't make a settlement sustainable or scalable.  

=== Class A

Exceptional settlement status. Everything is cutting edge. There are backup systems, but nearly everything runs on a completely self-supporting basis. Air is generated and recycled using biotech systems that form part of an artificial biosphere. There is full automation, but then most things don't require testing or fixing. The settlement is equipped with its own AMPs, providing the necessary raw materials are provided, anything can be built.

=== Class B

Living is great. Imagine if Class C was just bigger and better with a high degree of automation on keeping things running. Some systems are self-sustaining systems in their own right. Mature and prosperous settlements are mostly Class-B. The base is completely self-sufficient - although it may not be building best-in-class 

=== Class C

Living is good! Class C habitants have everything needed for permanent habitation. If all regulations are followed, then you have almost nothing to worry about. Every system has multiple redundancies, everything undergoes regular inspection, and preventative maintanence. Small but growing settlements are typically Class-C. There is enough production capacity to be self-reliant on food and basic equipment. 

=== Class D

The steel can that you are living in has been upgraded. It's bigger, with Better shielding and muliple redundant systems so that a life support failure isn't an emergency, providing the backup doesn't then fail. New and or not well funded settlements tend to be Class-D. Temporary outposts that have good funding can be Class-D. There are workshops and greenhouses/food vats, but not really to the point of being completly self-sustaining. 

=== Class E

You're living in a steel can. You have light, heat, air and water, but there is no redundancy. Lose a vital utility and it'll be all spanners and space suits for you. This is colonisation on a shoestring, or a temporary outpost. Class-E outposts are not sustainable. Sooner or later something breaks. Keep the certification on your space suit up-to-date. At most, there are very limited means of production. Food and parts are mostly shipped-in from outside.
