ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Free fallin

[.lead]
The following mini-adventure is a great way to introduce new players to Orbital Elements. At the beginning of the adventure the PCs are not a party, but in the first chapter they are thrown together and must quickly learn to rely on each other in a deseperate struggle for survival. 

[NOTE]
====
**NOTE:** This adventure is intended for a group of 3-4 new players and a Game Master. You can create new characters before the adventure session or you can use the pre-rolled characters provided at the end of the adventure.
====

image:https://db3pap001files.storage.live.com/y4m2BNQMeshdJIzqvQbzORXneLXCwgNIUs-iAeqAK_DaITAf8GskR65EqicCUI2jEq4O5ni54Wmd7uRXAlcxfMJL2xmErivpMQV2RLARtvSXO6zogoomZ4tEAl9oYhXVfIdMmqgBJGkz7uqGbDfskKkUVPnhJ62JWgQ8uzARMLP-nIZXZKN3uMVO6vQAbsDH3KG?width=1024&height=576&cropmode=none[image1]

==== Section links

* link:#adventure-summary-game-masters-eyes-only-1[*Adventure Summary*] 
* link:#chapter-one---the-breaks-1[*Chapter One - _The Breaks_*] 
* link:#chapter-two---free-fallin-1[*Chapter Two -_Free Fallin_*] 
* link:#chapter-three---fight-the-power-1[*Chapter Three - _Fight the Power_*]
* link:#end-credits[*End Credits*]

[[summary]]
=== Adventure Summary (Game Master's eyes only)

==== Chapter One - _The Breaks_

In the opening chapter, the player characters are prisoners on a patrol carrier operated by the mercenary force that handles anti-piracy duties out of Lanserda Yeocan, the industrial settlement on Callisto. The players were unlucky enough to be travelling on a transporter that the mercenaries accused of piracy and impounded. All onboard the transporter were arrested. As play begins, the PCs have been held on the patrol carrier for three weeks. The captured passengers are then loaded onto two shuttles and launch to unknown destinations. All the PCs are loaded into the same shuttle. There are whispers among the other prisoners that the patrol carrier is returning to its base and transferring the prisoners to a free station for interrogation and release.

Within hours of its departure, the PC's shuttle makes a detour. The four crew become agitated. The talk between prisoners is that the shuttle has been ordered to investigate a transporter that briefly broadcasted an SOS before going quiet. Soon, the PCs are selected by drawing straws for a potentially dangerous mission to board an apparently derelict transport vehicle.

==== Chapter Two - _Free fallin_

The PCs make the 300-metre trip to the apparently lifeless transport vehicle. The moment the players board, some kind of munition launches, destroying the shuttle they were travelling on. The PCs now seem to be alone.


[NOTE]
====
*So what happened on the derelict?* +
While making a routine cargo run to Callisto, some of the transporter's crew, loitering around the cargo deck, decided to tamper with the wrong package, a robotics system called T-12. The system is an advanced humanoid robot of unusual complexity. The crew members activated the robot for poops and giggles, not knowing that the robot wasn't a "labour droid," contrary to the manifest description. When the group tried to have some fun ordering the robot around, they were attacked and immobilized. 

The robot appears to be a prototype anti-piracy droid intended to act as onboard security. However, the unit is not supposed to be activated without first being programmed with the crew's IDs and biometric information. Consequently, on being activated, the droid is classifying all of the crew as hostiles. In the ensuing fracas, the crewmembers were either immobilized and captured or in hiding. Making contact with crew members is the easiest way for the PCs to learn what's going on. 
====

At this point, the PCs get to explore the derelict, _Independent Transport Vehicle Golden Goose_. Chapter two consists of scenes that deal with different parts of the vehicle, so the scenes will play out based on where the players choose to send their characters. The PCs must unravel the mystery of the Golden Goose and find a way to take control of the ship before it coasts out of range and ends up floating into a deep system orbit.

There are six entry points into the Golden Goose, a full airlock in the command module and each of the hab rings, an airlock at each end of the vehicle's stem, and two airlocks in each cargo module. Finally, there's an emergency lock in engineering.

**Command Module** +
Some clues in the command module point to the ship having been locked down by some kind of security incident.
There are small bloodstains in the central access area of Deck 2.

**Hab Modules** +
There are four Hab module decks. The first (Deck-5) is used by the crew, the other decks are not occupied. Deck 8 is cordoned off with a notice that says "Keep out, cleaning in progress." There are clues to a struggle in the main lounge area (room C on the map). Most of the state rooms appear to have been sealed by some kind of metal tape. the tape is some of super strong repair tape, unless some kind of removal agent is applied it will be easier to smash the doors in than get them open. Held in the rooms are the Almona Wash, Tony Pendula and Simone Acosta. 

Making noises will result in Almona shouting at the PCs. Her priority is for getting the PCs to go to engineer (deck 21) to look for her husband. The crew help in the hab decs have a water supply and snacks, but she is worried for her husband, Ross McAlpine as there's no food or water in engineer. Ross may be slipping into a coma after three days without water.

Almona tells the PCs that there is some kind of droid onboard that attack the crew. While it didn't appear to use lethal force, it has set the ship in lockdown which means that it is coasting past their destination and will be heading into an unrecoverable orbit in a few hours. Unless the PCs can take control of the ship everyone onboard is doomed.

Tony Pendula shouts at the PCs that the tape sealing the doors is molecular bonding tape (MBT-40). There's a spray for its easy removal in a container on the cargo module (Deck 17). There's also the ship's locker, located on the command deck (The side room that connects to B, on Deck 2) which contains a number of firearms, but only Almona or Tony can open unlock the cabinet.

Simone Acosta tells the PCs that she thinks that the incident started in the cargo hold, Lars Anderson and two of his maintance team were on Deck 11 just before the incident. Simone adds that she doesn't recognise the make of the droid, it is not part of the ship's official equipment.

**End Cap "Clamp" Decks (9 and 20)** +
No obvious activity on these special decks that clamp each end of the huge cargo modules.

**Cargo Decks (10-19)** +
There are nine cargo decks, each is 9m high, creating a really large area to explore. On Deck 10, in the central area at the top of the map (D) are clues to the origins of the trouble. The PCs can find a large storage container on which are planted flexiscreens that display various documents that claim that the container is storing a UD-27 manual labour droid. This is a fairly common utility droid. On the labels are a corporate insignia, a white rook chess-piece, set against a star field background. The logo doesn't connect with anything else in the adventure, it's really a clue for a future scenario that features Trigean Systems. 

* The PCs might notice security cameras, suggesting that the events that played out in the cargo section might have been recorded.
* A PC with computing skill can make a difficult role (10+) to notice a procedure burried in the container's documentation that allows for the robot's firmware to be remotely updated. This could be done from the central engineering control room (Deck 21).

**Engineering Control (21)** +
This is currently the control centre for the transporter, since the activation of lockdown has disabled all controls in the command module. Naturally, it is also T-12's default hiding place.                      

**Fusion Control (22)** +
This deck is essentially a balcony with an interior space filled with the fusion powerplants that stretches about 15 from top to bottom. There's nothing critical in this section unless you want to turn the power off or scuttle the transporter.

**Drive Deck (23)** +
This deck provides access to the Quan-Ebrahimi drive. There's nothing here of interest but it does have an emergency airlock that T-12 can use to travel across the hull to access 

==== Chapter Three - _Fight the Power_

Chapter three starts when the PCs have pieced together what's going on, have some contact with the trapped or hidden crew. The main focus of this final chapter is whatever plan the PCs come up with to take back control of the ship. T-12 is an unstoppable force and an immovable object, successfully completing the adventure is going to depend on some clever planning. The PCs have a number advantage and a ship full of stuff. Winning through combat is the least effective and most dangerous road to follow - the PCs begin the adventure unarmed and the firearms in the emergency locker are intended for use in self defense against human attackers. 


*PLAN-BETA*

If the PCs gain entry to Engineering control, or they manage to evade T-12 in an encounter, T-12 goes to to the Cargo decks and unpacks 6 labour droids to act as its minions. These standard droids don't have much to contribute except for evening the numbers. They are not effective and can be disabled relatively easily. 


=== Chapter One - The Breaks

==== Scene-1 

*Location:* Patrol craft: Jian Suur (Sword-4), Jupiter far orbit +
*Time:* June 12th 2288 

.Readout:
____
Three weeks ago, you were heading for Mars aboard a scruffy but incredibly cheap transporter. Before you could decide what to spend the money you saved on, the transporter was   intercepted by a military patrol vehicle working out of the Chinese colony on Callisto. Apparently the Chinese defense force personnel believed IPS Sugerhill, the cheap    transporter has been involved in piracy. Everyone on the Sugerhill was handcuffed and taken aboard the patrol vehicle.

A few hours ago you and eleven other Sugerhill passengers were loaded onto a shuttle, destination unknown. The rumour was that the Defense vehicle was heading back to Callisto so prisoners were to be transferred to a prison bus. Twelve prisoners secured in a passenger cabin with three guards.

Some of the prisoners say that they believe that they are being transferred to a free station to be released. Others whisper a more worrying story -- apparently some private military contractors do a background check on prisoners that they pick up. Anyone who doesn't appear to have rich or influencial friends end up being sold into slavery - their arrest record is deleted by criminal hackers.
____

The guards of the shuttle become agitated. The following conversation is hearded.

.Readout:
____
**Guard 1:** We're being retasked. Apparently a transporter reports a possible pirate attack but then went dark and hasn't changed course. I'm not risking my neck going onto a deralict, I didn't sign up to fight pirates. +
**Guard 2:** Ha ha, won't be any risk. Captain says the boarding crew is getting decided by a prisoner lottery. +
**Guard 1:** NO WAY, I already lost one vacc suit this year when I was forced to lend it to a prisoner. +
**Guard 2:** You don't loan a suit, you don't get a cut. It's a big ITV, a 30-thousand-tonner. Even if its empty there will be a million in salvage, each. + 
**Guard 1:** A million. Okay, but better be right about this.
____

The twelve prisoners are escorted to the main operations deck and strapped to seating at a large table. Each prisoner draws a lazily fashioned straw. The PC's each draw a short straw. Before this moment, the PCs lived separate lives, now they are link by a momentary act of chance.

The other prisoners appear visibly relieved. Many of them shoot you with concerned looks. Nobody speaks to you but their eyes are saying "it was nice knowing you."

The shuttle's XO gathers you and leads you to the EVA bay and airlock. You are dressed in slightly worn mid-range vacc suits.

The officer, a wirely chinese man in his late 50s grins grimly at you. "Nine times out of ten, everything fine. Everyone happy. Good odds! You not heroes, you not take risks. Go in, report on what you find. If danger obvious, report and withdraw."

Fran gives him a steely look. 
____
*Fran O'Malley:* One in ten is NOT good odds. If it was good odds you wouldn't need to use impressment. By the way, impressment is ILEGAL.
____

The XO's face blanked, making the man's mood unreadible.

____
*XO:* You must think I am a bad man. I am NOT a bad man. But I am a hard man. My duty is to protect my crew, above all else. I'm not impressing you, I'm making you all deputies. Regulation 275.9 'During an emergency situation, the command officers may deputize any passengers if there are insufficient crew to fulfil mission requirements safely.
____
A klaxon sounds. Pumps begin to pressurise the airlock. A guard checks over the PC's space suits. To one PC he tells them not to pull hard on the left sleave as the seam may have a micropuncture.

____
*XO:* All you need to do is check out the transporter for survivors. Nobody on the ship is communicating, now. There's a chance the ship was completely abandoned or maybe the crew are awaiting rescue. Or they might all be dead from a deadly radiation leak, but it that happended we would surely detect it from your suit sensors the moment that you enter.
____

=== Scene-2 I think we're alone now

All PCs have the following equippment/capabilities:

* 1 Worn light-armour space suits with integral comms, head-lamps and wrist-comp
* 48-hour emergency provisions pack
* 4 First Aid packs
* Schematics of the Independent Trading Vehicle Golden Goose (loaded onto their wrist computers.)

The PCs are strapped to a EVATD-79 "huskie", a coffin-sized drone with rungs that astronaughts attach themselves to. The drone handles the maneuvers of an EVA, so is ideal for people with little or no E.V.A experience.

The PCs transfer 3000m between the shuttle and the transport vehicle. The PCs are now free to decide how and where they enter the vehicle.

[NOTE]
====
Pass out the deck arrangement sheet. The airlocks are displayed on the left-hand side (*See below*). The Huskie will maneuver The PCs to any location/airlock that they choose. 
====

image:https://db3pap001files.storage.live.com/y4mZxiXRDVzd1Ftqoq6Lv-GZXZGAKLw3f812Mo-yAaE95r1Py0qGv3u78vobEm-Xb0Eep_wGZvuoWAYm2cA5GttIBGH5rel4YH0ceGziHmZ9qFZGEfQ5Im1F_3TlLGe1WNC-RFDeAO5EksgkF4Wiaj0YHDlQfG1LLVO28bxAMWWXmZmH3AJnIDuDaCKCEkXdy1s?width=724&height=1024&cropmode=none[image]

The PC's may choose to enter at different points. While this is challenging to run, it shouldn't be discouraged. A group of PCs that split up can seriously up the tension as they fend for themselves.

Once the PCs select an entry point (or a number of entry points) then proceed to the section that corresponds with that location.

*BOOM* +

The moment that someone opens an airlock, there's a glow of light. A small module, about 2m long that may have been attached to the transporter fires a projectile in the direction of the shuttle. Instantly the shuttle turns into a cloud of hot, shrapnel-filled gass. Nothing is left of the shuttle, just streaking fragments o-red-hot hull. Gone in a blink.

.Readout:
____
Moments after the airlock opens, you become aware of a sudden brilliant bright flare. Turning to the ball of light, your vision is momentarily lost by the glare. The light is coming from the direction of your shuttle. As your vision clears you now see tumbling fragments of hot metal and plastic. The shuttle has been destroyed. 
____

=== Chapter Two - _Free fallin_

The PC's all go into shock. Their breathing becomes erratic and they need to make a difficult (8+) endurance role or suffer from panic. This increases the difficulty of all actions by 1 or 2 for D6 minutes. 

==== Dancing in the Dark

*The deralict vehicle is an independant transport vehicle called the Golden Goose. Readings show that the power is on but the engines are off, so the Golden Goose is coasting along. This means no acceleration, so no simulated gravity. Many onboard operations will require Zero-G skill checks.*

The ITV Golden Goose is a Languedoc-class 30,000 ton heavy hauler. Originally built in the 2190s, the few that remain in operation have been retrofitted with updated engines, although their moduler design is otherwise unchanged. The vehicle is assembled around a 200m-long graphine-lymar composite stem. Behind the command module, a number of habitation decks are slotted-in. A single hab-deck can be fitted for a dedicated hauler that will only carry a crew, or upto twenty decks if the vehicle is going to be used as a slow passenger carrier. The hab deck design is an open ring, so that it can be easily slotted onto the stem, although the clamping is perminent, so hab decks can't be ejected. Removal requires a refit at a construction yard.

image:https://db3pap001files.storage.live.com/y4mHV_uhTQjk01vl0KeIQAwNxNDFlnIGPRWklJ7Gyk6JUtWj_TwWp_5DqgD2ZchPku8iTz4ArqjkYIX-rmTw1werVUWxPWdGYetGmTrUlc85uDB-IFiCrFZC57vWSPT7enzwnbZLLygQT0vE-Z-g5yZ3fCH5QVbA2OhqelfsOTSsrI2F-lcjRAjSMtR7-02nt0V?width=1024&height=616&cropmode=none[image]

The cargo modules come in various shapes and sizes, the Golden Goose carries two cargo modules that clamp onto the stem to form a cylinder. The two modules offer 9 identical decks, each is 9m, allowing the transportation of very large items, such as vehicles, plant machinary, even small space vehicles. In order to load and unload, the two halves uncouple and are moved away from the stem to make the large cargo doors accessible, while in transit there are no external hatches and the outer hull is heavily reinforced and shielded.      

The cargo modules are held between decks nine and twenty, which contain machinery for seperating and reconnecting the modules for loading and unloading.

The next section is huge torus that stores the vehicle's reaction mass, either water or, in later models carbon-diamond dust. Three seperate fusion power plants are fitted within the hole of the torus. Two plants are run, leaving the third in cold-shutdown as a backup. Most of the generated power is used to supply the drive module which is equipped with six Amarok-71 QE-thrusters for a sustained 0.5g acceleration. Fully loaded, this gets a Languedoc from Earth to Mars in 8-14 days. 

[NOTE]
====
.Describing the Golden Goose
This is not a standard space vehicle. You might be generous and describe it as a "classic" but in truth, this is an "old banger". Most of its internals, engine, and systems have been replaced two or three times during its 80 years of service, although most systems are still probably about 20-years old. Nothing is outright grimy but almost everything is showing wear-and-tear. Most things work as they should and mostly they work first time, but not always. _Don't overplay "rickety", but once in a while remind the PCs that this maybe not the most reliable or safest transporter._
==== 

==== Every Breath you take

T-12 is linked into the cameras and sensors that monitor most goings-on aboard the Golden Goose. This includes pretty good radio reception from the PCs space suits. With this in mind, play T-12 as always, or at least nearly always one or two steps ahead of the PCs. PCs might make skill rolls to tease out that they're being monitored. If they work it out, they can start disabling cameras and mics. They can turn encryption or line-of-sight modes on their vacc suit radio to prevent eavesdropping. Taking these steps make T-12 seem far less omnipotent - however it will also compell T-12 to active PLAN-BETA, where it activates additional labour droids.

==== Under Pressure

There are a number of "side-quest" activities that provide some focus for the PCs as they bounce around the Golden Goose. They're not essential to the conclusion of the adventure, but provide some sense of urgency and provide opportunities for role playing fun.

===== Captain's orders

Like most of the crew, Captain Wash is sealed into her stateroom and is trapped. She's aware that Ross, her husband was located in the Engineering Control room at the time that the incident started. She is in a panic that Ross is trapped there, because there's not stores in that location. In three days, Ross may have slipped into a comma through lack of water. Wash will implore the characters to find Ross and provide assistance, as a matter of urgency.

*outcome:* In fact, Ross was dragged from Engineering Control and was locked into Deck 21. Ross managed to break into the main Power Plant bay, in the hope of finding an access hatch or air supply duct to sneak through. He failed to find a way out, but he did find a secret party stash, a case of party materials, including 4 bottles of red wine. Currently Ross is sleeping off the second bottle. He has a cracking headache, but is otherwise in good health.

[NOTE]
====
.Wine-only 
Alcoholic drinks are dehydrating, the remove water from cells, but they also provide water. Most wine will balance towards hydration, so you won't die drinking only wine, at least not as quickly as drinking nothing, or -- it has to be said -- drinking your pee, which will likely only extend your surival from 3 days to 4. As a bonus, red wine also contains some nutrients, so it substitutes for a bit of food. 
====

===== Lars

Lars Anderson is the cause of this big sorry mess. He spotted some inconsistencies between the manifest description and the T-12 container. He opened up the container and decided to turn the labour droid on, mostly because it didn't look like any labour droid he'd ever seen. Things turned bad, and Lars knew he was going to be in heaps of trouble for it, so he absolutely threw himself at the problem. T-12 broken Lars arm and caused so much bruising to his legs, that Lars can't walk. Lars managed to crawl off and is currently laying behind machinary in top (A) on Deck 20. He's delirious and will babble while laying in a semi-conscious state. He's critical ill as his broken arm has gone bad - there is  dark red and purple marks along the fracture area. He needs immediate medical treatment to avoid death. There's nothing that can save his arm, he'll either need to have a new one grown, or he'll need to go cyber.

===== Anya

Anya Fillipova, one of Lars Anderson's repair Maintenance and Repair Team members managed to evade T-12 long enough to get into a vacc-suit. She's actually set up a base on Deck 7, living in one of the EVA marshelling rooms, which is baracaded from the inside. She uses her vacc suit to make supply runs, and to attempt to rescue other crew members. She may be encountered if the PCs explore deck 7, or she might be encountered as she makes a supply run, heading into another part of the ship. A rasping figure in a large dirty space suit, may be startling to the PCS -- likewise, a chance encounter may cause Anya to panic and make an attempt to run away.


=== Deck descriptions                     

==== Command Module

image:https://db3pap001files.storage.live.com/y4mUGDji4EfnaNKZ31Eeo5M3AqKSBOOfDU1kP1KKuP_W-Q3UcGB9jbbcTgHylKuRhz_cFJwZb4YQrBEZnQy463RuZ9hYgrFyqVnJd4A00IHHXQINj_eUhSew5aH1bJ-ovL1yA6dYAtIVGR8O5rQDY3BgyRxdzDGOeB-NW5kshO914hi8-CDagsQmVULv1EEq4Md?width=724&height=1024&cropmode=none[image]

===== Deck 1

*(A)* Avionics deck is seperated from Deck 2 by grilling, with lots of gaps.|Ladders in the central stem of Deck 2 can be used when the ship is under acceleration.

No signs of any trouble. Ships systems appear to be unimpaired but an *+8* piloting or computer roll will reveal that the ship's systems are locked down from engineering.

____
This deck is located at the front of the vehicle, it's an open space, filled with system cabinets, cabling and monitors. Metal grilled walkways separate it from the deck below. There are no access tubes down to Deck 2, just ladders, which lead down into Deck-2's access tubes. While the Goose is not accelerating, it's possible to move between Deck1 and Deck2 without using the ladders. There's no sign of life, or any obvious problem. Everything is on and working.
____


===== Deck 2 (AVIONICS)

*(B)* Backup systems. This has a simplified control systems duplicated from actual command deck (Deck 3). At the moment this room is in hot-shutdown. This means that everything is on and is duplicating the status of the control systems  on the main deck. However, most of the holo-displays show a bit "Lock-down" label. Piloting roll 6+ indicates that this means that the vehicle's controls are disabled. This is standard procedure if there is any threat that a hostile force has taken control of the command deck.

There's a side room (Emergency Locker) that contains emergency equipment. There are two large lockers that require a biometric scan to open. These may contain sensitive materials, fire arms or controlled substances. There's no way to get into these cabinets, they can only be accessed by senior crew members.

*(+C+)* This room contains a briefing table, chairs. Some emergency equipment cabinets.

*(D)* More backup systems. Big metal cabinets filled with hardware, emergency power cells.

===== Deck 3 (COMMAND DECK)
____
You can immediately tell this is the command deck. Everything is triple-reinforced. The bulkhead materials are made of exotic materials and the crew section is protected by a secondary wall. Outside the wall are wall mounted cabinets and boxes that carry cables and piping. The ring-shaped outer corridor ends in an airlock system that opens on one side into the stem access tubes, and opens into a command docking airlock on the other. Emergency Vacc suits hang on the wall next to the airlock.
____

*(E)* Bridge. There are three crew positions for a pilot, a captain and a systems officer.
____
The deck is dark. Lit by a dim red emergency light. Most screens display the words "Lockdown". There's a coffee beaker floating near a wall. Droplets of coffee hang in the air. There's no signs of the crew. No obvious damage, or signs of violence.
____

*(F)* Command Ring. airlocks to the stem access system and the command docking airlock.

==== Stem Access

image:https://db3pap001files.storage.live.com/y4mb2yRdOfrVskdw37G_iAGbtOEzL7AOPcnBLNGYrlOCA3aFFrWYt2qAmX7WFFSkX3CGj-TtULJOs01WN74CzSKB2mlX92OR93q3YP82z196oNmJZAxUm6c6rX2XMwjbecDhzfo_-ApXyA0aeNni8XOeClhmIqW_RLALyu_ggqw7PY2yE1PM6zwahvr0hMynMrz?width=635&height=377&cropmode=none[image]

Running almost the entire length of the Golden Goose is the stem, a tube of incredibly strong exotic material on which most of the rest of the vehicle's elements are attached. At the centre of the stem are access decks that connect the stem to the surrounding module, through an airlock or hatch.

*Transit Pod* +
 At the very centre is a Transit Pod, (labled as "Rapid Transit" on the sliding door). It's a souped-up elevator that responds to a button call. When it arrives at your deck a sliding door opens, you board it and strap yourself to the wall, then select a destination deck. Transit times are very short, end-to-end in 30 seconds, which pulls some gee. Travelling in the pod is unconfortable but it gets you from one side of the vechicle to the other in seconds, which could be critically important.

There's no possible access to the elevator chamber. It's not pressurized and the operation of the pod would hit and then catapult anyone in the shaft to their likely doom. When the vehicle is under normal motion, the Transit Pod shaft is no different from a lift shaft. Falling hundreds of metres under low-g is still likely to be fatal.

*Ladder and rail tube* +
These tubes contain two ladders, one to the left and one to the right of entry, allowing two people to pass each other while travelling up or down the shaft. In the centre of each ladder is a rail that you connect a safety harness to. Wearing a harness that connects to the rail is a mandatory part of the ladder operation. If you enter and don't connect your harness, the tube's emergency valves close. While operating in the tubes is not risky in zero-g, the moment the engines go on, there's an obvious risk of unexpected falling. The rail system allows you to climb or pull yourself along the tube (in zero-g) at quite high speed, it only locks when the motion is sudden and under high force.

===== Deck 4 (SYSTEMS)

*(G)* Systems Control. Banks of monitors and controls handle most systems that are not part of the vehicle's propulsion, navigation or maneuvering. This includes life-support, communications, security. There's a single crew post for monitoring. This console is also locked down.
____
To the right of the entry hatch are a load of plastic boxes. Some are opened and various bits of supplies and equipment float around them. It looks like someone was looking for something and left a mess. The stuff is all random like basic meds, ration and battery packs.
____

*(H)* Systems Ring. This deck contains backup life support systems. Pipes and machinary that handle water purification and air filtration.

==== Hab Modules

image:https://db3pap001files.storage.live.com/y4mwu0QMOxXlAHggGNhprGi_s75CTF1YfJ9nR-BC_mOxFfS8Tbum3NluZhdECWXMvtM-fderghyXzonowAdBF0JEWUPEb7TzJeL5Bn1enS1r5EAovk2_IHDDxP53a31ERv8SgLNG-CkcuZauQsLzpNp2Rn63s2u1nebgqRJG2mWQwdXLFimcU2Dr3IE1SUk89_X?width=724&height=1024&cropmode=none[image]


The Hab modules are rings open at one end so they be slid onto the vehicle's stem. Each of the four decks are identical in layout, although only the top deck was in use during its current trip. The other decks were being cleaned prior to picking up passengers. If you look at the deck arrangement diagram you may notice that the decks don't actually stack together, there's a 70cm gap between each deck. The only way to travel between decks is via the stem. 

[NOTE]
====
On transporters that are set up for large numbers of habitation decks, the emergency airlocks on each deck can be fitted with inflatable access tubes to provide additional access points. This arrangement is not in use on the Golden Goose, although individuals wearing vacc suits can move between decks.
====

==== Hab Decks

===== Deck 5 (Habitation)

*(A)* *Emergency Airlocks* - The top one is designated for entry only. The bottom lock leads to an EVA room. This airlock leads directly into the corridor/utility space.

*(B)* *EVA room* - This room contains equipment for storing, getting in and out of vacc suits. There are three emergency vacc suits hanging in the opening on the bottom wall.

*(+C+)* *Lounge* - A large L-shaped room that contains couches, chairs and tables. On the inner wall, mounted against the stem are various food and drink vending machines.

*(D)* *Single-occupancy Stateroom* 

*(E)* *Single-occupancy Stateroom* 

*(F)* *Double-occupancy Stateroom* 

*(G)* *Double-occupancy Stateroom* 

*(H)* *Double-occupancy Stateroom* 

*(I)* *Double-occupancy Stateroom* 

*(J)* *Double-occupancy Stateroom* 

*(K)* *Double-occupancy Stateroom* 

*(L)* Locker/Safe

===== Deck 6 (Habitation)

This deck has exactly the same layout as Deck 5. Life support is running so the deck may be accessed. There's no sign of activity.

===== Deck 7 (Habitation)

This deck has exactly the same layout as Deck 5. Life support is not running, although the central stem is still accessible, there are sliding doors blocking the two entry ports into the deck. It's possible to access this deck via the emergency airlocks.

===== Deck 8 (Habitation)

This deck has exactly the same layout as Deck 5. Life support is running so the deck may be accessed. In the stem chamber, there is tape over the two entry ports into the hab deck. There's a wall mounted e-poster that reads "Stay out: Cleaning in progress". Someone has written "Say no to smelly passengers" in pen at the bottom of the poster.

===== Deck 9 (Forward Cap)

The vehicle's cargo hold modules are clamped between Deck 9 and Deck 20. This foward cap contains equipment that pushes the two cargo modules appart. Either the two cargo modules split appart to create an opening where cargo can be removed, or the modules are ejected so that they can be docked for 
This deck has exactly the same layout as Deck 5. Life support is running so the deck may be accessed. There's no sign of activity.

The stem Access section is surrounded by a ring corridor that leads into the utility rooms and the long stores. Additionally, there's an airlock in the ceiling that leads to the stemp external ladder/rail system which runs the entire length of the step, leading up to a corresponding airlock at the top end of the stem. Should the stem access system become impassable, this system can be used to get people about.                                                                                                                                                                            

*(A)* *Utility room/workshop* - The two largest rooms on the deck are designed to be multifunctional. In the case of the Golden Goose, the top A has actually been turned into a gymnasium with various floor mounted exercise machines. In the tight corners of the room on the side of the stem there are large cases for machining tools and some 3D printers. In the lower (A) room, the workshop tools are set out, ready to fabricate or repair machinary.

*(B)* *Stores* - Two rooms contain storage bins filled with parts and materials.


==== Cargo Modules

The Golden Goose carries two cargo modules, each module connects to the step to form a single cylinder. For loading and unloading, the two modules separate and move away from the step to allow access to the roller-shuttered ports. While all the other decks on the Godlen Goose are three metres heigh, the cargo decks are nine metres, floor to ceiling. This makes the cargo module large enough to carry a wide ranger of shipping container types, or large items such as vehicles or plant machinary. 

image:https://db3pap001files.storage.live.com/y4mYbX0JGKdreXlloTJGeIB_szuiZlVQz5Vx8SmFO8qYBmAeyePTVKV-bZdjAcbltpAF1TTkDO1HbNeABf3Y0Z5gZRRzJoamNpgPCkNHy4_L9rjytyFGqD9pu4g77WjVOrAeJKsZUvxvkGnQQALzM4p3MJua4GEyiRz5zJpxMeGi5OmUsOxHdX0BSZV1RPvsr5F?width=1024&height=704&cropmode=none[image]

===== Deck 10

image:https://db3pap001files.storage.live.com/y4mVOIei7qgPctmVuR5d121HVhL9uIQP0orXBYT1UIT6FKi_mNiMRlbW9qowJ2heh4iuwgv3r9yG2mtmUwAjszEUYTudU3H914G1sgpRq0isBvmUKbDI_b0ouTsE0gekSb47_zkD9oWnNsl5jzE8bNJNgtLwPDNNyytY6GsacYouJT4lgY1qqBZnBRc7WXek_pe?width=724&height=1024&cropmode=none[image]

*(A)* *Stem Access System* - This area is consistent all the way along the length of the transporter. Note that everything beyond the hatch doors in A are part of either of the two cargo modules. 

*(B)* *Clamp room* - When the cargo containers separate from the transport, this space opens out to vacuum, as the outer wall of B is actually part of the wall of the cargo container. The wall mounted equipment, must of which is part of the clamp machinary, is all vacuum hardened and certified for space operations.

*(+C+)* *Starboard Hold* - Large cargo space filled with 3m x 12m shipping containers. There are ladder tubes on the other walls that lead just between the cargo decks.

*(D)* *Marshalling Area* - This part of the cargo decks has a crain system for moving shipping containers between decks. There's a 15m x 18m openning between decks. This opening has a sliding door that can isolate each deck from the rest. When the hatch is open on all nine decks, there's a nearly 200m drop.

===== Deck 11

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed. The floor and ceiling hatches in the (D) areas are all open. There's no sign of activity.

===== Deck 12

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed. The ceiling hatches (leading to deck 11) are open but the floor hatches (leading to Deck 13) are both closed. There's no sign of activity.

===== Deck 13

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 14

This deck has the same layout as Deck 10, although there is noticably more superstructure on the floor, indicating that this is the centre of the module. Life support is running so the deck may be accessed. The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 15

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 16

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 17

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 18

This deck has exactly the same layout as Deck 10. The hatches are locked. It looks like fault in the air pumps is caused the pressure in the chamber to drop considerably. The hatches lock to prevent an decompression event.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. If the PCs want to get access to the cargo decks, they can depressure it, then enter wearing a vacc suit. There's nothing special here.

===== Deck 19

This deck has exactly the same layout as Deck 10, although there are no floor hatches. Life support is running so the deck may be accessed. The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

image:https://db3pap001files.storage.live.com/y4mWvdRW0WS76GKcAj16uen9fYrd0NK80GXJ2GNSnGbClxNn_unyEcHUIxiEXWJsfRMe3094BiOb1pyfKDwbHT0bZlr7NxYV9rmU_YSdjzu5tg7Pd5mdwuKAdDNsQGY6NWH48hnkihriDazI4nbRpXe8Nrsu9MmfqfvIw7h13H5Xe6E4R4dK-tYu7Vm5S3oC40A?width=724&height=1024&cropmode=none[image]

===== Deck 20 (End Cap)

This is the reverse of deck 9. The clamping machinary connect to the bottom of the cargo containers. There's also no stem airlock system as from this deck, the stem integrates into the rear sections.

===== Deck 21 (Engineering Control)

image:https://db3pap001files.storage.live.com/y4m4U2137eC1IdHbDkV4c97hJDjq09kmNicMI45e7aRQC6pj5YI_P_a-fkUg1vX80W-fXB3hKiunF7ahanb0U7JZIVCBg5VY7xf_Mw5NgBtH97jL3V442lkNwmFAeY_Ii_yIYCfuvH_KbwEPuB97f6FdsDUgcfHW9bhLY50WvsZDwBilK7faxPMZX-Zq2NK_pWA?width=724&height=1024&cropmode=none[image]

This small deck is the contains primary control for the entire transporter. In the locked-down state, all control over the ship is held here. The control room forms a ring around the stem, with a single antechamber. T-12 guards this room and only leaves when it observes that nobody on the ship is approaching the room.

===== Deck 22 (Power Plant)

The Fusion deck contains three fusion power plants in a large changer that is 9m high. However, access to crew is limited to a control room that is a standard 3m height. There are hatches at both ends of the room that lead onto a walkway with a railings. The white in the middle of the deck plan is open space that rises 3m above the deck and drops 3m below. When the vehicle is not accelerating, its possible to move around this chamber.

The Power system is mostly autonomous. Every twelve hours, the off-line powerplant starts up, once confirmed that it is running properly, one of running powerplants shuts down and undergoes a purge and becomes the off-line powerplant. This operation happens automatically, even in lockdown.

===== Deck 23 (Drive Deck)

The drive deck is a series of access spaces and walkways inside the giant thruster system. Everything is heavily engineered and reinforced. There are countless cable rails and piping going in every direction. On one side of the deck is an Emergency airlock. There's no EVA marshalling area, the airlock is mostly intended for entry from outside, should the stem access become blocked, rather than as an escape route.

=== Chapter Three - Fight the Power

This chapter deals with how the PCs conclude the mini-adventure. The most pressing objective deals with Deck 21 (Engineering Control).

The following list of strategies are available, although the PCs should be allowed to come up with their own plan, which as GM you will need to assess, to decide if it can work.

* *Ripley maneuver:* Lure T-12 to an airlock and flush it out into space. This only works if the PCs locks down all airlocks as T-12 is equipped with mini-thrusters and will otherwise work his way to another airlock and re-enter.

* *Lock-up:* Lure T-12 into a room that can be locked. Doesn't work for long as T-12 is equipped with a blow-torch, so can cut itself through any wall that isn't the outer-hull, or any hatch that isn't a surface airlock.

* *Flytrap:* Lure T-12 into an improvised trap using MBT-40 bonding tape. Tricky but at the risk of some bruising this works if all the PCs work together and quickly enough that T-12 doesn't work out their plan.

* *Firmware Update:* Take the firmware update catridge from T-12's storage box on Deck 10 (Cargo) to the Deck 21 (Engineering Control) and initiate a firmware update. This actually takes quite a long time, first the PCs profiles need to be uploaded into a computer file system directory, then uploaded with the firmware. The firmware update forces a 3-second shutdown, but provding the PCs profile information is included, it will stop treating them as intruders, they will be able to command T-12 to stand down. 

*Down with Lock-down* +

The control room itself has heavy-duty panels that carrying multi-function-displays (MFD) that can be switched to control almost anything on the transporter. The most urgent action the PCs need to take is to remove the lockdown. This is handled by a Difficult 8+ Computing roll. A critical failure (unmodified 2) will result in the lockdown becoming perminent. If the character performing the task also has piloting or engineering skill, they get a +2, as they'll have training in handling vehicle lockdowns. 

The moment that the lockdown is removed klaxons will sound. A woman's voice will sound out. "Warning. Emergency Maneuver in 3 minutes. Please strap into a g-force rated seat." After three minutes the ship will perform a rapid spin to place the thrusters in the direction of travel. The thrusters will ignite and the vehicle will slowly build up to 0.9g of acceleration. From this point on, everyone on the Golden Goose now experiences simulated gravity.  

*Firmware upgrade* +

If the PC plan to stop T-12 by forcing it to undergo a firmware update, this is where it has to happen. The top-centre most console that sits in a cut in the stem is the main computer terminal. It's controls are isolated and can't be accessed from anywhere else. To complete a firmware update requires a difficult (8+) Computing roll. The task takes 10 minutes. If the PCs try to complete the upgrade in 5 minutes it becomes Very Difficult(10+). However, if the PCs slow down and take their time, the task becomes routine (6+).

The tricky part is keeping T-12 from stopping the action. If the PCs have drawn T-12 away with a distraction, it will immediately know that the central computer has been accessed and will attempt to withdraw and retake control of the Engineering Control Deck. 



=== End Credits

*Location: Unknown*
____
*Executive:* Developing Trajan under a cover program appears to have saved the project.

*Off screen voice:* Yes.

*Executive:* In fact, this incident has provided a great deal of useful data. A single unit disabled and captured a large transport. Operating under the fake Anti-piracy AI. Ironic that the unit turned out to be an effective pirate.

*Off screen voice:* We're not building robot pirates. Trajan is an army. 

*Executive:* In that case, maybe we should engineer an incident that field tests Trajan in force.

*Off screen voice:* Yes. {pause} When we're ready.
____


=== Appendix

==== Trajan-12-x 

Prototype anti-piracy droid. 


==== NPCs

==== Almona Wash (Captain)

Captain of the ITV Golden Goose. Almona is a tall, slender, pale-skinned woman with long black hair. She is dressed in a pale yellow jumpsuit. At 33, she's young for captaincy but her no-nonsense approach to life make her a good fit for the role. She has the respect of her crew because she is extremely loyal and the admiration of her peers because of her high competancy. Almona's worst habit is trying to own every problem, it makes her seem over serious. Ross Mcalphine is the one person who can lift the weight on her shoulders with a few words. 

====  Ross McAlpine (Lead Engineer)

Chief engineer of the ITV Golden Goose. Ross is a muscular man with red hair and a broad smile. He married Almona two years ago, although Almona says that she won't take his name until they retire and start a family. Ross is the unflappable sort whose mere presense can calm a high-stress situation. His worst habit is whistling tunes that get stuck in your head.

==== Lars Anderson (Maintanence)

Lars is a brutish-looking man who looms over most other people. However, it soon becomes clear that he is a sweet-natured giant whose tendancy for jokes and tom foolery frequently get him into hot water with Captain Wash. Always joking, Lars is difficult to take seriously but when matters become serious, his willingness to take personal risks for others make him a popular member of the crew.

==== Tony Pendula (Security/Cargo Handler)

Tony is a short, light framed man of British-Greek ancestry, although he is actually Martian. Tony is a cheerful but laconic man whose small stature leads him to be overlooked. He tends to  skulk at the back of any group. He takes his duties seriously and while Tony and Lars are good friends most of the time they spend together on duty tends to turn into banter.

==== Simone Acosta (Computer/Systems Engineer)

Nigerian-Luna woman in her early 40s, Simone is even taller than Almona, but has a more muscular frame that gives surprising physical strength. Simone is extremely competent and capable but does not suffer fools gladly. She remains aloof in the company of strangers or people that she doesn't respect. She's ambitious and wants her own captaincy but recognises that Almona has leadership qualities that she doesn't have, and would never question an order, even if she didn't agree with it. However, in her specialist field, she's the boss.

==== Anya Fillipova

Anya is a Russian-Luna national, in her early 30s. She's tall, with an athletic build and wears her long brown hair in a ponytail or under a cap.  She's part of Lars Anderson's maintanence team. Considered by the rest of the crew to be something of a loner, Anya is one of those people who just can't settle anywhere. She's happy enough working on the Golden Goose but has ambitions to return to Luna and set up as an independent maintenance contractor.
