== Solar Gazetteer

image:https://db3pap001files.storage.live.com/y4mF6J7uTJFMEg352kCGKuxS_WAlsWwQhSMh332HDzWNRgTgcUl1Z0Z9DN0Jux20s7qtj7RMTAw2TNd-uXuJHvLguZ-vN2kd8FPdxZ60Wpb-fLh_Mh-ErSDjZ5QUZKm3Q1MTuOVjBM3Rcq4Lqt3qWNHYTYqAnNlTN6KMHZxANhEjXqRJFPt6jgiiLfD8uEibQxB?width=1024&height=354&cropmode=none[image]

The following guide covers all the planets and major masses in the solar system, along with their corresponding stations and colonies.

=== Sun

=== Icurus Station

|=======================
2+| **Icurus**      
|*Diameter:*   |2 km
|*Mass:*      |Negligable  
|*Gravity:*    |Negligable   
|*Escape velocity:* | Negligable
|*Atmospheric pressure:* |0 (vacuum)
|*Surface temperature:*|-10/+800
|*Surface radiation:*|20 SDU
|*Solar Day:* 10 minutes
|*Year:* 30 days
|*Distance from Sun:* 0.2 
|=======================

There are no colonies or large settlements inside the orbit of Mercury. There is a reseach and monitoring facility built inside Icurus, a small captured asteroid that was manoeuvred into its close solar orbit to provide a shielded location for a monitoring station. Icurus rotates to simulate gravity and to ensure that the intense heat felt at that location is applied evenly across its surface. The station's habitats are burried deep to provide adequate heat and radiation shielding. The station manages an array of solar monitoring satellites that ring the Sun and perform deep scans, to provide reliable predictions of storms. Satellite maintainence, monitoring and solar reseach keep about 100 staff occupied, with most staff working three-month assignment before returning various Earth universities. Icurus station is an isolated place to work, only very specialised, heavily shielded vehicles can reach it and they follow a four trips per-year schedule.

NOTE: There's now an inflatable heat blanket that can be deployed across the hull of suitable space vehicles, allowing them to travel closer to the Sun. The heat shield is intended for short emergency transit as more than a few days of heavy neutron exposure is dangerous. 


[cols="10%,90%"]
|===
2+|Settlement profile: Icurus Station

|*Function:*
|Science Outpost

|*Founded:*
|3rd July 2255

|*Alignment:*
|International. The outpost provides a vital service for everyone in the solar system. As such, the station is managed by a board of directors made up of senior academics and AIs from all of Earth's biggest universities.

|*Ethnicity:*
|Mixed. *Languages:* English, French, Russian, Arabic, Chinese

|*Type:*
|Asteroid-spun

|*Tech-level:*
|Old-standard

|*Class:*
|Cozy

|*Population:* 
|20 + 80 guest reseachers/engineers on 3-month tours.

|*Government Type*
|Civil Service Bureaucracy

|*Law Level*
|Restrictive

|*Attitude:*
|Closed

|*Social Type*
|Centrist
|===

=== Mercury

image:https://db3pap001files.storage.live.com/y4mkuAzdlP8JesFStGctLgQKY51eEwSPrjWGnb8S_YyS3nR-AMOjqMdTvoH4i6_Frx09GJ7uyObNzx39z65Gfqmc6yFm-F9H0t7obid-kTzDsbZfJfkDiO1roOXODThGl3MJCNqbL-k4CilpOST7wQRFie1KVb7z9xZ-75Gpe5T7f2DkLcCZBDwq7WeLtbuJnEY?width=1280&height=600&cropmode=none[image]

|=======================
2+| **Mercury**      
|*Diameter:*   |4880 km
|*Mass:*      |0.055 Earths    
|*Gravity:*    |0.38g     
|*Escape velocity:* | 4.3km/s
|*Atmospheric pressure:* |0 (vacuum)
|*Surface temperature:*|-180/+430
|*Surface radiation:*|7 SDU
|*Solar Day:* 176 days
|*Year:* 88 days
|*Distance from Sun:* 0.4 
|=======================

The smallest planet in the system, and the closest to the Sun, Mercury is characterised by extreme heat (450 degrees Celsius under the midday sun) and extreme cold (minus 170 C in the evershades). Geologists have long agreed that Mercury is a planetary remnant -- the core of a larger planet that lost much of its rocky mantle coat in ancient punch-up, probably a collision with another proto-planet. Mercury has almost no axial tilt but its eccentric (egg-shaped) orbit creates extreme seasonal temperature variations.

==== Settlement

A research outpost was established in the northern polar region, on the wall of a crater that never falls under direct sunlight. Large deposits of water were found there, a discovery that makes resource extraction economically feasible, as large water deposits allow any settlements to create fuel locally and be essentially self sustaining.  Mercury has accumulated lots of minerals from asteroid and comet strikes, making it a buffet of useful construction materials. However, counting against early settlement and exploitation was the fact that reaching Mercury's orbit requires a lot of Delta-v. Mercury is essentially zipping around the sun at at very high speed. Vehicles that travel to Mercury need to burn a lot of fuel to get into oribit. Then, if they want to land on Mercury they have to burn more fuel get rid of their speed. The lack of atmosphere means that you can't slow down using atmospheric breaking, like with Earth or Mars reentry. For these reasons, Mercury was settled relatively late, long after the other inner planets and the asteroid belt. 

In 2288 there are just two medium-sized settlements on the planet, mostly supporting water, Helium-3 and mineral mining. A further complication for colonization are the frequent quakes, caused by the fact that Mercury is contracting as its liquid core cools.

*Ground Settlements*

==== Aljadid Toubkal

Moroccan colony constructed to accommodate the High Atlas Archology's expanding population. Aljadid (New) Toubkal is constructed under the mountain at the centre of the Kulthum crater. The colony's underground structure was built by digging out and extending an earlier mining facility that was established to dig out rare earth metals. Kulthum Crator, named after  Umm Kulthum, a 20th-century Egyptian singer, songwriter, and film actress, is the location of extensive industrial sites, many now mothballed since the closure of the mines. In 2250 the colony government fell to our military coup, after a period of rapid economic recession and hardship. The High Atlas government made several attempts at military intervention but each failed and resulted in the ruling clique of generals gaining more popularity. In 2280, power return to a civilian government, lead by Tarik Kharbouch, an effective technocrat who was groomed for power by the aging generals.

In recent years there have been suspicious activities among these disused sites, Aljadid Toubkal's government has rejected all claims that criminal elements are now operating from the region, under the government's protection.  


[cols="10%,90%"]
|===
2+|Settlement profile: Aljadid Toubkal

|*Function:*
|Large colony

|*Founded:*
|21 August 2163

|*Alignment:*
|Moroccan (High Atlas Archology) Colony

|*Ethnicity:*
|Mixed. *Languages:* Arabic,Berber and French

|*Type:*
|Burried Modules

|*Tech-level:*
|Old-standard

|*Class:*
|Cozy.  

|*Population:* 
|2 million

|*Government Type*
|Non-Charismatic Leader

|*Law Level*
| Moderate

|*Attitude:*
|Open with visa

|*Social Type*
|Advancer stage 1
|===


==== Hidayatullah


==== AMP DX229-71

*Population:* 10 +
Autonomous Manufacturing Plant DX229-71 processes various raw materials, then launches them into an orbital stockpile using a mass driver. A caretaker contingent of humans live at the station. The station is mostly surface-based. 

==== Other settlements

There are between thirty and fifty independent mining settlements. These pop up and then dissapear as they're mostly looking for small lodes of rare earth metals delivered to the surface by asteroid impact.


*Orbital Settlements*

==== Idunn

*Population:* 7000 +
Originally a German-built research station. When the research ended, the station was sold a Swiss businessman who expanded the station to become a Swiss-German Colony.

==== Garaventa

*Population:* 12,000 +
Italian fledgeling colony, has the best orbital spaceport around Mercury which manages 90% of shipping to and from Mercury.

==== USEDS Finingley

*Population:* 300 +
United States of Europe Defense Station, monitors the inner system. Maintains two active warships.


=== Venus

image:https://db3pap001files.storage.live.com/y4mKcorB-1QUXlBxbd1rUsaAJhDEmuaYm-DkpRCqDl0w1AC0x2B0JnnbRY2x016rKgWqhp7WvZ4VTggsw63D0I-O8ghy2aCAV4oFsZ-sb5MpAMqPiGPPAZLXqh6YCZ1Nx256NKPZzOwTRWjWNNRxYjZCDfbQP_DVBXHakb-9EbD1u2xXzmNqdZDFwIOoLz62NTi?width=1024&height=480&cropmode=none[image]

|=======================
2+| **Venus**      
|*Diameter:*   |4880 km
|*Mass:*      |0.94 Earths 
|*Gravity:*    |0.8     
|*Escape velocity:* | 10.4km/s
|*Atmospheric pressure:* |92 
|*Surface temperature:*| +475
|*Surface radiation:*|20 SDU
|*Solar Day:* 116 days
|*Year:* 225 days
|*Distance from Sun:* 0.723
|=======================

Named for its beauty, Venus is a hellish world with some of the most hostile surface conditions in the entire solar system. It's so hot down there on the Venusian surface that anything not made of a high-melting point metals or ceramics ends up melted or erroded. There have been several attempts to begin terraforming operations but each has ended up discontinued, in part because of the difficulty of operating in such hostile conditions.

==== Experimental Atmospheric Outpost

Historical site. Like a floating museum, maintaining the original research output.

*Atmopheric Settlements*

==== Pegasus Station

*Population:* 1500 +

An under-construction floating colony, the pegasus project is constructing a vast lighter than air platform, situated 70km above the burning surface of Venus. While the surface of Venus is like the inside of a kiln, the upper atmosphere has a zone where settlers can walk around with just an oxygen mask and acid resistent suit. When completed, Pegasus will provide more than a square kilometer of surface area on which to construct inflatable habitats. The top of the habitation is used for greenhouses and a shuttle recovery platform.

*Ground Settlements*

==== Hadius 

Hadius was the first settlement established on the surface of Venus. It is also the first settlement to falter and fail. In 2200 the Lone Star Archology declared that it was going to establish a mining colony using advanced cooling technologies. News of the project created a lot of interest. Lone Star had little experience or expertise in extra-terrestrial construction, never mind construction in the most challenging environment in the solar system. It's not clear if the exercise was a vanity project for the archology's president, or fulfilled some other agenda, but the project went ahead. The engineering team created a specially designed AMP which landed on the ground then folded out a large array that would start to vent heat into space cooling the area around the AMP. The finished structure uses various high technology cooling methods to stop the settlement from cooking. However, failures occured, deaths occured. The project quickly developed such a bad reputation that almost nobody was willing to sign-up for relocation. The initial tranche of settlers received extremely generous relocation packages but bribing citizens to move to hell was not a sustainable plan.

Lone Star, desperate to makeup the massive shortfall in colonists took to offering criminals the chance to "emigrarate instead of incarcerate". When the original settlers learned that there new home was essentially being reclassified as a penal colony there was unrest and hostility between different groups of colonists. The relationship between Lone Star and the Hadius colonial administration got steadily worse, until 2230 when the various factions in the colony decided to stop fighting each other and joined forces to take control of the colony. Lone Star Archology, rather than digging in its heels and attempting to retake the colony, instead walked away from what was seen as a massive money trap. Without the Archology's financial backing, the newly independent Hadius couldn't maintain its complex environmental systems. Over the course of the next twenty years, large sections of the settlement had to be shut off. Tens of thousands of colonists were forced to find homes elsewhere. Some moved to the other Venusian colonies, some became vagrant or joined lawless colonies. 

Today, Habius has less than half the original population, it's essentially lawless, with various autonomous groups vying for power, territory and resources. Demmeuter, with its 10,000 Habiusian emigres regularly stages inteventions, delivery emergency aid and care packages while trying to figure out how to reset the course for their troubled neighbour.

[cols="10%,90%"]
|===
2+|Settlement profile: Hadius

|*Function:*
|Large colony

|*Founded:*
|1st November 2207

|*Alignment:*
|Independent. Ex-Colony of Lone Star Archology (Texas)

|*Ethnicity:*
|Mixed. *Languages:* English/Spanish/German

|*Type:*
|Surface Modules

|*Tech-level:*
|Old-standard

|*Class:*
|Durable.

|*Population:* 
|30,000

|*Government Type*
|Balkanized

|*Law Level*
| Lax

|*Attitude:*
|Open

|*Social Type*
|None
|===




==== Demmeuter USP: AC


Joint German-Italian colony, situated on the northern pole. The main settlement is housed in a manmade underground lake of specially engineered dielectric fluids, most of the colony structure takes the form of a cluster of giant submarines. Demmeuter was designed and engineered by the Berlin Archology during the 2200 Expansion project. Initially a small 20-person habitat was constructed as part of a feasibility study. While the proof of concept worked, it was clear that such a difficult and technically complex colony would be far too expensive to scale up for millions of colonists, at least when compared with the orbitals. However, the government was willing to press ahead with a medium sized colony providing it could share the cost with another archology. Initially France was considering the partnership but the Lyon Archology's colonial administration got cold feet, so the a partnership was instead forged with the Turin-Milan Metroplex Archology. Demmeuter has a successful manufacturing sector that specialises in building heat and pressure resistant appliances and robotics, leading techologies developed out of necessity for those living in the hell-heat of Venus.

[cols="10%,90%"]
|===
2+|Settlement profile: Demmeuter

|*Function:*
|Large colony

|*Founded:*
|1st November 2212

|*Alignment:*
|Joint German/Italian Colony

|*Ethnicity:*
|Mixed. *Languages:* German,Italian, French and English

|*Type:*
|Caven

|*Tech-level:*
|Old-standard

|*Class:*
|Durable. Even deep underground the temperature of the rock 

|*Population:* 
|75,000, 50,000 Germans, 24,000 Italian, 1000 French

|*Government Type*
|Colony/occupational government

|*Law Level*
| Restrictive (Prohibitive for laws concerning settlement safety)

|*Attitude:*
|Open with visa

|*Social Type*
|Centrist
|===


==== Mirabai

*Population:* 50,000 +
Mirabai is named after the 16th-century Hindu mystic poet and devotee of Krishna. Like Demmeuter, Mirabai is a colony, intended to provide living space for young residents of the Gujarati archology. The colony's design is radically different from that of Demmeuter and is intended to be far more viable for population expansion. Instead of submerging the habitat in coolant, Mirabai is constructed using huge vacuum flask-like structures that insulate its underground towers from the surounding heat. Internally, Mirabai is built to be as close to Gujarati Archology architecture as possible, which was part of the strategy for persuading people to relocate here.

Since its initial settlement drive, growth of the colony has greatly slowed. 

[cols="10%,90%"]
|===
2+|Settlement profile: Mirabai 

|*Function:*
|Large colony

|*Founded:*
|1st November 2270

|*Alignment:*
|Colony of the Gujarati Archology

|*Ethnicity:*
|Indian. Gujarati, Hindi, English

|*Type:*
|Caven

|*Tech-level:*
|Cutting-edge

|*Class:*
|Durable 

|*Population:* 
|40,000 Gujarati/10,000 Mixed

|*Government Type*
|Colony/occupational government

|*Law Level*
| Prohibitive

|*Attitude:*
|Open

|*Social Type*
|Centrist
|===


=== Earth

image:https://db3pap001files.storage.live.com/y4mXKWsSvSC82ILeraxpa5VA29HZxhNc2c1ykwld0LT4b97dRuoJPwp2bb6Qkl5NSVTFLG58vTEOcIB8Lvza_i6n9MW17QoKh-BLEXD1W6LchAN_S5jTBGPqTH-Faf2y4JculfVneyqgUhIKk9KZFc9mS0vDgVMVgFW4sYolAAXvBu2iHKfI5wLms8MDF9vFoWo?width=1024&height=480&cropmode=none[Earth Header]

|=======================
2+| **Earth**      
|*Diameter:*   |12,700 km
|*Mass:*      |1 Earths 
|*Gravity:*    |1     
|*Escape velocity:* | 11.2km/s
|*Atmospheric pressure:* |1
|*Surface temperature:*| +15
|*Surface radiation:*|1 SDU (1 microSevert per day)
|*Solar Day:* 24 hours
|*Year:* 365 days
|*Distance from Sun:* 1
|=======================


image:https://db3pap001files.storage.live.com/y4mVH80D8qYEGpGJt9tiTHyTisxxqr4TmW5wqnBHROA6J91TErF0t0pPFgqfooEZMqPeNcgy6kFBqmvOfoh5SiHyXkvnnIkHK4Og_ySld9unJl5SDMZNVkxPJIjZiO3tU5DA21Pxf_tAUMeFzj85s1BxSZXop6Ba6ISu_b4i-x1QqOfaMGYtAlrSBsuE1xG1NLR?width=1024&height=795&cropmode=none[image of the world]


==== Continents

Looking closely at the world map, it can be seen that a runaway ice-melt has rewritten the shape of the continents, a movement that had profound implications when you consider that most people like near coastlines. What's not obvious is the ecological collapse. In 2050 there as a global effort to plant a billion new trees per year. By 2055 the majority of the new trees had died in forest fires. The painful truth was that the lost forests would not grow back. There would be no easy answers in dealing with a rapidly dying world.

*Unstoppable flooding*

Year-on-year calamitous flooding impacted every nation on Earth with a coastline. For Bangladesh and many of the world's island nations, these flooding events where the end of their nations as they passed the way of Doggerland, the land bridge that once connected England with the Netherlands which seamingly sunk into the North Sea eight thousand years ago.

Asia suffered massive upheavel as its nations buckled under the impossible effort of relocating a billion people. By the signing of the  Arctowski Treaty and the start of the Global Restoration Initiative, most nations were entering a long awaited era of recovery. While most of the remaining nations had restore basic standards of living, all the growth coming out of the increased automation and AI was going into the funding of humanity's expansion into space.

America lost its entire Atlantic seaboard, which slowly vanished between 2040 and 2140, including the entire state of Florida. However populations moved long before the loss of land became perminent. When devasting floods came every year, the government stopped trying to hold the waters back, instead moving to massive relocation projects. The Archology projects came out of a joing American-Japanese research program, aimed at balancing the relocation of hundreds of millions of people with the need to minimise heat and CO2 output. The project was heralded as a huge success and was quickly emulated by Asia's high population nations.

*Archologies* 

More than ninety percent of Earth's inhabitants live in fewer than 100 archologies. The near colapse of Earth's biosphere, along with the constant hurricanes generated by the heat-wrecked atmosphere forced humanity to huddle in cramp, highly vertical city-structures. Anyone not living in an archology is living in so-called Bunker communities, these are networks of underground habitats. Compared to the archologies, these are much smaller with fewer facilities, inhabited by those who valued space and freedom over convenience. Tiny number of people live outside of these two types of habitation. Living "off the grid" means a constant battle for survival, facing savage weather, living off sterilized soil and poisoned water. However, even after hundreds of years, there is money to be made exploring the ruins of the old cities, just don't go unarmed. Things can get wild out there.

There are broadly three types of archology:

**Dome clusters**, where existing cities where covered in vast domes, supported by tower pillars. These are more sprawling, covering larger land areas and being somewhat less developed then the purpose built structures. 

**Tower Structures**, Single or multiple tower structures, these massive buildings incorporate everything required to sustain the inhabitants, automated manufacturing plants supply most manufactured goods, automated farms create the food. Power is supplied from a combination of renewables, fusion power and orbital solar provide energy. 

**Deep Wells**, Some Archologies were dug downwards, creating cavernous habitats that support artificially sustained forrests, lit by huge sunlamps. An approach to living space that was imported from the extra-terrestrial colonies.

Life in the archologies is reasonably comfortable and safe, but for most inhabitants, day-to-day living is highly regulated, with limits on personal freedom. Employment rates are below 25%, leaving the majority of people to occupy themselves through leisure, hobbies or self employment producing artifacts.

Most archologies are extremely insular. Built to be completely self-sufficient, and following very similar plans, so life in one archology is pretty much the same as another. The exceptions are the archologies at the base of the two space elevators, Cayambe in Equador and Mame no ki, an artificial island off the coast of Indonesia funded mostly by Japan.

Raising families remains popular, although most archologies limit family sizes to keep population growth under control. Couples wanting more than two children are encouraged to emigrate to a colony/habitat. 

By the 2280s most archologies have become rundown. While automated systems continue to repair essential infrastructure, the massive scale of these structures make the task of renovation or replacement extremely difficult. Most archologies have shifted to space emigration to handle population pressure. 

=== Low Earth Orbit

There are hundreds of small to medium sized stations in low Earth orbit. Larger stations are not built there because of the need to occasionally adjust orbits would be difficult. Larger stations are built at the Lagrange points, where orbits are stable.

=== Gateway stations

Located about half way up Earth's two space elevators are the Gateway stations. Built as transport hubs for the passengers and cargo that travel up and down the elevator, they quickly expanded to include hotels and entertainment, then habitats for the growing number of perminment workers. Each station is an independent "free city" with no political or cultural connection to the country located far below it. 

=== Lagrange Points

There are five points around the Earth-Luna system where objects can benefit from a stable orbit. Outside of these zones occasional orbital corrections are required, which is difficult and expensive for moderate space stations, never mind the multi-million-ton Orbital colonies. For this reason, large space facilities are located at the Lagrange points. The first, L1 is located near Luna and orbits Earth at the same rate as Luna. L2 is located on Luna's orbital track, but on the oposite side of the Earth. L3 and L4 are located on Luna's oribital track, F3 just behind Luna and L4 just ahead.  

==== L1

*Edgeware* +

*Martel* +

====  L2

==== L3

=== Luna

image:https://db3pap001files.storage.live.com/y4mIyqf2rVrPc0HCNc6hsvE_a7Ty9_ZTzXJdH-5tpwo2zfUV-hgZW5Egu9bxhMNq_JCR6icjcbrtQaZSjgdY1WDDUpfWOsZV0cej3MMwpmfDOSQPj-hJgQVFKKmGXmZAtj21xmVQ1XJlXszHK2ZPokwwNVTqseu4ATj22leNs16RSAWelCwcmbrFWBUxxH8XWEE?width=1024&height=480&cropmode=none[image]

|=======================
2+| **Luna**      
|*Diameter:*   |3476 km
|*Mass:*      |0.012 Earths 
|*Gravity:*   |0.165g     
|*Escape velocity:* | 2.38km/s
|*Atmospheric pressure:* |1
|*Surface temperature:*| +124/-173
|*Surface radiation:*|10 SDU
|*Solar Day:* 29.3 hours
|*Year:* 365 days
|*Distance from Sun:* 1
|=======================

The Earth's moon, now commonly called Luna, given that people are living on dozens of moons, is one of the most developed and populous places in the solar system. It was the location of the first perminent space settlement, it then because the main industrial hub for both space development and metal resources for Earth. Over the last two centuries six large settlements have grown to become nations in their own right. This development didn't run smoothly, Luna was the first readily available source of Helium-3, the crucial ingrediant for low-neutron-emission Fusion. Helium-3 was seen as stategically vital resouce -- if you had it, you had a foothold in the future, if you didn't, your nation would be left behind. In the early days, Luna saw nations scuffle over mining rights, then full-blown conflicts.

Mining saw the construction of hundreds of small  temporarly settlements, build quickly and with not much care. The infamous Jobesville massacre occured when the desperate inhabitats of one such settlement suffered life support failure, a band of engineers lead of Tommy Logan travelled to the neighbouring Jobesvill to persaude the occupants to provide technical assistance and parts. The occupants of Jobesville refused to help as their own settlement's infrastructure was close to collapse. The resulting tussle turned bloody, resulting on Jobesville's destruction and the death of its entire population. It was seen as the darkest day in human space colonisation, the larger colonies tried to introduce a legal framework to ensure that future conflicts could be avoided, but nothing could be agreed. There was an on-going cold war among the Luna colonies and no colony wanted to be constrained from "defending" its own rights.

Outside of the protected borders of each colony, Luna is a no man's land of deserted mining settlements and surviving failed-state settlements that breed piracy and cover the activities of the big criminal organizations.

**Apollo City** US Luna hub city, located 

**Chang-Er** Chinese Luna settlement, less developed than Appollo but spread over a larger area, located in the southern pole.  

**Tsiolkovskygrad** Russian industry-focused colony 

**Dubois** Jointed European colony, colonised by all European archologies.

**Azania** Colonised by the African Federation

**Tsukuyomii** Japanese colony

==== Other settlements

There are hundreds of smaller settlments dotted ado

==== Orbitals (Lagrange Points)

The following colonies are massive structures, or captured asteroids built at the Lagrange to house colonists from Earth's archologies. Most are now over 100 years old.



=== Mars

image:https://db3pap001files.storage.live.com/y4msK-xtuAOedDcgosE57w_YQ4tpe87VYrly4cSQsNnEC1lZuC55BKkiO1SLHsDYXps80Lkp1o_gSVlT20EbsyXSuLsvWimC9r1TV6dA5WUg0zf4JXW-mZVg8urVI5bJGNHcSpFIM24yyzzoCIs-Q9QaBB8ioPTTMVUkJKdFqbOKQOFVMQlgUczJfdW_342IOQz?width=1024&height=480&cropmode=none[image]


|=======================
2+| **Mars**      
|*Diameter:*   |6,779km
|*Mass:*      |0.1 Earths 
|*Gravity:*    |0.3    
|*Escape velocity:* | 5 km/s
|*Atmospheric pressure:* |0.006
|*Surface temperature:*| -143/+35
|*Surface radiation:*|30 SDU
|*Solar Day:* 24.5 hours
|*Year:* 687 days
|*Distance from Sun:* 1.66 AU
|=======================


==== Phobos

image:https://db3pap001files.storage.live.com/y4mt8-96g06h6RKW1xz25JN0cBdK2oT8s4pPdoLTl5KexY2-BeHtpAwxcoB3zNo3jNpIzYEX-ajNXE0TxPM8IpaCNOo_yr9zfSq9KU6wq37y4QpBibEh6-xAX3qzLG6KxTaiL5hyP-MU1ggAJ4Xd3nOrDhEQKjNJc6dAfmHb0bGVD9NYjs8DmA-W95axUF3PXo3?width=1024&height=480&cropmode=none[image]

|=======================
2+| **Phobos**      
|*Diameter:*   |11.19km
|*Mass:*      |Negligable
|*Gravity:*    | 0.5mm/second 
|*Escape velocity:* | 41km/h
|*Atmospheric pressure:* |0
|*Surface temperature:*| -112/-4
|*Surface radiation:*|30 SDU
|*Day:* 24.5 hours
|*Year:* 8 hours
|*Distance from Sun:* 1.66 AU
|=======================

Named after the son of Ares (Mars, by the Romans), Phobos is the larger of the two martian moons and is believed to formed out of a debris ring that was created when Mars had a run in with a small planetoid. In time, the ring of space rubble coalesced into the bumpy ball of rock and ice that we see today. Initially ignored by the first generation of settlers, Phobos was later mined for water and volatiles. Some of the early mining facilties expanded to become an easy orbital resting point, given that a well kicked football can escape the moon's miniscule gravity well.  

*Ground Settlements* +

*Limtoc City* +
A free city, that acts as a transport and trade hub for goods that move between the Martian settlements and elsewhere in the system. Limtoc City is built into the deep Limtoc crater which is itself located within the massive Strickney crater. The main habitat is a rotating ring, that spins on a giant axial that runs deep into the moon's core and connects to hundreds of mining tunnels.

image:https://db3pap001files.storage.live.com/y4mBLjsbF2HThmPyiWd_NRr46PYcZGx1kZPVW7FPvHS8-Rlh_C9amTy_fc51A8wPwmobYnss6EyvkLlNhd0-UT5SAcrvWpIoXEgN8cytlHjZsOOhOiFJmpBGCxdQ5nslLRzxMvxFXmBosBlFcKluD8DJ3sSg51r8y8F6UiILHXVrgXiLgiypmXeecsn0-D1To1w?width=1024&height=576&cropmode=none[image]



==== Deimos

|=======================
2+| **Deimos**      
|*Diameter:*   |12.4 km
|*Mass:*      |Negligable   
|*Gravity:*    |Negligable      
|*Escape velocity:* | 20km/h
|*Atmospheric pressure:* |0 (vacuum)
|*Surface temperature:*|-40
|*Surface radiation:*|7 SDU
|*Day:* 30 hours 
|*Year:* 30 hours (synchronous)
|*Distance from Sun:* 1.66 AU
|=======================

image:https://db3pap001files.storage.live.com/y4mTr2himi63sBjKkNwWT_n-w9qJpMIP3HFtm5xrYrAdldPWmJIHoar7x4mfLqgeIbgl5X25iTp9fR78zm0KXtyqRpZZtc9v8zwSq3nR9pheFO3f73u44_UkDPOG3cSXB9KUy8-uWoyCwDr2hzhdqNkfTs30JvwmctImfrRAqTUtXvEBtBcGuTEdyxnPCUk03If?width=1024&height=480&cropmode=none[image]

=== The Belt

==== Ceres

|=======================
2+| **Ceres**      
|*Diameter:*   |939 km
|*Mass:*      |0.00016 Earths  
|*Gravity:*    |0.029 g     
|*Escape velocity:* | 0.51 km/h
|*Atmospheric pressure:* |0 (vacuum)
|*Surface temperature:*|-163.15/-38
|*Surface radiation:*|7 SDU
|*Day:* 9 hours
|*Year:* 4.61 (synchronous)
|*Distance from Sun:* 2.9 AU
|=======================

image:https://db3pap001files.storage.live.com/y4mvDsp-vylXGhTbNg98GojjJ3oD7xYIXke2ZrRl0ExiJcGYH6vzDXP8gPeVw4E5S95_T4XjjD42nnsjg1fYX1w99SnSKXbYw4tTfHF92O5TotzfkgfB_81D68XOgWmEIBx9MHctoyMO9qO8dCicPx6QjtvUbl5hVGfJkHTm6arrtL-TcusTAcgT3vDfGnrMkfP?width=1024&height=480&cropmode=none[image]

==== Pallas

==== Vesta

==== Hygiea

==== Domus



=== Jupiter

image:https://db3pap001files.storage.live.com/y4mi6iRnveOw0vVqffYJ3oxwrGAGn4L7rJR86Qn2Tdck2UgcO5VA83TJjERc96nSvEtSI0uUOlB7u_XFnixj7hvvCzA8viLELEqQwZrON5BF_tWtCdu5YhmKDumd1tBfFsnNvWiR9DEXeAQtoY0C_GCBktvPCIC8alkp3Qk2IFz83x1Yx729H45CDNoOuRZckTo?width=1024&height=480&cropmode=none[image]

==== Io

image:https://db3pap001files.storage.live.com/y4msdH6Hsedvb5lVsOchZCXkcpYX87xmuF_L-X3nyuG3hQ2icEPUMqwuTrWBCUVSnm0pKkDaJpg8RhjnNAiFlYJzLTyfcDj1MdZ78dND9PLugn7M_pW0d1k6IukDqBwiBpOVUV_xqhbzqIA0KEW4XkD5R3A-4JuUNcOoRwgcxmi7f3HEcYVQrbRNPC4_PC4uheo?width=1024&height=480&cropmode=none[image]

==== Europa

image:https://db3pap001files.storage.live.com/y4mFNU-0-bDCBNfDkfSNqPMKdgwEHIlnnnp9OEOfONxVOfwPrxrlWw6sYQsZ2fBg6AhPZMXSrrDC2RNQ65YoBiJ43E2WGkGf21uvS1P6sclZEwuTR2xGc0SoyQZ4SH8Y2lumvCoX1NOfmCcXQobnWTUzH0UE25NBYiggKB7wdcZggK48OzHvY3uFZIOzGcGCVz0?width=1024&height=480&cropmode=none[image]

==== Ganymede

image:https://db3pap001files.storage.live.com/y4mAu-iXcjX7xwuAfuo88Yse8pBSqp3ZTVxs6g0b-EIGeSyjXE1yoeWyD9gjgODkmAj-s-E1Yiw4Q2DhqvlNGeK4pdsDte6d8w7fcIstSS9COxrx68vbe-O7u1E_1Dv3yvcm9NEcpASucMcuQuXvg_W_ii4AyXt-Xni0Ar9Z7vVrqVZvIm8ICFFtF9bN4WXPv-P?width=1024&height=480&cropmode=none[image]

Ganymede's surface is exposed to 800 mSv per day. The relocation of people away from Chernobyl was based on the threshold of 350 mSv. You don't walk on the surface of Ganymede, you run into the deepwell underground settlements as quickly as you can. These outpost

==== Callisto

image:https://db3pap001files.storage.live.com/y4m3Asj9otz38Fjj4HCcTUAImY5D8TpXLYBYOugi_SbsGRMdDuvXMHkMrMfx1HuWxAt2BnaC_N208abxkK7b3vapUCiL7xY_Mt77qWT3uHxfBsEZaWcdAxH1fTyo6fKdBaqTVzN8QdiIp7wGLjoyap5T2t6GE9bWFuVoImhe-SW4xuXFMjwLHqulr_sf80GlJzr?width=1024&height=480&cropmode=none[Callisto image]

|=======================
2+| **Callisto**      
|*Diameter:*   |4820 km
|*Mass:*      |0.018 Earths
|*Gravity:*    | 1.2m/s/second (0.1g) 
|*Escape velocity:* | 41km/h
|*Atmospheric pressure:* |Trace
|*Surface temperature:*| -190/-108
|*Surface radiation:*|30 SDU
|*Day:* | 17 days
|*Year:* |17 days
|*Distance from Sun:* | 5.2 AU
|=======================

The second largest of Jupiter's moons. In the early days of colonisation, Callisto was considered the "goldilocks" location for settling. It orbits Jupiter just outside the deadly radiation belts and is far enough away to not fall into Jupiter's steep gravity well, making travel there significantly cheaper. Large amounts of precious metals and some volitiles, mostly the result of eons of asteroid collision made the moon a target for industrialisation.

*Ground Settlements* +

*Lanser Yertan* +
The largest settlement on Callisto (population 10 million), this industrial colony mines and processes a range of materials that are then shipped throughout the outer system. It's central "hub" city is Chǒuxiǎoyā (ChowSowYA), built at the centre of the great Valhalla crater, although there are hundreds of small industrial sites surrounding the settlement's hub. In recent years, the colony has become the target of piracy and industrial espionage. As a result, the settlement's government has taken large security contracts and now fields a sizable defense force. The other settlements on Callisto are deeply unhappy as these security forces continue to disrupt operations and harass shipping in the Jupiter planetary system.

*Jambaree* +
A small settlement located on the edge of the Durinn crater, near the northern pole. Established by northern europeans in 2218, early initiatives such as the development of an extensive fish farm and vat food plant give the settlement a good start for success. Space is cruel; a short run of bad luck and a few bad decisions resulted in both production centres failing to meet necessary production volumes. After the loss of contracts to Lanser Yertan and other smaller settlements, Jambaree has entered a steady decline.  

*Orbital Settlements* +

*Jupiter Gateway* +
Jupiter Gateway is free station, funded and built by the Jupiter Development Conglomerate. Jupiter-gateway (commonly abrevivated to J-gate) is a distribution hub. Heavy transporters, shipping in goods and materials in and out of the Jupiter Planetary system go to Jupiter Gateway. The station is equipped with a specialised robotic distribution platform into which shipping containers are loaded through spoke-like gantries. Once loaded into the storage hangars, the station's AI can then shuffle a hundred thousand tons of cargo like a croupier can shuffle a pack of cards. 

image:https://db3pap001files.storage.live.com/y4m5FPXCxwx-LauIHB3fNGZouUarjwPf7xTaCcqdJV9Yj087uO4ohpdwhFvQmEMB_95Sn8VUVKan4FtGF1JyjQ4aa3HDDiNDIiNkwQwJs0cOZ1OHchIWJLcRCAB6NGjqw1CFi4Ot_DgnmfEszlu8_G2w1te3PtkS0XbX8Bsqu10voHGJnne0VhH4irRAWhvZwBp?width=1024&height=620&cropmode=none[jupiter gateway]


=== Saturn

image:https://db3pap001files.storage.live.com/y4mPsKcOL4yUi3ioZI0Thsjo49BNtYO5oyZ32r0HEq-AeXrYasx-DtwFpPhI7dDjNXwxgzvjAcxWlcB4RXSyC4QmvyZAn3p5o6qZofh4xGOPwsDH2SjejkpKADbYg4MhekHKCWLx-fWpYPsMqWKXvoOguxTp8PIoiTMKu0AYpF1SQmu-At7KvA3PTEv2oe8w443?width=1024&height=480&cropmode=none[Saturn]

==== Pandora

image:https://db3pap001files.storage.live.com/y4mxe04OgyTs34Kbvw0OJSs1OGKwoiugXJcllRmA9kcqoyKrzNkHHtLjIFfL19epy8x5woPlGjgzu3joj7Edzojr-oLzX56ENawjUojsil66dUpof2Dqvwc4hwSToaLnDlfzcBAP92F-_Fmi2e-aALs3m8vngR1x0S_L4Rgfc7p9lqe9yJNbY-DvSaWLoTWYnW2?width=1024&height=480&cropmode=none[Pandora]

==== Janus

image:https://db3pap001files.storage.live.com/y4mZQVYFE060OUanS_tIzNfnNyve0zaVTc4vHJVNZxCyITg3N8SgxlhYx0CmF8-99iOPMMODPyv9i-pXJoB-8kWg5C5sG7qnIug6parjiiAT8WL3YKsTUpmo4D4r5KBjpWJPntJr4oCWgjTNRq6p_4fg40Sld5UNV_gWSwuneoiG1_lufitNzHD_EKpRBe6GF1s?width=1024&height=480&cropmode=none[Janus]

==== Mimas

image:https://db3pap001files.storage.live.com/y4mlh4Fh_jAHHk4Mrl0NFEduBqjBhB4iAx1daRvw6czTU1qfGEbDfUbyxf-QZuQmc_7qa-WpqgIGjLoytnDjgaHbHYcMyDYEnSzosGflP4lj7KGu1gR-Zzzw-opTWF_E0lj8rnYb_BfxRYZEgJRPZuwejx-lBu_gQgVyC4Nh59CHZgtGXOrAte7r1eaIHaMirhX?width=1024&height=480&cropmode=none[Mimas]

==== Enceladus

image:https://db3pap001files.storage.live.com/y4m7lvPzOlQnPDl5RNjeKRFEXNcxE51di2ZZbV0UCIC0dCmRpkMguSR0Y2Y7ieV2seg0zPFn36LCWoTf_L8llqTNyDiRiPG2GIIH2QSfym_JKBuv5sp2nqwgUkUsRgtb_9Y2L-CgxB3oMAENktuJBYQdCxR__q8VIzf42ASwZHJI6DgSi23oVsuW29lbnQcS3_F?width=1024&height=480&cropmode=none[Enceladus]

==== Tethys (trojans: Telesto and Calypso)

image:https://db3pap001files.storage.live.com/y4m0w5fhiMImCH84lBEVQ1fZQNqpProbe8RDjxNusir7rJTcbZfEis_rnnAwppjarGI2JH-zaU7RxIWOJsMkxIq2-u3fENnvDqDqeSVOaQwcrU_JREhhpyaDQsSElrVgsq2kRWWWzDlMxr4Qaid0XooyahYJDtuqgyy5UhbBKXP28-MTQSFD7gnbj9mItGUrDqr?width=1024&height=480&cropmode=none[Tethys]

==== Dione (trojans: Helene and Polydeuces)

image:https://db3pap001files.storage.live.com/y4mOnErCD1jr94pygesVM61Jd0XMtYn5rB-nl-hXKN_dCiRBEbUYeSfCvYKc_yduHFNPm62HA37WfflKYEWWngrvVuNXw5F0KHUyb06_p7xGZnC-ueydOq8Qe14Qw_wAfbCgMzBr-JOcvZ3ar4AGNEhEETrBl71W0xhGud-96lu4mjHVj7thXmsig6j-zfpZEIy?width=1024&height=480&cropmode=none[Dione]

==== Rhea

image:https://db3pap001files.storage.live.com/y4mU7cevU1WSK_0-m7BIRSKiXkMalBxbspLPabcd-grWgDONia-eXLxx3Jm-I7QJOXqXpms_xWC8Y6WBc5KH5iMPv_rwUnb3vt3I__UZEi6gM3rpGBlUsvqT2u83MfheCD7kgpFGdu69zaSmQgyMfHkO0HP83u81thLO_-jILWlyogymKGfpUHvnB9QieDLin4m?width=1024&height=480&cropmode=none[Rhea]

==== Titan

image:https://db3pap001files.storage.live.com/y4momMP2JHQs6a-xg0VNv09W5ZjWcNGs6hUz_FRqCcL22Dq1ULURp_pmUyB0pvcyoyhWOmxZ3i4Azk8OXvIlGk6fjCUmprqGib6bc-aLrlrsxD8hdNbkbvqzhja0WrbHPm9XP1nEJ1bYFOVik9AW2xmIb8aTv2jpL2joSogKNOhK4f6MfidAcMhDgmRRN0Z1Big?width=1024&height=480&cropmode=none[Titan]

==== Hyperion

==== Iapetus

==== Phoebe

=== Uranus

==== Miranda

==== Ariel

==== Umbriel

==== Titania

==== Oberon

=== Neptune

==== Rings of Neptune

==== Proteus

==== Triton

==== Nereid


