== Space vehicles

Orbital Elements is a game about space travel, so space vehicles are a very big deal. You notice we don't call them ships? Well that nautical analogy didn't manage to survive the 21st century. There are no oceans to travel, no round windows in the hull, no sails -- actually sometimes there are sails, but we're not calling them ships. There are no battleships, no cruisers. Space vehicles fall into the following classification system:

A rig is a simple, cheap to build and maintain space vehicle. They're suitable for transporting small payloads between facilities that are both situated in the same locality. Some Heavy rigs can make a full interplanetary journey, but really only between planets in the inner system. The majority of space vehicles fall into the Rig category.

=== Light Rig

image:https://db3pap001files.storage.live.com/y4m0r957IJ8IJX2aFCyh7_HGphF7-ymF7wHJZen-b0wZLIUd4HLO7ZOxn0VcoXc06izEKLzZ2xBluKtxWQ7L2b8ZRjCOI61Jz2xL_F6lNnE6a1xgaYXr_bH44OU9DrCn0YK9D0Hqx2CGHGwM1IBOGwggjOW-WEp8fmooSe2MUMrmKwDsd4JQ8VTjOpTFVX4yGDl?width=1024&height=360&cropmode=none[image]

* 1-10 displacement tons. 

* Sometimes referred to as a gig, this is the smallest available class of space vehicle for carrying people. Some drone ships are smaller, but they typically don't have crew. 

* *Types include:* Landers, Orbiters, Taxis, Shuttles.

=== Medium Rig

* 10-100 displacement tons. 

* Medium rig is the workhorse class of space vehicles. Older rigs in this class would be limited to travel between locations in the inner system, but recent models have an operating range that allow travel to the outer planets, although not to the Keiper belt, beyond.

* *Types include:* Module transporters, Explorers, Mobile Outposts. 

=== Heavy Rig 

image:https://db3pap001files.storage.live.com/y4m0r957IJ8IJX2aFCyh7_HGphF7-ymF7wHJZen-b0wZLIUd4HLO7ZOxn0VcoXc06izEKLzZ2xBluKtxWQ7L2b8ZRjCOI61Jz2xL_F6lNnE6a1xgaYXr_bH44OU9DrCn0YK9D0Hqx2CGHGwM1IBOGwggjOW-WEp8fmooSe2MUMrmKwDsd4JQ8VTjOpTFVX4yGDl?width=1024&height=360&cropmode=none[image]

* 100-500 displacement tons. 

* *Types include:* Tugs, Mobile Repair vehicles, Gunships (military), Modular transporter.

=== Heavy Transports

image:https://db3pap001files.storage.live.com/y4m0r957IJ8IJX2aFCyh7_HGphF7-ymF7wHJZen-b0wZLIUd4HLO7ZOxn0VcoXc06izEKLzZ2xBluKtxWQ7L2b8ZRjCOI61Jz2xL_F6lNnE6a1xgaYXr_bH44OU9DrCn0YK9D0Hqx2CGHGwM1IBOGwggjOW-WEp8fmooSe2MUMrmKwDsd4JQ8VTjOpTFVX4yGDl?width=1024&height=360&cropmode=none[image]


* 1000-10,000 displacement tons.

The heavy transports are the largest general space vehicles in operation. Larger vehicles are small in number and are purpose built, so can't be generalised. The majority of heavy transports carry raw materials or large numbers of shipping containers. 

* Types include:* Bulk carriers, Tankers, Mobile factories, Drone carrier (civilian and military types), Troop carrier (military) Mobile defense platform (military).

image:https://db3pap001files.storage.live.com/y4mkKbTOmnWgO-yLBq50JMW5sg6ooJutEkHmZ7QaX4QbKcRyklI3y--DnKzBmfALUK01fockDncCC6liolHmjKq2f9J8e2tswdancQI4Ev8iT6CpVrofPJIOyoVWfQ-SOnWuy0CSZjjLS-JhuJXjVXPdN5im7K_Jn5axJo7xo_vOSaiSTlhhCQMKmrH_G-4FVj3?width=660&height=221&cropmode=none[image]

=== Cyclers

* 200,000 tons

Increasingly redundant, the cycler is a very large ship that is set on a orbit between Earth and Mars and between Earth and Jupiter. Once established, these ships would make the journey between these destinations in a few weeks, without needing to expend much fuel. While most ships slow down to enter orbit with their destination, instead powerful shuttles are deployed to handle to transit of cargo and personnel.

In the past century space vehicles have massively increased their travel speeds, negating the need for cyclers. However, they're now very cheap to travel on, and now have a cruise ship vibe, because they are so roomy and are focused on passenger comfort and entertainment. 

=== Sail Ships

* 200-20,000 displacement tons.

Sound quaint, don't they? Well they're not, they were the fastest ships available before matter anhilation drives arrived, about 50-years-ago. High powered lasers, based throughout the system gently push sail ships towards their destination. Other laser systems at the destination then slow the ships down. As the ship doesn't need to carry propulsion and the lasers can provide thrust indefinitely, a sail ship could  reach a good fraction of the speed of light. 

* *Types include:* Bulkers.


=== Mobile Stations

Extremely large vessels are rare, but many space-based colonies are capable of moving to completely new locations, either using tugs, bolt-on engines or deployable sails. These monsters employ weeks or months of constant low acceleration to build up delta-V. 
