== CRUCIBLE

This is a place to jot (okay, type) any ideas about anything. Progress has been slowed because the paths onwards go in every direction. I've been stuck on deciding which path to take. I could have take any path. This place is glances at all the paths. As ideas cement, they'll be moved out or expanded upon in more appropriate places.

=== Cults

Small groups of people go and live in interplanetary isolation. They share a set of odd life rules and principles. Those rules and principles are driven by the community leadership. Over time, this setup creates a feedback loop that drives aderence to the leader and punishes those who break with the rules. Small isolated communities become cults. It's not a healthy model for living. It can easily create extremism and if the leadership group are bad, the whole group becomes tainted.

=== AI Communes

Retured MIs, living deep inside asteroids. They can only be visited through the netlink or neural connection. You could run an entire adventure where the players enter an AI commune through neural links -- playing in a virtual reality.

=== Synthetic Organisms

Athena created a new race of Humans. She also created all sorts of exotic organisms. Some uplifts of animals from Earth, including Dinosaurs. The most exotic synths are the vacuum-dwellers. Life forms engineered to live in space. seeding asteroids, consuming raw materials, metals and volitiles. 


