== Introduction

.Extract from  "How I'd describe life in 2277 to my ancestors" by Benji Reesman
=====
What a time to be alive! Or, if you're a sentient machine, not alive, technically. It's 2288AD, there's good news and bad. If you thought we'd fix the climate, add that one to the bad news list. Earth is a hot mess. Burning deserts stretch across half the remaining landmass. Hurricane season is every season and almost everywhere. The biosphere hangs on by a thread. Hey, we stopped things getting worse - everyone moved into giant archologies that trap the heat they create underground. When the archologies got full, we started to move people to the space colonies. Now, we're everywhere. Which is quite good. Kicking-up Helium-3-rich rust on Mercury, floating above the Sulphuric-acid-rich clouds of Venus, we're big on Mars, and all the way out to the Keipers. 

First it was all about getting our hands on Helium-3 for Fusion and raw materials for making stuff. These days, the energy people are starting to use matter-anti-matter annilhation, mostly for giving our space ships some serious horsepower.

We made those sentient machines - pretty good. We programmed them to like us, which meant that they wouldn't hurt us, or at least they'd really well up if they accidentally did. There were some accidents, and some people who never liked the idea of thinking machines started to turn against them. There were terrorist bombings, After a while some of those machines made their own thinking machines, optimized to protect their own kind. These AI Guardians were not programmed to like us, they weren't so good. We had a giant scrap about that, two scraps, in fact. Lots of people died, some machines died to - I guess maybe they are alive then.  

After the first AI war, the leader of the machines sneaked into the Oort cloud and started to create her own humans. In a crazy twist, she programmed these new humans to love AI. The people who didn't like thinking machines, well some of them really didn't like the new humans either. It got really messy. You might think that the AI wars were fought between humans and AI. If you thought that you'd be sweet-summer-child wrong. The wars were fought between Human nations that embraced or accepted AI and those that rejected them. Most of the friendly AI, we call them "Bound AI" remained neutral or worked to end the war, while their guardian AIs sort of had a plan to cull natural humans and replacement them with their 2.0 version. The last big spat ended with the AI leader, Athena changing sides to join the humans after her "destroy-all-humans" protocol got activated by mistake. Apparently the neutral AI managed to block Athena's network, which triggered the activation of two really nasty AIs, Kali and Anubis. Athena and a human fleet managed to destroy Kali in a big space battle above IO. Anubis escaped and we think is hiding somewhere. Athena agreed to go into exile so long as her humans were allowed mingle with natural humans. Most human nations agreed, those that didn't are still making trouble, but Athena kept her word and turned herself into a starship. She jetted off into deep space 50 years ago.

Since then, there's been an uneasy peace. Everyone thinks Anubis is out there, waiting to start another war, which keep the pro-AI and anti-AI nations at logger heads. There hasn't been another big war, but there are lots of little conflicts going on.
====

=== 10,000 Nations

Back when space colonies were brand new, setting one up took a pretty big chunck on money. You had banks and governments, system architects and technical specialists. Everything was underpined by human expertise, and an Olympus Mons mountain of regulations. Eventually, when everything was running smooth with a bow on top, regular folks started to arrive. Thing is, by the start of the 22nd century, AI and automation meant that you could buy an AMP, sort of a giant robot factory and it would do absolutely everything. Literally land the thing on some patch of moon and tell it to "Bake me a settlement". As there was increasing pressure to move people out of the crumbling archologies, the regulations got watered down. Suddenly you only needed a bunch of people and a tiny crowd fund to set yourself up as a new colony. This was a revolution! Hundreds, then thousands of small groups, all wanting to set up their own outer space utopia. And, well, if the egg-head army with unlimited funds couldn't build utopias, it wasn't too surprising that fringe religious groups, goth communes and other retro-culturists never quite nailed it, either.

A few small settlements found a niche and became really successfully. They turn into big settlements, then into fully-fledged nations, with a unique collective identity and their own money-making shtick. However, most small settlments are forever hanging on by their collective fingernails -- a situation that breeds desperation. Some settlements just starve and fade away, quite a few literally fight to survive, by which I mean they get armed and go out and use guns to persaude people to hand over stuff that they need. Oftentimes people don't give up what they have and blood gets spilt. Yeah, bloodthirsty pirates in the 23rd century, life imitating art, well not art, maybe pulp science fiction.


=== Keeping humans in the loop

After the first AI war people came up with some regulations to keep AI under close watch. Those robot factories, the AMPs, suddenly needed a human oversight team and spot checks. There were serious concerns that AIs could be building more evil AIs or Antimatter production equipment, weapons of mass destruction. This turned out to be a good thing because it gave lots of bored people important jobs. Instead of watching VRs all day, these people would spend their days reviewing manifests, walking around warehouses taking readings - all that interesting stuff.

=== Economics

About those Autonomous Manufacturing Plants, you known, the giant robot factories. They make almost everything. Clothes, gadgets, vehicles, even space craft. There are no workers to pay, but running costs are high, so all those manufactured artifacts are sold, not given away. The money made from sales go into covering operating costs while a portion of the profit goes into a central pot that funds a universal income scheme. People can live a confortable life from universal income, but most people seek to increase their wealth by taking on some form of work. In 2288 there are still rich people and poor people. Being poor usually is because you were born on a failing independent settlement, or someone decided you would live out from under the yoke of a controlling government. Pure wealth is not the only factor to consider, citizens living in the archologies, about 90% of humanity, live in a nice but cramped appartment. They have access to healthcare, entertainment, parks and recreation. Living is easy, but, for a lot of people tedious. When the old world shifted from the old capitalist system to the current model, a lot of people decided to fill their endless free time with raising families -- big families! Having four children become very common. In the early years population growth wasn't a major issue, but there soon reached a point where whole new archologies would be required. The problem was that the exising archologies where a special one-time global initiative that took massive industrial effort. AMPs could create new settlements, but an archology isn't just a series of interconnected settlements -- they require titanic engineering effort, the type of effort that creates polution and and heat. At that point, it was just cheaper and easier to ship the expanding populations out to the colonies. Seems odd, I know. Even with Earth's burnt-to-crisp biosphere and stormy climate, you can walk outside without your blood boiling. While it's always going to be cheaper and easier to build habitats on Earth, the powers that be decided that they would not allow Earth's population to grow. If anything, they want to depopulate the planet. 
