

image:https://dub01pap003files.storage.live.com/y4mrzpdOZBJErW6feztYtcYgcLwb_ZO-Wy83H3uVUmmpmA4g_YLwVGWLPFf_PIPbHPmXC7zP3XO2QLUeHuKMIiXHY-BaQgHJlTkf5wzVaqh8cJkwA8w_BJgnNwBb9qnbqVu3AG17OpHJaXjvMj_KbGoSseFoL3KC5TSnumr36Z5LbrB_Uq_L2WZI6XqSdnx8Zvg?width=1024&height=505&cropmode=none[Cover]


[quote]
 Giant steps are what you take +
 Walking on the moon +
 I hope my leg don't break +
 Walking on the moon +
 We could walk forever +
 Walking on the moon +
 We could be together +
 Walking on, walking on the moon +
 - 20th Century Police Mantra


== Introduction

A one-shot adventure for Orbital Elements Science Fiction Role-Playing Game.

*Setting:*  Mare Imbrium (Sea of Rain) basin. 

*Solarpedia Extract:* Mare Imbrium is a vast lava plain within the Imbrium crator basin, near Luna's northern polar region. It was the site of early Helium-3 mining regions, and one of the most contested. During the Luna war II the region became criss-crossed by a defensive lines, creating pockets of "no man's land", filled with smart mines, hidden missile launchers and killer drones. Today these areas are avoided, except by scavengers and pirates.


== Synopsis

In this one-shot adventure, the PCs are the crew of a small transport rig that carries passengers and cargo between the countless Luna settlements. The adventure begins part way through a journey from Nuvo Sputnika to Copernicus Arc. The transport is hit by a ground-based weapon, forcing a crash landing, right in the middle of a no man's land region that is littered with automated weapon systems left over from the second Luna War. The place is covered in smart jammers that make radio communication from the ground all but impossible, so there's no way to call for help. The PCs must try to lead their passengers to safety, walking across a trackless waste, filled with unseen dangers.

However, there's more going on...

=== What's going on?

One of the passengers, a mysterious middle-aged man called Jack Deringer told the PCs that he is carrying very sensitive research data. He fears that hostiles may try to intercept him during the journey. He offers to pay ten times his fare to fly to Copernicus "below the radar" and with their IFF beacon turned off. The PCs happily accepted because flying low, slow and quiet is safer. However, all is not what it seems. Jack Deringer's real name is Percy Brennan. He isn't an agent carrying secret research data, he's a retired farmer who now lives out the fantasy of being a secret agent. Locked in his secure case are some snacks, a couple of adventure sims and emergency toiletries.

At Nuvo Sputnika, Percy approached several transport services, specifically asking if they could provide an off-the-grid transit. This request was overheard by Sam Modey, a pirate working at Nuvo Sputnika's port who looks for high value targets for ambush. She assumes that Percy is carrying something of very high value, of such high value that she not only did she target Percy for ambush, she is risking travelling on the transporter herself, signing up as a passenger using a stolen identify (Zena Platts). Shortly after leaving Nuvo Sputnika, Sam activated a beacon in her dufflebag, sending the transport's position to her a pirate team. The beacon allows the pirates to quickly travel to one of several hidden weapon systems along the PC's route. When the PC's transport flies close, it is shot twice by a railgun emplacement. The shots are carefully targetted, so that the transporter is forced to make a hard landing, but is not so badly damaged that the transporter can't make a survivable landing. 

=== Journey facts

While it's possible to do the journey using a "hopper" that actually launches into space then comes back down anywhere on the moon in less than 20-minutes, it's super expensive to get the transit permits. Luna orbit is now a crowded place, and there are restructions due to the two space elevators that create exclusion zones on the equator. The journey of about 1000km is a little longer than normal for a small rig, but the rig will complete the journey in about 5-hours, cruising at 250 Kph, about 1000m above the surface.

The subject of the scenario is how the player characters deal with the crash and the dangers of finding a place to shelter. The pirate angle becomes apparent when, on finding a missing launch facility they identify that someone has put a beacon on their rig. Almost certainly one of the passengers as it would need to be activated some time after leaving polar traffic control.

The adventure is broken down into the following episodes:

=== Episode One: Moon crash

The PCs are introduced to their current situation. They don't get much time to prepare before their vehicle is hit by a small missile. Their rig immediately goes down. The PC piloting the vehicle gets to roll for how severe the crash is, and where exactly they land. On landing, it's clear that their vehicle is wrecked, and in danger of being shot at by any number of autonomous drones or hidden launchers. The PCs must decide how long they risk stripping equipment from the vehicle before a likely strike arrives. Eventually another missile is launched, resulting in the crashed vehicle being peppered by a cloud of penetrators. Potentially lethal for anyone still in the vehicle. 

The episode ends with the PCs deciding on a course of action. They might wait near the vehicle - not a good idea. They might head out and try to find some kind of refuge from where they can wait out until a search party arrives. Normally a personal communicator works fine, but the no mans land regions are usually covered by heavy jamming and interference. 

* *Player handout 1:* Shuttle manifest
* *Player handout 2:* Shuttle sheet (inc deck plans).
* *Player handout 3:* Regional map
* *Player handout 4:* Readout-1

=== Episode Two: Across the bright face

The PCs have a map of the region. They must decide where to walk. They're on foot and have limited air and water. Enough for 48 hours. As they travel across the lunar no man's land they roll on an encounter table each hour of travel. They may encounter discarded equipment, derelict shacks, killer drones or even pirates.

At some point the players will roll 6 on the facilities table, at which point they find Missile Silo 792, which takes them to Episode 3.


=== Episode Three: Oasis

Eventually, the PCs find the entrance to some kind of underground base. It's a hidden missile silo, apparantly intact and operational - the missiles are gone, but someone has rigged a railgun into the missile launcher. It's the strongest source of local jamming and although there's a functional communication system but it is locked down with encryption, the jammer itself could be modified to send out an S.O.S. signal. The PCs can spend time exploring the base, learning a little about people who once mannned the station. At some point a group of pirates rigged the silo to launch missiles at low flying or ground vehicles.

If they manage to modify the jammer to send a signal, the first people to turn up won't be a rescue party, it will be a contingent of pirates wanting to know who is messing with their missile silo. A fight will ensue.

This episode is part puzzle, part who-done-it. Sam/Zena is a member of the pirate gang that has wired this this station up as part of a network of weapon systems that it uses to bring down low-flying traffic. As such, Sam's arrival at the station unlocks most of the security. The station's computer will say that station security is now disabled, now that authorized personnel have arrived. At some point the PCs will realise that this actually means that someone in the group is part of whichever gang set the site up. 

Sam will send a message through the encrypted hardline saying that she needs a team sending out to the site to extract her and the booty.


=== Episode Four: Moon Siege

An alarm triggers. Two vehicles are driving towards the bunker. They're just over an hour away. Remote sensors indicate the vehicles are medium-sized armoured transporters. They look like pirates. The PCs have about an hour to prepare for an attack on the bunker. During their journey in Episode 2, several useful items were encountered that might help in the bunker's defense. A ground of combat drones. Small arms from a drop pod. The PCs could hack the bunker's railgun

=== Episode Four: Moon Cavalry

If the PCs lose the fight, a rescue party will arrive just in time to save them. If the PCs hold off the pirates long enough, the rescue party drives away the pirates.

=== Epilogue

The PCs are taken to the nearest settlement where the local security force will debrief them. 


== Episode One: Moon crash

.*Player handout-1:* Travel Manifest
____
* Luna Excursion Rig LER-21, Registration L-XP32-J12P, in transit to Copernicus City
* Carrying light cargo and five passengers.
Passenger Manifest: +
*Jack Derenger*, carrying precious cargo in a suitcase. Declared prototype scematics. +
*Zeena Platts*, 20-year-old interior designer, leaving the polar regions after a number of jobs improving various communes. +
*Anjar Sing*, 40-year-old surveyor, heading for early retirement after a couple of big mineral finds. +
*Trix Montang*, nonbinary folk singer and performance artist, returning from a tour. +
*Freddy Happyness Cheaplove*, journalist from the Azania archology, doing a backpacking tour of Luna. 
____

.*Player handout-2:* Shuttle sheet

image:https://dub01pap003files.storage.live.com/y4mhNnDnw0tWXMXhWlBhT5z_X_WuH3zv5k_i8YIUA5MOyRFDWdkvmXnH0jCZkP4NuCcPfAC_DAW1gWQ_NoT6YuMhtGrbtB_OsAtQdXoy8Af8T7Cxp1wjDva1eH8hIounpM4LAwaMA9IZyTLrj-fHpiMjlPanP8NP-T5OPyxHeJVrLqT8VNW49AdnaTCXN3TuK47?width=724&height=1024&cropmode=none[Bantam1]


.*Player handout-3:* Regional map

image:https://dub01pap003files.storage.live.com/y4mrvzjoAn2TKqykoGkkbnYgYRFPVYcKIflpHaKf63mBy36BGjhKVeucW-byGEp9Jty4m67A_Spv63xZ2q3xoM9LahmpMqXPFNu8oD8pjD7JzkBazEjY_1Fp5vngIzq6pjucbYdnN9IdY_KwqJa5I3EjXxCdso1M5fEXa7VNRXScUHS_N7wx69rAbevQjGLBvZp?width=1024&height=754&cropmode=none[alt=Map1,width=1024,height=754]

.*Player Handout-4:* Readout-1
____
*GM:* The LH41 Bantum flies over the baked white desert of Mare Imbrium, about halfway through the journey and about twenty minutes out from the next refuel stop. You attend to your flight monitoring responsibilites. Behind you, passengers chat.

*Player1:* We're passing over a no-mans-land region. This is where some of the fiercest fighting of the second Luna war happened. In fact this area is considered very dangerous as there's still a lot of autonomous weapon systems laying around. We're inside the area of smart jammers so don't panic if you're unable to connect to LUNAnet.

*Jack Derenger:* On that note, I'd like to thank everyone for letting me adjust the flight plan to take us this low, slow and with our IFF disabled. I think it only fair that I now explain that I'm an intelligence operator carrying highly sensitive data for the Copornicus City goverment. I needed to fly "off the grid" because there are most certainly operators working for adversary nations who might try to grab the information.

*Anjar Sing:* That's alright Mr Derenger. In fact, this flight profile is much safer! In the event of a propulsion system failure, flying fast and high results in a 750% increase in mortality. 

*Zeena Platts:* [Dismissive tone] In the event of propulsion failure. What about Mr Derenger's adversaries? What do they do to our odds?

*Jack Derenger:* Ha ha, well there you go.

*Trix Montag:* Dick move, Derenger. Shoula told us the truth before we set off.

*Jack Derenger:* I'm sorry, Trix. It was not my intention to deceive anyone. As Anjar says, this is actually safer -- if slower and more expensive, and I've covered the extra cost, and some.

*Zeena Platts:* Whatever, man. If you think you're a target, slower might not be safer. And you should have warned the passengers of the fact.

*Freddy:* I have to warn you Mr Derenger, I'm an investigative reporter. Could I persuade you into giving me an interview, when we reach Copurnicus City?

*Jack Derenger:* I couldn't divulge anything about the operation, but Yes, on condition that you withold publication until after my retirement.

*Freddy:* [Giggles]

*GM:* There's a loud thud. Then a second. Then a third. The Bantum's engines have stopped and the everyone feels a steady downward acceleration. The command consoles light up with countless emergency symbols. An automated message plays out "Warning! Catastrophic engine failure. Automated recovery system enabled. Emergency burn in 3 seconds. Landing speed will be faster than is optimal. Please brace for impact....
____


== Episode Two: Across the bright face



[width=50%]
|===========================
1D6 | *Encounter Table*
|1        | No encounter, rock, dust and the black sky.
|2        | Small surface debris. Roll on the *Debris Encounter Table*.
|3        | Small surface debris. Roll on the *Debris Encounter Table*. Add +1 to the roll.
|4        | Crash site. Roll on the *Crash Site Encounter Table*.
|5        | Small ruin. Roll on the *Ruin Encounter Table*.
|6        | Small facility. Roll on the *Facility Encounter Table*.
|===========================

[width=50%]
|===========================
1D6 | *Debris Encounter Table*
|1        | Scattered rocks
|2        | A small crater, about 10m in diameter surounded by rock fragments.
|3        | A large crater, about 50m in diameter. + 
Walking through the crater requires some checks against dexterity. 6+ to avoid a fall.
|4        | Signs of fighting. + 
Metal casings and fragments are scatered around. Maybe some discarded pieces of equipment
|5        | Signs of a battle. Equipment and some empty magazines scattered around. Pieces of space suit. No bodies remain but you definitely get a feeling that people met there end here. 
|6        | An intact lander sits on the edge of a small crater. It doesn't look have been stripped, but the PCs quickly identify that tiny bomblets covering the area. Any attempt to get to the lander will likely result in your death. However, if the PCs are creative they can liberate about CR3000 from the site.
|===========================


[width=50%]
|===========================
1D6 | *Crash Site Encounter Table*
|1        | Debris from a crash vehicle. Nothing remains except for burnt fragments.
|2        | A wreck of a small rig. Looks like it came down hard and exploded. Nothing of value remains.
|3        | The wreck of a large lander. It looks like it made a soft landing but then took fire on the ground and was therefore abondonded. Inside the wreck are intact pieces of equipment. Roll on *Basic Equipment Table*.
|4        | A group of four tracked drone tanks. Someone removed their battery packs. They're too big to carry, so even though they are valuable, the PCS can't benefit from them.
|5        | The wreck of a light combat rig. Came in hard. There are live bombs and missiles attached to its ordnance racks. There is a small risk that the bombs and missiles might detonate if the site is disturbed. If the PCs risk exploring the rig, they can make the ordnace safe, they find 1D6x10,000 cewsee
|6        | Small facility. Roll on the facility table.
|===========================

== Operating on Luna

Operating on Luna introduces the following challenges, that should factor into many of the actions that the PCs may wish to take:

* *Gravity:* You weigh about 16% of your mass. If you're not wearing a heavy vacc-suit then much care is required while walking or running as there's a serious danger of hitting your head when you take too big a step. 

* *Temperature:* Under the constant glare of the sun, the surface reaches 120 celsius Celsius. At the night side, temperatures drop to -180 C. Permanently shadowed regions (PSRs) are extremely cold (minus 240 C). Vacc-suits are not optional.

* *Dust:* Luna is covered in a dust that is much like fine volcanic ash. Its a serious irritant, toxic and damaging after long-term exposure. It clogs up machinary and causes a wide range of problems. All habitats need extensive must removal systems to prevent contamination.





== None-Player Characters

---
====
*Zeena Platts* (Realname: Sam Modey)  +

[width=500px]
image:https://dub01pap003files.storage.live.com/y4m2DgiBlAJFBUTftFn3UivMdlowj_f-3B2WqxnMrQksY4YCpxoriFGBrnLwF8hYcGG_4UXbbPDAoV-ICwOu3Hp7YhIoKA7toufZdP0PrKglDtx5PvGJMt6diIcVJ1UajmIkPcWZYaR9csjRhUTbO3WKk7ABTA1tvLuJq_h7tcgC4bIuG_G7Wy9uid7zQ98VNHj?width=660&height=660&cropmode=none[alt=Zena,width=340,height=340]

*UPP:* 896A38	Age 22 +
Interior Designer (actually, Pirate (1 terms) Rank 2 - Lieutenant) +
Electronics-0 , Energy Pistol-1 , Engineering-1 , Space Vehicle-0 , Piercing Weapons-0 , Piloting-1 , Streetwise-1 , Survival-0 , Turret Weapons-2 , Zero-G-1 +
5,000 cr +
Vacc Suit

Zeena is a "Jonah". A passenger who operates as an insider for pirates.
====

---
====

*Jack Deringer* (Real name: Percy Brennan)



[width=500px]
image:https://dub01pap003files.storage.live.com/y4mUdEJq0h4RbeoloWvV_ElWyMwkaqMInzdaW9ihUgGDVclZmKryg2RHGPmFuq45094ieWt4wXzbqVRe4XConNk37Pgs12a9dIjBKkM4eOPJ76uoacT-k3liFvFtBzngN8KpyFj8r4fX4WHPVIbUsmRLwdO6BxpUQxFXlyZTJ4aBkvqjHyleEzpefk63Y3_Eu-V?width=660&height=660&cropmode=none4[alt=Percy,width=340,height=340]

*UPP* 455D79	Age 50 +
Colonist (5 terms) Rank 5 - Lieutenant Governor +
Drifter (3 terms) +
Admin-0, Electronics-1 , Farming-3 , Gambling-1 , Liaison-1 , Mechanics-1 , Natural Weapons-1 , Recon-1 , Shotgun-1 , Streetwise-1 , Survival-2, Tracked Vehicle-1 , Zero-G-0 +
235,000 cr Pension 10,000 cr

Percy spent his life working diligently in hydroponic farming. He got really good and made a modest fortune. A few years ago he realised that what he really wanted was to be an espionage agent. Too old and with the wrong skillset, Percy instead turned to a life of deception. He travels the solar system under different aliases pretending to be spies, pirates or just damned mysterious. He doesn't use his deception to rob people, he just wants people to see him as an interplantary man of mystery, not a moderately successful hydroponics engineer.
====
---

*Anjar Singh* 

[width=500px]
image:https://dub01pap003files.storage.live.com/y4mQ52Kt3GHfFuWFr8swiDF22MmKwTfSBqWKstpDWv1v3F3iBk1RVcswO6F_FRirxFb4QbFGpOFst_FiNg81CbI36m-r9dVDMwOeQYt61ZKggOTNPbCYhNhcVC5y9C5QUy6rNUVCIQvBn44S76xVgUcXcHi9g2YDNw33PkwoNx-J9SxhpTKD_qTupydFDg0cw_-?width=943&height=953&cropmode=none[alt=Anjar,width=340,height=340]

*UPP* 657B66	Age 34 +
Belter (4 terms) +
Comms-0 , Demolitions-3 , Electronics-1 , Energy Pistol-0 , Heavy Weapons-0 , Mechanics-0 , Physical Sciences-0 , Piloting-2 , Zero-G-2 +
35,000 cr +
Mid Passage +

Anjar is a asteroid miner. A pretty good one. He has sizable shares in several valuable mines. Having nearly come close to death three times in his career, Anjar has decided to cash in and find another life. Sadly his brush with death has left Anjar suffering from mild paranoia and panic attacks. Nothing serious, but it makes him likely to call out wild suspicions.

====
---

*Trix Montang* 

[width=500px]
image:https://dub01pap003files.storage.live.com/y4m_l4CAUDGgoUee0jv-tteaWL0DOiM3esotYJZzm110OBO4gcJQmpWP6ALc0a5BN4DIbasYRMD6CR3L11tmrc0L_kQcsV0H1A1kukRA3FyrxcZU31z6pLmPODl-n8QigNxCfGqpU3epZyb0MSLwaumX4WY1_P-ziLtgn_fjzMVFKQxmrftlWbh8jhLgqSyT41U?width=660&height=660&cropmode=none[alt=Trix,width=340,height=340]

*UPP* 46AA9A	Age 34 +
Entertainer (4 terms) +
Admin-1 , Athletics-1 , Bribery-1 , Carousing-2 , Gambling-1 , Liaison-2 , Linguistics-1 , Social Sciences-0 , Survival-0 , Tracked Vehicle-0 +
1,120,000 cr +

Trix is a non-binary folk singer, guitarist and writer. Trix started out as a rebellious punky sort of solo performer. Now they've started to struggle for new material having become critically and commercially successful. Today, Trix is having to act the part of a young, angry and hungry performer. They have a tendency to over-amp anger and angst which come run past edgy and into, well a bit scary. Songs about burning it all down, dropping anti-matter bombs on Earth and generally doing over-the-top things have given her a reputation as song writer for budding revolutionaries. A reputation that has kept her busy visiting various small mining colonies. 

====
---

*Freddy Happyness Cheaplove* 

[width=500px]
image:https://dub01pap003files.storage.live.com/y4mW7hLop0ZOEJT2mRECXSJ3ruPazquavNmRK7F9Jiw7evQSorYLkKw3pvdbljMUBMfjRWqQAIGDH8xAHkTLTRU6yA5mnpPcAUOj-fpL3YGkOf06f0kYKYLO3UySJuxXYP8MHkBMMIf70RO1savu-ADOsi-Al1UygCzfnIiox9Sf-kwVu6kfDQtKt37s_eN6Z5j?width=660&height=660&cropmode=none[alt=Trix,width=340,height=340]

*UPP* 67B4B9	Age 26 +
Journalist (2 terms) Rank 3 - Investigative Reporter +
Admin-0 , Bribery-1 , Carousing-0 , Computer-0 , Leadership-1 , Linguistics-1 , Piercing Weapons-1 , Streetwise-1 , Tracked Vehicle-1 +
15,000 cr +

Freddy is an investigative journalist, working for a news service that operates out of The Central African Archologies. He's been investigating corruption amongst the polar mining settlements. He's started to annoy a number of criminal sorts. His editor has caught wind of the incidents and has recalled Freddy to the Copernican office. Freddy is a natural information differ. He has a great instincts for a story, and is a good reader of people's motives.
