
== Note Pad

Just a place to dump ideas.

=== Lost cities

=== Uplifts and Chimeras

Some Primates have been genetically manipulated to increase brain size and complexity.

Out in the unregulated places are customised life forms.


=== Organic space robots

Athena created a class of biological entities that are created to live in the vacuum of space. These range from small limpit-like creatures that can stick to hulls, right up to leviathan sized entities that can wander the Solar System looking for tasty asteroids to eat.


=== Life Extension / Resurrection

In 2288 it is possible to rejuvinate (reset the aging process, returning the subject to a younger age. Usually the process can be used with the subject reaches 40. It can reset the subject's age by 10 years.

=== Settlements.


==== Begondala

==== Reef-12

==== Ozzy's Reach

==== Dewi Ratih 

God of the Moon

====  purnama

Moon 

==== Chandra

Indian colony

Moon

==== Voltaire 

French/European colony

==== Bergmann

German/European colony

==== Unity 

International colony, open to all Earth nations/archologies

100 million pop. Made up of three interconnected archology structures. Surface, cavern and deepwell (15km deep)

=== Begondola

=== Ramat David

Israeli orbital

=== Casto Valanteia

=== Harrison Straton

=== New Manhatten

=== Kilamanjaro

=== Ridleyport

=== Asorokant "The Scant"


== Advancer cults

There are small pro-unbound cults. They worship Unbound AIs as gods. There are such cults in both Advancer and Athenian groups. To be a follower of the Unbound is to work against humanity. It is the acceptance that organic life was nothing more than the egg from which artificial intelligence is born.
