ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Free fallin

[.lead]
The following mini-adventure is a great way to introduce new players to Orbital Elements. At the beginning of the adventure the PCs are not a party, but in the first chapter they are thrown together and must quickly learn to rely on each other in a deseperate struggle for survival. 

[NOTE]
====
**NOTE:** This adventure is intended for a group of 3-4 new players and a Game Master. You can create new characters before the adventure session or you can use the pre-rolled characters provided at the end of the adventure.
====

image:https://db3pap001files.storage.live.com/y4m2BNQMeshdJIzqvQbzORXneLXCwgNIUs-iAeqAK_DaITAf8GskR65EqicCUI2jEq4O5ni54Wmd7uRXAlcxfMJL2xmErivpMQV2RLARtvSXO6zogoomZ4tEAl9oYhXVfIdMmqgBJGkz7uqGbDfskKkUVPnhJ62JWgQ8uzARMLP-nIZXZKN3uMVO6vQAbsDH3KG?width=1024&height=576&cropmode=none[image1]

==== Section links

* link:#adventure-summary-game-masters-eyes-only-1[*Adventure Summary*] 
* link:#chapter-one---the-breaks-1[*Chapter One - _The Breaks_*] 
* link:#chapter-two---free-fallin-1[*Chapter Two -_Free Fallin_*] 
* link:#chapter-three---fight-the-power-1[*Chapter Three - _Fight the Power_*]
* link:#end-credits[*End Credits*]

[[summary]]
=== Adventure Summary (Game Master's eyes only)

==== Chapter One - _The Breaks_

In the opening chapter, the player characters are prisoners on a patrol carrier operated by the mercenary force that handles anti-piracy duties out of Lanserda Yeocan, the industrial settlement on Callisto. The players were unlucky enough to be travelling on a transporter that the mercenaries accused of piracy and impounded. All onboard the transporter were arrested. As play begins, the PCs have been held on the patrol carrier for three weeks. The captured passengers are then loaded onto two shuttles and launch to unknown destinations. All the PCs are loaded into the same shuttle. There are whispers among the other prisoners that the patrol carrier is returning to its base and transferring the prisoners to a free station for interrogation and release.

Within hours of its departure, the PC's shuttle makes a detour. The four crew become agitated. The talk between prisoners is that the shuttle has been ordered to investigate a transporter that briefly broadcasted an SOS before going quiet. Soon, the PCs are selected by drawing straws for a potentially dangerous mission to board an apparently derelict transport vehicle.

==== Chapter Two - _Free fallin_

The PCs make the 300-metre trip to the apparently lifeless transport vehicle. The moment the players board, some kind of munition launches, destroying the shuttle they were travelling on. The PCs now seem to be alone.


[NOTE]
====
*So what happened on the derelict?* +
While making a routine cargo run to Callisto, some of the transporter's crew, loitering around the cargo deck, decided to tamper with the wrong package, a robotics system called T-12. The system is an advanced humanoid robot of unusual complexity. The crew members activated the robot for poops and giggles, not knowing that the robot wasn't a "labour droid," contrary to the manifest description. When the group tried to have some fun ordering the robot around, they were attacked and immobilized. 

The robot appears to be a prototype anti-piracy droid intended to act as onboard security. However, the unit is not supposed to be activated without being programmed with the crew's IDs and biometric information. Consequently, on being activated, the droid is classifying all of the crew as hostiles. In the ensuing fracas, the crewmembers were either immobilized and captured or in hiding. Making contact with crew members is the easiest way for the PCs to learn what's going on. 
====

At this point, the PCs get to explore the derelict, _Independent Transport Vehicle Golden Goose_. Chapter two consists of scenes that deal with different locations in the transporter, so scenes will play out based on where the players choose to send their characters. The PCs must unravel the mystery of the Golden Goose and find a way to take control of the ship before it coasts out of range and ends up floating into a deep system orbit.

There are six entry points into the Golden Goose, a full airlock in the command module and each of the hab rings, an airlock at each end of the vehicle's stem, and two airlocks in each cargo module. Finally, there's an emergency lock in engineering.

**Command Module** +
Some clues in the command module point to the ship having been locked down by some kind of security incident.
There are small bloodstains in the central access area of Deck 2.

**Hab Modules** +
There are four Hab module decks. The first (Deck-5) is used by the crew. The other decks are not occupied. Deck 8 is cordoned off with a notice that says, "Keep out, cleaning in progress." There are clues to a struggle in the main lounge area (room C on the map). Most of the staterooms appear to have been sealed by some kind of super-strong repair tape. Unless a removal agent is applied, it will be easier to smash the doors in than remove the tape. Held in the rooms are Almona Wash (D), Tony Pendula (N), and Simone Acosta (M). 

Making any kind of noise will result in Almona shouting for help. Her priority is for getting the PCs to go to Engineering Control (deck 21) to look for her husband. The crew held in the hab decks have a water supply and snacks, but she is worried for her husband, Ross McAlpine, as there's no food or water in engineer. Ross may be slipping into a coma or even dead after three days without water.

Almona tells the PCs that an unknown droid appeared in the cargo hold and attacked the crew. While it didn't use lethal force, it has locked down the Golden Goose, which means it is coasting past its required orbital insertion point and will head into an unrecoverable orbit in a few hours. Unless the PCs can take control of Engineering Control, everyone onboard is doomed.

Tony Pendula shouts at the PCs that the tape sealing the doors is molecular bonding tape (MBT-40). There's a spray for its easy removal in a container on the cargo module (Deck 17). There's also the ship's locker, located on the command deck (The side room that connects to B, on Deck 2) which contains a number of firearms, however, it has a biometric lock so only Almona or Tony can open the cabinet.

Simone Acosta tells the PCs that she thinks that the incident started in the cargo hold. Lars Anderson and two of his maintenance team were on Deck 10 just before the incident. Simone adds that she doesn't recognise the make of the droid; it is not part of the ship's official equipment.

**End Cap "Clamp" Decks (9 and 20)** +
There is no apparent activity on these unique decks that clamp each end of the huge cargo modules to the stem. However, if explored the PCs may encounter the gravely injured link:#lars[Lars Anderson].

**Cargo Decks (10-19)** +
There are nine cargo decks, each is 9m high, creating a huge area to potentially explore. There are clues to what happened in the central area at the top of the map (D) on Deck 10. In the middle of the room is a storage container on which there are flexiscreens that display various documents that claim that the container was storing a UD-27 manual labour droid, which is a fairly common utility droid. On the labels are a corporate insignia, a white rook chess piece, set against a starfield background. _The logo doesn't connect with anything else in the adventure. It's really a clue for a future scenario that features Trigean Systems._ 

* The PCs might notice security cameras, suggesting that the events that played out in the cargo section might have been recorded.
* A PC with computing skill can make a difficult role (10+) to notice a procedure buried in the container's documentation that allows for the robot's firmware to be remotely updated, using a small data card still contained in a pocket in the storage case. This card could be used to initiate a reboot and upgrade of T-12, but only from the central engineering control room (Deck 21).

**Engineering Control (21)** +
This is currently the control centre for the transporter since the activation of lockdown has disabled all controls in the command module. Naturally, it is also T-12's default hiding place.                      

**Fusion Control (22)** +
This deck is essentially a balcony with an interior space filled with the fusion powerplants that stretches about 15 from top to bottom. This section is locked from the outside. If the PCs enter the stem access room they can open the door and find the sleeping Ross McAlpine. See link:#captains-orders[Captains Orders]. After drinking some water, Ross will start to wake up and will provide advice to the PCs, although he's far too weak to be able to provide physical help.

**Drive Deck (23)** +
This deck provides access to the Quan-Ebrahimi drive. There's nothing here of interest, but it does have an emergency airlock that T-12 can use to travel across the hull to access 

==== Chapter Three - _Fight the Power_

Chapter three starts when the PCs have pieced together what's going on and contact the trapped or hidden crew. The main focus of this final chapter is whatever plan the PCs come up with to take back control of the ship. T-12 is an unstoppable force and an immovable object. Successfully completing the adventure will depend on some clever planning. However, the PCs have some advantages and a ship full of stuff. Winning through combat is the least effective and most dangerous road to follow - the PCs begin the adventure unarmed, and the firearms in the emergency locker are intended for use in self-defense against human attackers. 


*PLAN-BETA*

Suppose the PCs gain entry to Engineering control, or they manage to evade T-12 in an encounter. In that case, T-12 goes to the Cargo decks and unpacks 6 labour droids to act as its minions. These standard droids don't have much to contribute except for evening the numbers. They are not effective and can be disabled relatively easily. 


=== Chapter One - The Breaks

==== Scene-1 

*Location:* Patrol craft: Jian Suur (Sword-4), Jupiter far orbit +
*Time:* June 12th, 2288 

.Readout:
____
Three weeks ago, you were heading for Mars aboard a scruffy but incredibly cheap transporter. Before you could decide what to spend the money you saved on, the transporter was intercepted by a military patrol vehicle working out of the Chinese colony on Callisto. Apparently, the Chinese defense force personnel believed IPS Sugarhill, the cheap transporter, has been involved in piracy. Everyone on the Sugarhill was handcuffed and taken aboard the patrol vehicle.

A few hours ago, you and eleven other Sugerhill passengers were loaded onto a shuttle, destination unknown. The rumour was that the Defense vehicle was heading back to Callisto, so prisoners were transferred to a prison bus (shuttle). Twelve prisoners were secured in a passenger cabin with three guards and two crew.

Some of the prisoners believe they are being transferred to a free station to be released. Others whisper a more worrying story -- apparently, some private military contractors do a background check on prisoners that they pick up. Anyone who doesn't appear to have rich or influential friends is sold into slavery - their arrest recorded deleted by hacker gangs.
____

The guards of the shuttle become agitated. The following conversation is heard:

.Readout:
____
**Guard 1:** We're being retasked. Apparently, a nearby transporter reported a possible pirate attack but then went dark. I'm not risking my neck going onto a derelict. I didn't sign up to fight pirates. +
**Guard 2:** Haha, won't be any risk. Captain says the boarding crew is getting decided by a prisoner lottery. +
**Guard 1:** NO WAY, I already lost one vac-suit this year when I was forced to lend it to a prisoner. +
**Guard 2:** You don't loan a suit; you don't get a cut. It's a big ITV, a 30-thousand-tonner. Even if it's empty, there will be a million in salvage, each. + 
**Guard 1:** A million. Okay, but better be right about this.
____

The twelve prisoners are escorted to the operations deck and strapped to seating at a large table. Each prisoner draws a lazily fashioned straw. The PCs each draw the short straw. Before this moment, they had separate lives; now, they are linked by a momentary act of chance.

The other prisoners appear visibly relieved. Many of them shoot you with concerned looks. Nobody speaks to you but their eyes are saying, "it was nice knowing you."

The shuttle's XO gathers you and leads you to the EVA bay and airlock. You are dressed in slightly worn mid-range vac suits.

The officer, a wiry Chinese man in his late 50s, grins grimly at you. "Nine times out of ten, everything fine. Everyone happy. Good odds! You not heroes. You not take risks. Go in, report on what you find. If danger obvious, report and withdraw."

Fran gives him a steely look. 
____
*Fran O'Malley:* One in ten is NOT good odds. If it was good odds, you wouldn't need to use impressment. By the way, impressment is ILEGAL.
____

The XO's face blanked, making the man's mood unreadable.

____
*XO:* You must think I am a bad man. I am NOT a bad man. But I am a hard man. My duty is to protect my crew above all else. I'm not impressing you. I'm making you all deputies. Regulation 275.9: 'During an emergency situation, the command officers may deputize any passengers if there are insufficient crew to fulfill mission requirements safely.
____
A klaxon sounds. Pumps begin to pressurise the airlock. A guard checks over the PC's space suits. To one PC, he tells them not to pull hard on the left sleeve as the seam may have a micropuncture.

____
*XO:* All you need to do is check out the transporter for survivors. Nobody on the ship is communicating now. There's a chance the ship was completely abandoned, or maybe the crew is awaiting rescue. Or they might all be dead from a deadly radiation leak, but it that happened, we would surely detect it from your suit sensors the moment that you enter.
____

=== Scene-2 I think we're alone now

All PCs have the following equippment/capabilities:

* 1 Worn light-armour space suits with integral comms, head-lamps and wrist-comp
* 48-hour emergency provisions pack
* 4 First Aid packs
* Schematics of the Independent Trading Vehicle Golden Goose (loaded onto their wrist computers.)

The PCs are strapped to an EVATD-79 "huskie," a coffin-sized drone with rungs that astronauts attach themselves to. The drone handles the maneuvers of an EVA, so it is ideal for people with little or no EVA experience.

The PCs transfer 3000m between the shuttle and the transport vehicle. The PCs are now free to decide how and where they enter the vehicle.

[NOTE]
====
Pass out the deck arrangement sheet. The airlocks are displayed on the left-hand side (*See below*). The Huskie will maneuver The PCs to any location/airlock that they choose. 
====

image:https://db3pap001files.storage.live.com/y4mZxiXRDVzd1Ftqoq6Lv-GZXZGAKLw3f812Mo-yAaE95r1Py0qGv3u78vobEm-Xb0Eep_wGZvuoWAYm2cA5GttIBGH5rel4YH0ceGziHmZ9qFZGEfQ5Im1F_3TlLGe1WNC-RFDeAO5EksgkF4Wiaj0YHDlQfG1LLVO28bxAMWWXmZmH3AJnIDuDaCKCEkXdy1s?width=724&height=1024&cropmode=none[image]

The PCs may choose to enter at different points. While this is challenging to run, it shouldn't be discouraged. Splitting the PCs up can seriously build up the tension.

Once the PCs select an entry point (or a number of entry points), proceed to the section corresponding with that or the first location.

*BOOM* +

The moment that someone opens an airlock, there's a glow of light. A small module, about 2m long that may have been attached to the transporter fires a projectile in the shuttle's direction. Instantly the shuttle turns into a cloud of hot, shrapnel-filled gas. Nothing is left of the shuttle, just streaking fragments o' burning hull. Gone in a blink.

.Readout:
____
Moments after the airlock opens, you become aware of a sudden brilliant bright flare. Turning to the ball of light, your vision is momentarily lost by the glare. The light is coming from the direction of your shuttle. As your vision clears, you now see tumbling fragments of hot metal and plastic. The shuttle has been destroyed. 
____

=== Chapter Two - _Free fallin_

The PC's all go into shock. Their breathing becomes erratic and they need to make a difficult (8+) endurance role or suffer from panic. This increases the difficulty of all actions by 1 or 2 for D6 minutes. 

==== Dancing in the Dark

*The derelict vehicle is an independent transport vehicle called the Golden Goose. Readings show that the power is on, but the engines are off, so the Golden Goose is coasting along. This means no acceleration, so no simulated gravity. Many onboard operations will require Zero-G skill checks.*

The ITV Golden Goose is a Languedoc-class 30,000 ton heavy hauler. First built in the 2190s, the few that remain in operation have been retrofitted with updated engines. However, their modular design is otherwise unchanged. The vehicle is assembled around a 200m-long graphene-lymar composite stem. Behind the command module, habitation decks are slotted in. A single hab-deck can be fitted for a dedicated hauler that will only carry a crew or up to twenty decks if the transporter operates as a passenger carrier. The hab deck design is an open ring that slots onto the stem and is then welded into place. Removal requires a refit at a construction yard.

image:https://db3pap001files.storage.live.com/y4mHV_uhTQjk01vl0KeIQAwNxNDFlnIGPRWklJ7Gyk6JUtWj_TwWp_5DqgD2ZchPku8iTz4ArqjkYIX-rmTw1werVUWxPWdGYetGmTrUlc85uDB-IFiCrFZC57vWSPT7enzwnbZLLygQT0vE-Z-g5yZ3fCH5QVbA2OhqelfsOTSsrI2F-lcjRAjSMtR7-02nt0V?width=1024&height=616&cropmode=none[image]

The cargo modules come in various shapes and sizes. The Golden Goose carries two cargo modules that clamp onto the stem to form a cylinder. Each module has nine decks, each deck being nine metres from floor to ceiling, allowing the transportation of large vehicles, plant machinery, even small space vehicles. To load and unload, the two modules uncouple and separate from the stem to make the cargo doors accessible. There are no hatches on the outer hull, which is heavily reinforced and shielded.      

The cargo modules are held between decks nine and twenty, which contain machinery for seperating and reconnecting the modules for loading and unloading.

The following section is a large torus that stores the vehicle's reaction mass, either water or, in later models, carbon-diamond dust. Three separate fusion power plants are fitted within the hole of the torus. While in transit, two power plants are run, leaving the third in "hot" shutdown. At regular intervals, the shutdown plant is swapped with a running power plant. This operating cycle ensures that all powerplants are regularly purged and recalibrated. Most of the generated power is used to supply the drive module, equipped with six Amarok-71 QE-thrusters for a sustained 0.5g acceleration. Fully loaded, this gets a Languedoc from Earth to Mars in 8-14 days. 

[NOTE]
====
.Describing the Golden Goose
This is not a standard space vehicle. You might be generous and describe it as a "classic," but in truth, this is an "old banger." Most of its internals, engine, and systems have been replaced two or three times during its 80 years of service. However, most systems are still probably about 20-years old. Nothing is outright grimy, but almost everything is showing wear-and-tear. Most things work as they should, and mostly they work the first time, but not always. _Don't overplay "rickety", but once in a while, remind the PCs that this maybe not be the most reliable or safest transporter._
==== 

==== Every Breath you take

T-12 is linked into the cameras and sensors that monitor most goings-on aboard the Golden Goose. This includes pretty good radio reception from the PCs space suits. With this in mind, play T-12 as always two steps ahead of the PCs. The PCs might make skill rolls to tease out that they're being monitored. If they work it out, they can start disabling cameras and mics. They can turn encryption or line-of-sight modes on their vac suit radio to prevent eavesdropping. Taking these steps will make T-12 seem far less omnipotent. However, it will also compel T-12 to active PLAN-BETA, in which it activates additional labour droids.

==== Under Pressure

Several "side-quest" activities provide some focus for the PCs as they bounce around the Golden Goose. They're not essential to the adventure's conclusion but give a sense of urgency and provide opportunities for role-playing fun.

===== Captain's orders

Like most of the crew, Captain Wash is sealed into her stateroom and is trapped. She's aware that Ross, her husband, was located in the Engineering Control room when the incident started. She is in a panic that Ross is trapped there because there are no stores in that location. In three days, Ross may have slipped into a coma through lack of water. Captain Wash will implore the characters to find Ross and provide assistance as a matter of urgency.

*outcome:* In fact, Ross was dragged from Engineering Control and was locked into Deck 21. He managed to break into the central Power Plant bay in the hope of finding an access hatch or air supply duct to sneak through. He failed to find a way out that he hoped for, but he did find a secret party stash, a case of party materials, including 4 bottles of red wine. Currently, Ross is sleeping off the second bottle. He has a cracking headache but is otherwise fully restored if given water to drink.

[NOTE]
====
.Wine-only 
Alcoholic drinks are dehydrating as they remove water from your cells. However, wine is also 90% water, so wine will, on balance, hydrate you. So you won't die of thirst drinking only wine. At least not as quickly as drinking nothing, or -- it has to be said -- drinking your pee, which will likely only extend your survival from 3 days to 4. As a bonus, red wine also contains some nutrients and calories, so it substitutes for a bit of food. Good to know, eh!
====

===== Lars

Lars Anderson is the cause of this big sorry mess. He spotted some inconsistencies between the manifest description and the T-12 container. He opened up T-12's case and decided to turn the droid on, mainly because it didn't look like any droid he'd ever seen before. Things instantly turned bad as T-12 grabbed his crewmates. Lars knew he would be in heaps of trouble for it, so he absolutely threw himself at the problem. T-12 broke Lars's arm and caused so much bruising to his legs that Lars can't walk. He crawled off and is currently lying behind machinery in the top (A) on Deck 20. He's delirious and will babble while lying in a semi-conscious state. He's critically ill as his broken arm has gone bad - there are dark red and purple marks along the fracture area. He needs immediate medical treatment to avoid death. There's nothing that can save his arm, he'll either need to have a new one grown, or he'll need to go cyber.

===== Anya

Anya Fillipova, one of Lars Anderson's repair Maintenance and Repair Team members, managed to evade T-12 long enough to get into a vac suit. She's actually set up a base on Deck 7, living in one of the EVA rooms, which she has barricaded from the inside. She uses her vac suit to make supply runs and to attempt to rescue other crew members. She may be encountered if the PCs explore deck 7 or spotted as she makes a supply run, heading into another part of the ship. A rasping figure in a large dirty space suit may be startling to the PCs. Likewise, a chance encounter with the PCs may cause Anya to panic and run away.


=== Deck descriptions                     

==== Command Module

image:https://db3pap001files.storage.live.com/y4mUGDji4EfnaNKZ31Eeo5M3AqKSBOOfDU1kP1KKuP_W-Q3UcGB9jbbcTgHylKuRhz_cFJwZb4YQrBEZnQy463RuZ9hYgrFyqVnJd4A00IHHXQINj_eUhSew5aH1bJ-ovL1yA6dYAtIVGR8O5rQDY3BgyRxdzDGOeB-NW5kshO914hi8-CDagsQmVULv1EEq4Md?width=724&height=1024&cropmode=none[image]

===== Deck 1

*(A)* Avionics deck is separated from Deck 2 by grilling, with lots of gaps.|Ladders in the central stem of Deck 2 can be used when the ship is under acceleration.

No signs of any trouble. Ships systems appear to be unimpaired, but an *+8* piloting or computer roll will reveal that the ship's systems are locked down from engineering.

____
This deck is located at the front of the vehicle. It's an open space filled with system cabinets, cabling, and monitors. Metal grilled walkways separate it from the deck below. There are no access tubes down to Deck 2, just ladders, which lead down into Deck-2's access tubes. While the Goose is not accelerating, it's possible to move between Deck1 and Deck2 without using the ladders. There's no sign of life or any apparent problem. Everything is on and working.
____


===== Deck 2 (AVIONICS)

*(B)* Backup systems. This has simplified control systems duplicated from the command deck (Deck 3). At the moment, this room is in "hot shutdown." Everything is on and is replicating the status of the control systems on the main deck. However, most of the holo-displays show a bit "Lock-down" label. Piloting roll 6+ indicates that this means that the vehicle's controls are disabled. This is standard procedure if there is any threat that a hostile force has taken possession of the command deck.

There's a side room (Emergency Lockers) that contains emergency equipment. Two large lockers require a biometric scan to open. These may contain sensitive materials, firearms, or controlled substances. There's no way to get into these cabinets; they can only be accessed by senior crew members.

*(+C+)* This room contains a briefing table, chairs. Some emergency equipment cabinets.

*(D)* More backup systems. Big metal cabinets filled with hardware, emergency power cells.

===== Deck 3 (COMMAND DECK)
____
You can immediately tell this is the command deck. Everything is triple-reinforced. The bulkhead materials are made of exotic materials, and the crew section is protected by a secondary wall. Outside the secondary wall are cabinets and boxes that carry cables and piping. The ring-shaped outer corridor ends in an airlock system that opens on one side into the stem access. On the other side, it opens into a command docking airlock. Three Emergency vac suits hang on the wall next to the airlock.
____

*(E)* Bridge. There are three crew positions for a pilot, a captain, and a systems officer.
____
The deck is dark. A dim red emergency is the main source of light. There are various screens. Most display the words "Lockdown." There's a coffee beaker floating near a wall. Droplets of coffee hang in the air. There are no signs of the crew. No apparent damage or signs of violence.
____

*(F)* Command Ring. Airlocks to the stem access system and the command docking airlock.

==== Stem Access

image:https://db3pap001files.storage.live.com/y4mb2yRdOfrVskdw37G_iAGbtOEzL7AOPcnBLNGYrlOCA3aFFrWYt2qAmX7WFFSkX3CGj-TtULJOs01WN74CzSKB2mlX92OR93q3YP82z196oNmJZAxUm6c6rX2XMwjbecDhzfo_-ApXyA0aeNni8XOeClhmIqW_RLALyu_ggqw7PY2yE1PM6zwahvr0hMynMrz?width=635&height=377&cropmode=none[image]

Running almost the entire length of the Golden Goose is the stem, a tube of incredibly strong exotic material on which most of the transporter's components are attached. Where modules are connected to the stem, there are corresponding access decks (illustrated above). Near the centre of the stem is the Transit Pod system, with two corresponding tubes providing ladder/rail access.

*Transit Pod* +
A Transit Pod system (labeled as "Rapid Transit" on its sliding access door) is at the center. It's a souped-up elevator that responds to a button call. When it arrives at your deck, a sliding door opens, you board it and strap yourself to the wall, then select a destination deck. Transit times are fast, end-to-end in 30 seconds, which pulls some gee. Travelling in the pod is uncomfortable, but it gets you from one side of the vehicle to the other in seconds, which could be critically important.

There's no possible access to the elevator chamber. It's not pressurized, and the operation of the pod would kill anyone foolish enough to be travelling along the shaft. When the vehicle is under acceleration, the Transit Pod shaft is no different from a lift shaft. Falling hundreds of metres, even under low-g, is still likely to be fatal.

*Ladder and rail tube* +
These tubes contain two ladders, one to the left and one to the right of entry, allowing two people to pass each other while travelling up or down the shaft. In the centre of each ladder is a rail that you connect a safety harness to. Wearing a harness that connects to the rail is a mandatory part of the ladder operation. If you enter and don't connect your harness, the tube's emergency valves close. While operating in the tubes is not risky in zero-g, the moment the engines go on, there's an obvious risk of falling. The rail system allows you to climb or pull yourself along the tube (in zero-g) at quite high speed. It only locks when the motion is sudden and under high force.

===== Deck 4 (SYSTEMS)

*(G)* Systems Control. Banks of monitors and controls handle most systems not part of the vehicle's propulsion, navigation, or maneuvering. This mainly includes life-support, communications, security. There's a single crew post for monitoring. This console is also locked down.
____
To the right of the hatch are a load of plastic boxes. Some are opened, and various bits of supplies and equipment float around them. It looks like someone was looking for something and left a mess. The stuff is all random; basic meds, rations, and battery packs.
____

*(H)* Systems Ring. This deck contains backup life support systems. Pipes and machinery that handle water purification and air filtration.

==== Hab Modules

image:https://db3pap001files.storage.live.com/y4mwu0QMOxXlAHggGNhprGi_s75CTF1YfJ9nR-BC_mOxFfS8Tbum3NluZhdECWXMvtM-fderghyXzonowAdBF0JEWUPEb7TzJeL5Bn1enS1r5EAovk2_IHDDxP53a31ERv8SgLNG-CkcuZauQsLzpNp2Rn63s2u1nebgqRJG2mWQwdXLFimcU2Dr3IE1SUk89_X?width=724&height=1024&cropmode=none[image]


The Hab modules take the form of rings with an opening on one side, allowing decks to be slid onto the stem. Each of the four decks is identical in layout, although only the top deck is in use during the current trip. The other decks were being cleaned before picking up passengers. Looking at the deck arrangement diagram, you may notice that the decks don't actually stack together. There's a 70cm gap between each deck. The only way to travel between decks is via the stem. 

[NOTE]
====
On transporters set up for large numbers of habitation decks, the emergency airlocks on each deck can be fitted with inflatable access tubes to provide additional access points. This arrangement is not used on the Golden Goose, although individuals wearing vac suits can move between decks.
====

==== Hab Decks

===== Deck 5 (Habitation)

*(A)* *Emergency Airlocks* - The top one is designated for entry only. The bottom lock leads to an EVA room. This airlock leads directly into the corridor/utility space.

*(B)* *EVA room* - This room contains equipment for storing, getting in and out of vac suits. Three emergency vac suits are hanging in the opening on the bottom wall.

*(+C+)* *Lounge* - A sizeable L-shaped room that contains couches, chairs, and tables. On the inner wall, mounted against the stem, are various food and drink vending machines.

*(D)* *Single-occupancy Stateroom* 

*(E)* *Single-occupancy Stateroom* 

*(F)* *Double-occupancy Stateroom* 

*(G)* *Double-occupancy Stateroom* 

*(H)* *Double-occupancy Stateroom* 

*(I)* *Double-occupancy Stateroom* 

*(J)* *Double-occupancy Stateroom* 

*(K)* *Double-occupancy Stateroom* 

*(L)* Locker/Safe

===== Deck 6 (Habitation)

This deck has the same layout as Deck 5. Life support is running, so the deck may be accessed without restriction. There's no sign of activity.

===== Deck 7 (Habitation)

This deck has the same layout as Deck 5. Life support is not running,  although the central stem is still accessible. Sliding doors are blocking the two entry ports into the deck. It's possible to access this deck via the emergency airlocks.

===== Deck 8 (Habitation)

Same layout as Deck 5. Life support is running, so the deck may be accessed. In the stem chamber, there is tape over the two entry ports into the deck. There's a wall-mounted e-poster that reads "Stay out: Cleaning in progress." Someone has written "Say no to smelly passengers" in a marker pen at the bottom of the poster.

===== Deck 9 (Forward Cap)

The vehicle's cargo hold modules are clamped between Deck 9 and Deck 20. This forward cap contains equipment that moves the two cargo modules apart. Either the two cargo modules split apart to create an opening where cargo can be removed, or the modules are ejected so that they can be docked for 
This deck has the same layout as Deck 5. Life support is running, so the deck may be accessed. There's no sign of activity.

The stem Access section is surrounded by a ring corridor leading to the utility rooms and the long stores. Additionally, an airlock in the ceiling leads to the stem external ladder/rail system, which runs the entire stem length, leading up to a corresponding airlock at the top end of the stem. Should the stem access system become impassable, this system can be used to get people about.                                                                                                                                                                          
*(A)* *Utility room/workshop* - The two largest rooms on the deck are designed to be multifunctional. On the Golden Goose, the top A has been turned into a gymnasium with various floor-mounted exercise machines. In the corners of the room are large cases containing machining tools and 3D printers. The workshop tools are set out in the lower (A) room, ready to fabricate or repair machinery.

*(B)* *Stores* - Two rooms contain storage bins filled with parts and materials.


==== Cargo Modules

The Golden Goose carries two cargo modules, each of these modules connect to the stem to form a cylinder. The two modules separate and move away from the stem to allow access to the roller-shuttered ports for loading and unloading. While most decks on the Golden Goose are a standard three metres high, the cargo decks are nine metres, floor to ceiling. This is high enough to carry a wide ranger of shipping container types or large items such as vehicles or plant machinery. 

image:https://db3pap001files.storage.live.com/y4mYbX0JGKdreXlloTJGeIB_szuiZlVQz5Vx8SmFO8qYBmAeyePTVKV-bZdjAcbltpAF1TTkDO1HbNeABf3Y0Z5gZRRzJoamNpgPCkNHy4_L9rjytyFGqD9pu4g77WjVOrAeJKsZUvxvkGnQQALzM4p3MJua4GEyiRz5zJpxMeGi5OmUsOxHdX0BSZV1RPvsr5F?width=1024&height=704&cropmode=none[image]

===== Deck 10

image:https://db3pap001files.storage.live.com/y4mVOIei7qgPctmVuR5d121HVhL9uIQP0orXBYT1UIT6FKi_mNiMRlbW9qowJ2heh4iuwgv3r9yG2mtmUwAjszEUYTudU3H914G1sgpRq0isBvmUKbDI_b0ouTsE0gekSb47_zkD9oWnNsl5jzE8bNJNgtLwPDNNyytY6GsacYouJT4lgY1qqBZnBRc7WXek_pe?width=724&height=1024&cropmode=none[image]

*(A)* *Stem Access System* - This area is consistent all the way along the length of the transporter. Note that everything beyond the hatch doors in A are part of either of the two cargo modules. 

*(B)* *Clamp room* - When the cargo containers separate from the transport, this space opens out to vacuum, as the outer wall of B is actually part of the wall of the cargo container. The wall-mounted equipment, part of the clamp machinery, is all vacuum hardened and certified for space operations.

*(+C+)* *Starboard Hold* - Large cargo space filled with 3m x 12m shipping containers. There are ladder tubes on the other walls that lead just between the cargo decks.

*(D)* *Marshalling Area* - This part of the cargo decks has a crane system for moving shipping containers between decks. There's a 15m x 18m opening between decks. This opening has a sliding door that can isolate each deck from the rest. When the hatch is open on all nine decks, there's a nearly 200m drop.

===== Deck 11

This deck has the same layout as Deck 10. Life support is running so the deck may be accessed. The floor and ceiling hatches in the (D) areas are all open. There's no sign of activity.

===== Deck 12

This deck has the same layout as Deck 10. Life support is running so the deck may be accessed. The ceiling hatches (leading to deck 11) are open but the floor hatches (leading to Deck 13) are both closed. There's no sign of activity.

===== Deck 13

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 14

This deck has the same layout as Deck 10, although there is noticably more superstructure on the floor, indicating that this is the centre of the module. Life support is running so the deck may be accessed. The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 15

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 16

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 17

This deck has exactly the same layout as Deck 10. Life support is running so the deck may be accessed.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

===== Deck 18

This deck has exactly the same layout as Deck 10. The hatches are locked. It looks like fault in the air pumps is caused the pressure in the chamber to drop considerably. The hatches lock to prevent an decompression event.  The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. If the PCs want to get access to the cargo decks, they can depressure it, then enter wearing a vac suit. There's nothing special here.

===== Deck 19

This deck has exactly the same layout as Deck 10, although there are no floor hatches. Life support is running so the deck may be accessed. The floor and ceiling hatches in the (D) areas are all closed. There's no sign of activity. 

image:https://db3pap001files.storage.live.com/y4mWvdRW0WS76GKcAj16uen9fYrd0NK80GXJ2GNSnGbClxNn_unyEcHUIxiEXWJsfRMe3094BiOb1pyfKDwbHT0bZlr7NxYV9rmU_YSdjzu5tg7Pd5mdwuKAdDNsQGY6NWH48hnkihriDazI4nbRpXe8Nrsu9MmfqfvIw7h13H5Xe6E4R4dK-tYu7Vm5S3oC40A?width=724&height=1024&cropmode=none[image]

===== Deck 20 (End Cap)

This is the reverse of deck 9. The clamping machinary connect to the bottom of the cargo containers. There's also no stem airlock system as from this deck, the stem integrates into the rear sections.

===== Deck 21 (Engineering Control)

image:https://db3pap001files.storage.live.com/y4m4U2137eC1IdHbDkV4c97hJDjq09kmNicMI45e7aRQC6pj5YI_P_a-fkUg1vX80W-fXB3hKiunF7ahanb0U7JZIVCBg5VY7xf_Mw5NgBtH97jL3V442lkNwmFAeY_Ii_yIYCfuvH_KbwEPuB97f6FdsDUgcfHW9bhLY50WvsZDwBilK7faxPMZX-Zq2NK_pWA?width=724&height=1024&cropmode=none[image]

This small deck is the contains primary control for the entire transporter. In the locked-down state, all control over the ship is held here. The control room forms a ring around the stem, with a single antechamber. T-12 guards this room and only leaves when it observes that nobody on the ship is approaching the room.

===== Deck 22 (Power Plant)

The Fusion deck contains three fusion power plants in a large changer that is 9m high. However, crew access is limited to a control room on a balcony halfway up the chamber. The control room is the standard 3m in height. There are hatches at both ends of the room that lead onto a walkway with a railing. The white area in the middle of the deck is open space, rising 3m above the deck and dropping 3m below. When the vehicle is not accelerating, it's possible to move around this chamber.

The Power system is mostly autonomous. Every twelve hours, the off-line powerplant starts up. Once confirmed that it is running correctly, one of the running powerplants shuts down, undergoes a purge, and becomes the new off-line powerplant. This operation happens automatically, even in lockdown.

===== Deck 23 (Drive Deck)

The drive deck is a series of access spaces and walkways inside the giant thruster system. Everything is heavily engineered and reinforced. Countless cable rails and piping go in every direction. On one side of the deck is an Emergency airlock. There's no EVA marshaling area. The purpose of the airlock is to provide entry from outside, should the stem access become blocked.

=== Chapter Three - Fight the Power

This chapter deals with how the PCs conclude the mini-adventure. The most pressing objective deals with taking control of Deck 21 (Engineering Control).

The following strategies are available, although the PCs should be allowed to develop their own plan. As GM, you will need to assess to decide if it can work.

* *Ripley maneuver:* Lure T-12 to an airlock and flush it out into space. This only works if the PCs lock down all airlocks as T-12 is equipped with mini-thrusters and will otherwise work its way to another airlock and re-enter.

* *Lock-up:* Lure T-12 into a room that can be locked. Doesn't work for long as T-12 is equipped with a blow-torch, so it can cut itself through any wall that isn't the outer hull or any hatch that isn't a surface airlock.

* *Flytrap:* Lure T-12 into an improvised trap using MBT-40 bonding tape. Tricky, but at the risk of some bruising, this works if all the PCs work together. They'll need to be quick, though, as T-12 will run away if he can work out what they are trying to do.

* *Firmware Update:* Take the firmware update cartridge from T-12's storage box on Deck 10 (Cargo) to Deck 21 (Engineering Control) and initiate a firmware update. This actually takes quite a long time. First, the PC's profiles must be uploaded into the main computer, then uploaded with the firmware. The firmware update forces a 3-second shutdown but providing the PCs profile information is included, it will stop treating them as intruders. They will be able to command T-12 to stand down. 


*Down with Lock-down* +

The Engineering Control room has heavy-duty panels that carry multi-function displays (MFDs) that may be switched to control almost anything on the Golden Goose. The most urgent action the PCs need to take is to remove the lockdown. This is handled by a Difficult 8+ Computing roll. A critical failure (unmodified 2) will result in the lockdown becoming permanent. If the character performing the task also has piloting or engineering skill, they get a +2, as they'll have training in handling vehicle lockdowns. 

The moment that the lockdown is removed, klaxons will sound. A woman's voice will sound out. "Warning. Emergency Maneuver in 3 minutes. Please strap into a g-force rated seat." After three minutes, the ship will perform a rapid spin to place the thrusters in the direction of travel. The thrusters will ignite, and the vehicle will slowly build up to 0.9g of acceleration. From this point on, everyone on the Golden Goose now experiences simulated gravity.  

*Firmware upgrade* +

If the PC plan to stop T-12 by forcing it to undergo a firmware update, this is where it has to happen. The top-centre most console that sits in a cut in the stem is the main computer terminal. Its controls are isolated and can't be accessed from anywhere else. To complete a firmware update requires a difficult (8+) Computing skill roll. The task takes 10 minutes. If the PCs try to complete the upgrade in 5 minutes, it becomes Very Difficult (10+). However, if the PCs slow down and take their time, the task becomes routine (6+).

The tricky part is keeping T-12 from stopping the action. Suppose the PCs have drawn T-12 away with a distraction. In that case, it will immediately know that the central computer has been accessed and will attempt to withdraw and retake control of the Engineering Control Deck. 


=== End Credits

*Location: Unknown*
____
*Executive:* Developing Trajan under a cover program appears to have saved the project.

* Off-screen voice:* Yes.

*Executive:* In fact, this incident has provided a great deal of useful data. A single unit disabled and captured a large transport. Operating under the fake Anti-piracy AI. Ironic that the unit turned out to be an effective pirate.

* Off-screen voice:* We're not building robot pirates. Trajan is an army. 

*Executive:* In that case, maybe we should engineer an incident that field tests Trajan in force.

* Off-screen voice:* Yes. {pause} When we're ready.
____


=== Appendix

==== Trajan-12-x 

Trajan-12 (T-12) is a prototype for a highly sophisticated security robot, developed by Trajan Industries, a high technology research and development company. 

Prototype anti-piracy droid. 


==== NPCs

[cols="400px,500px"]
|===
>a| 
image:https://db3pap001files.storage.live.com/y4md_EVqFNHcMyQHjCDHQjnrPMFtAL6e536uuKaWa3wlI_7oEbi2BN751F_QlvS7DZqrFligafrNoxHxIKkOwLJ38oUwB75CBCnpGbokD6fzLJCvOv6ZhXC4M6Gxjca2wg473uwMZTIJqlQ96v9xxWPYmgfB2QlXkbsUVNEXc6PhVgAH5NipfRO2BN1lcslMkb_?width=658&height=660&cropmode=none[image] 
>a|   
*Almona Wash (Captain)* +
*UPP:* 479AA6  + 
*Age:33* +
*Description:* +
Almona is a tall, slender, pale-skinned woman with long black hair. She is dressed in a pale yellow jumpsuit. At 33, she's young for captaincy, but her no-nonsense approach to life makes her a good fit for the role. She has the respect of her crew because she is extremely loyal and the admiration of her peers because of her high competency. Almona's worst habit is trying to own every problem. It makes her seem over serious. Ross McAlpine is the one person who can lift the weight on her shoulders with a few words.
|===


[cols="400px,500px"]
|===
>a| 
image:https://db3pap001files.storage.live.com/y4mptzZeon9smR6TS_Sa9JrU7at1eLqN8P3rFqIg-DqNzg3XfLYS4un9_Zooxmeaq6u_xL24_EXg5bn0v6y37XTKz4Mk8Nzq2s5eWw3UHU8-4Y2RJyWUkX6XazOyluGdaSPPY0rO7lkgukgq2CKLA5gPjaByJetLux6C1XARIcENmK3Mq0jieB6ABlII3zlNr-k?width=658&height=660&cropmode=none[image] 
>a|   
*Ross McAlphine (Engineer)* +
*UPP:* 775888  + 
*Age:40* +
*Description:* +
The chief engineer of the ITV Golden Goose. Ross is a muscular man with red hair and a broad smile. He married Almona two years ago, although Almona says she won't take his name until they retire and start a family. Ross is the unflappable sort whose mere presence can calm a high-stress situation. His worst habit is whistling tunes that get stuck in your head. Ross speaks with a slight Scottish accent, although he's never actually set foot on Earth, never mind Scotland.
|===

[cols="400px,500px"]
|===
>a| 
image:https://db3pap001files.storage.live.com/y4mVdkleTEfs4XUY4Jy59yTmCYW5BsulRTtvtbM8zJe2RMcXO-IgFz2oxQsLFM21MXK4z-S_K1V7NmFLgbGpXQfEWOsq1DPDntjcoqY4Kl1LntMRlokLDqqWmkEf7B32FfLayz3qwLV4sBpX0Ux9je95uNNJ4tNHFAfWWROatx84KUNxbAA4556NsAIOLCutC8Y?width=660&height=622&cropmode=none[image]
>a|    
*Lars Anderson (Maintanence)* +
*UPP:* A5B764  + 
*Age:45* +
*Description:* +
Lars is a brutish-looking man who looms over most other people. However, it soon becomes clear that he is a sweet-natured giant whose tendency for jokes and tomfoolery frequently gets him into hot water with Captain Wash. Always joking, Lars is difficult to take seriously. Still, when matters become serious, his willingness to take personal risks for others makes him a popular member of the crew. Lars was born on Earth in a bunker community 30km outside of Helsinki, although his family moved to the Orbitals and then to Luna.
|===

[cols="400px,500px"]
|===
>a| 
image:https://db3pap001files.storage.live.com/y4mNH0L87ehjOrt57hjUYDu0OJCdtWb3pz5hBPMmmBvyDKpWGT4GuGxbClLLUBg26Dbl8Hx-ZM_L9MuOU740pfIzMI3ltyJKx7OujF-8-O-gkvSF4bRrjsgEwFnyk6ocDfjf2FqXiM_jYMCKeL_61GR4EzhgjaMq9phFEUs5VefO0XtPe7Fk70X5rJkk2fzn5Sm?width=587&height=660&cropmode=none[image]
>a|    
*Tony Pendula (Security/Cargo Handler)* +
*UPP:* 676877  + 
*Age:47* +
*Description:* +
Tony is a short, light-framed man of British-Greek ancestry, although he is actually Martian. Tony is a cheerful but laconic man whose small stature leads him to be overlooked. He tends to skulk at the back of any group. He takes his duties seriously, and while Tony and Lars are good friends, most of the time they spend together on duty tends to turn into banter.
|===

[cols="400px,500px"]
|===
>a| 
image:https://db3pap001files.storage.live.com/y4mx53vvBnYay65ln3axR549QpWuRbc5jHNbCjZv8VwoiYieNoWbfcPOTNPLVY7u8aqJHXT6OG7_zUNMM2GfDw_D9VwT1RSMvJvhO3GXB4DrqEFca2MmFWAb5wE_IEdLnqFH5cmkuKahu-P4GI6HBG012LU5pmgSxBIvGrQ4o9bibsgCYNBSc-zzLoq_2-hTb4e?width=658&height=660&cropmode=none[image]
>a|    
*Simone Acosta (Computer/Systems Engineer) +
*UPP:* A69BB8  + 
*Age:42* +
*Description:* +
Nigerian-Luna woman in her early 40s, Simone is even taller than Almona but has a more muscular frame that gives surprising physical strength. Simone is competent but does not suffer fools gladly. She remains aloof in the company of strangers or people that she doesn't respect. She's ambitious and wants her own captaincy but recognises that Almona has leadership qualities that she doesn't have. Simone would never question an order, even if she disagreed with it. However, in her specialist field, she's the boss.
|===



==== Anya Fillipova (Maintanence)  

Anya is a Russian-Luna national in her early 30s. She's tall, athletic, and wears her long brown hair in a ponytail or under a cap.  She's part of Lars Anderson's maintenance team. Considered by the rest of the crew to be a loner, Anya is one of those people who just can't settle anywhere. She's happy enough working on the Golden Goose, but she has ambitions to return to Luna and set up as an independent maintenance contractor.
