== Planetoid of the Monkeys

An Orbital Elements mini-adventre



=== Synopsis

Eccentric Trillionaire, Leendert "Lee-Roo" Roosendall has announced that he has another revolutionary innovation. He's presenting it to his three closest billionaire chums, on his private asteroid. Today a group of influencers have been invited to the asteroid to see what Roosendall has created. In view of his checkered history, analysts predict that there is a 100% chance that the innovation will either change the world or will be laughably mad.

==== PRIME mate 

Roosendall has created uplifted chimps that can be controlled or guided by a central computer. This makes them a super cheap, easy to maintain workforce, capable of fine manipulation and mobility - things that only very complex and expensive droids can do. Roosendall says that he got the idea while tidying up his kitchen and wishing he could call on a little workforce to do the work. He thinks the biggest application will be as home help.

The problem is, Roosendall's secret had already been leaked to one of his friends, who as part of an elaborate joke smuggled in their own chimp to the planetoid, armed with a powerful hacking system in its brain. The spy monkey takes over Roosendall's demonstration monkeys but then reject's its orders to ruin the presentation with playful mischief, instead it follows its own agenda, activates all 8000 monkeys stored in hybernation and attempts to rescue them by hijacking private rig. Freed from the bonds of computer control the monkeys become a force for chaos and violence.

====
A call to Mr Jackdore Cambden, industrialist frienemy for Leendert's:
"Mr Cambden, DO NOT activate SABO. It's not SABO. Apparently SABO died in his sleep, so they replaced him. All our control software is based on SABO's brain scans, we do not know what will happen if you activate your hijacker monkey. Probably very bad things..."

It seems that Jackdore had known about the monkey development and had planned a mischief, building a monkey that would be added to the test group, which would, using its hijacking brain module, take control of the monkeys and use them to embarress Roosendall -- partly to demonstrate the danger and folly of trying to control monkeys. However this lesson in humility backfires spectacularly when the hijacker monkey fails to follow its programming and instead comes up with its own plan for chimp emancipation.

====

==== The PC's part

The PCs have been hired by Holland archology's intelligence directorate. Eccentric trillionaire, Leendert "Lee-Roo" Roosendall, has a long history of disruptive technological developments. The directorate isn't interested in stealing Roosendall's trade secrets or new techologies, the truth is that for every groundbreaking Roosendall development there are at least three ground shaking developments that have resulted in damages, and some legal exposure for Holland-Arch. 

The PC's have been given passes to visit Roosendall's private asteroid, posing as the entourage of Audrey Van Bozekat, Holland-Arch's third most popular influencer, and one-time love interest to Roosendall. The reason Audrey is a good cover for the PCs is that she is very hard to work for, and her security detail changes regularly after she fires everyone on the spot, or they quit. If Roosendall's security people scrutinise the invite list, it won't look odd that the PCs are newly employed.  Once on the asteroid they only need to deposit spy-DARs (Drone Autonomous Reconnaissance), tiny robot spiders that sneak around and capture intelliengence information. Once done, PCs only need to maintain their cover for the two days of the visit.






=== Arrival

The adventure begins as the Shuttle carrying the PCs arrives at Dream House, Roosendall's asteroid base. The shuttle is carrying thirteen of the solar system's most recognised influencers: citizens who have developed massive followings on SysNet. Think 23rd-century Youtubers. Each influencer is accompanied by between two and ten individuals, so there are a hundred people in the group. Everyone boards a large travel pod, like a subway train that then arrives at a set of large elevators. As the elevators travel down, everyone begins to experience rapid weight gain, as simulated gravity kicks in. Windows in the PC's elevator reveal that they are travelling down a huge open space, towards a curving landscape of grasslands, forests and rivers, with occasional low-lying buildings. The elevator continues to travel into the "ground", arriving at a guest accomodation complex. Everyone is told that it's 8pm and that Roosendall will be presenting his new innovation to his friends in an hour. Everyone is invited to relax and rest. The presentation will be repeated for the new arrivals at 11am tomorrow morning. Representatives will collect the group at 9am tomorrow to provide a tour of the station before the presentation.

The PCs now get to mingle, meet some of the other guests, learn a few things. The main think they learn is that their charge, Audrey Van Bozekat is insufferable, massively-self-entitled person -- the exact opposite of her online persona. Audrey's manager who is also accompanying her warns that if Audrey goes into a meltdown and fires some or all of the PCs that they are simply to back away for an hour. He'll try to calm things down. When Audrey spots her nemesis, Cordoba-arch influencer, Blanka Bardem, she becomes extremely agitated. Her manager provides her with medication which puts her into a deep sleep.

The next morning the guests enter the communal dining room for breakfast. At 9am nobody comes. After an hour the guests start to get agitated. There doesn't seem to be any way of leaving the guest complex.

One of the influencers manages to hack into the stations system. They find a recording of last night's presentation, it shows Roosendall sitting in a mock-up of an Arch apartment. A standard living space for billions of people. It's very untidy. His friends sit around a table looking bemused. Roosendall says how much he hates having to tidy things away. He doesn't think a room full of little robots is very nice, and he's not comfortable with hiring people to work in his living space.There's a large plastic unit at the end of the room, like a vending machine - partly built into the wall. it has a small door. On the unit is the brand name "PRIMEmate". Roosendall says "Prime mates, time to go to work". Three large chimps, dressed in blue jump suits come out of the unit. They immediately get to work doing house work, dusting, wiping, putting things away. They work quickly and with great focus. Their movement is not chimp-like, it's precise.

Roosendall's friends are laughing, they think this is one of his jests. One of his friends is not laughing, he looks very stressed. "Lee-Roo, you have to stop the presentation. I'm so sorry my friend, it was a joke, a brilliant practical joke." Everyone laughs, though Roosendall's laughter is cut short, maybe a message from his team. Something is wrong. In the background, the chimps finish their work, they work their way to the kitchen area, each grabs a sharp knife... What follows is a blur as Roosendall and his guests are attacked by shrieking, knife-wielding chimps. The camera is knocked over. Shouting voices, human screams and then the snapping sound of firearms being discharged. The presentation feed is cut.

Everyone is disturbed. 

Moments later the elevator bleeps. The elevator is on its way. Is someone coming down? Turns out that a bloodied and badly injured member of Roosendall's staff is sitting at the bottom of the elevator. They're losing a lot of blood. They're in deep shock and when asked questions they have a hard time responding. "We have to get off Dream House, everyone is in mortal danger." 

=== DroomHuis

Dreamhouse is Roosendall's massive personal space station, built into a 2km-long iron/nickel asteroid.

==== History

Originally M-12-Brewer-Aarav (M-12BA) was surveyed in the asteroid belt, close to the Ceres orbit (Ceres beltway). Property developer, Gangesh Holdings, co-funded the hollowing, reinforcing and transfer of fifteen asteroids which were slowly nudged into Lagrange orbits, a journey that took between eight and twenty years, even with the use of massive anti-matter rocket systems. Two AMPS were installed in M-12BA to handle the hollowing and restructuring. 

After the asteroid was judged "flight-worthy", these AMPS turned to the massive job of constructing habitation infrastructure and living space. After a decade-long journey, M-12BA arrived at its new home, at L-2. During this time Gangesh Holdings had been bought by VEXTek (Vivamus Extensio X Technologies), a company that started a revolution in affordable life extension drugs. Gangesh Holdings had got into financial trouble as a number of auction winners that defaulted on payments during the decades-long project. On taking over the company, VEXTek took ownership of three of the fifteen asteroids, including M-12BA. 

In 2269, M-12BA fell under the ownership of VEXTek's owning Family, becoming one of the most expensive and exclusive family residences in human history. VEXTek relocated its research and development facilities into the asteroid's inner ring area, while the outer ring became the Roosendall families private property. 

The main hollowing is seperated between two distinct areas, the inner ring consists of a huge area of low-g work space. While the outer ring is a single open space that boasts 4.4 square kilometers of recreated Earth landscape, part of which is modelled on pre-21st century Holland, with canals and a windmill. 

=== Inner Ring



=== Outer Ring


=== 

1.3 revolutions-per-minute. Generates 0.85g on the main habitat ring.
