== Travel Times

Most space vehicles that are performing a orbital transit travel at a constant 1g, providing simulated gravity for those onboard. Some ships are capable of much higher impulse, but this is not sustainable due to crew comfort. Combat vessels use higher maximum acceleration to get into a favourable position more quickly.




.An example table
[options="header,footer"]
|=======================
|Journey from Earth|Duration -closest  | -farthest    
|Earth to  Luna: |3h |3h
|Venus: |1d 11h | 2d 22h
|Mercury:| 2d | 4d
|Mars: |1d 21h |3d 18h
|Ceres: |2d 10h | 4d 20h
|Domus: |2d 25h | 5d 2h
|Jupiter: |5d 16h | 12d 8h
|Saturn: |8d 2h | 14d 4h
|Uranus: |11d 20h | 17d 20h
|Neptune: |15d 8h | 21s  8h
|Pluto-Charon: |15d 7h | 21d 3h
|Keipers: |19d 5h | 19d 5h
|=======================

Duration is for 1g constant acceleration, then turning around and decelerating through the second half.

Space vehicles intended to operate only in a single orbital don't require more than a day's fuel capacity, while long-range vehicles might carry nearly a month of fuel. Most space vehicles are designed for travelling between the inner planets and maybe as far as Jupiter, where most vehicles refuel. A duration of 10 days is common.
