
image:https://dub01pap003files.storage.live.com/y4mrzpdOZBJErW6feztYtcYgcLwb_ZO-Wy83H3uVUmmpmA4g_YLwVGWLPFf_PIPbHPmXC7zP3XO2QLUeHuKMIiXHY-BaQgHJlTkf5wzVaqh8cJkwA8w_BJgnNwBb9qnbqVu3AG17OpHJaXjvMj_KbGoSseFoL3KC5TSnumr36Z5LbrB_Uq_L2WZI6XqSdnx8Zvg?width=1024&height=505&cropmode=none[Cover]

[quote]
 Giant steps are what you take +
 Walking on the moon +
 I hope my leg don't break +
 Walking on the moon +
 We could walk forever +
 Walking on the moon +
 We could be together +
 Walking on, walking on the moon +
 - 20th Century Police Mantra

== Introduction

A one-shot adventure for Orbital Elements Science Fiction Role-Playing Game.

*Setting:*  Mare Imbrium (Sea of Rain) basin. 

*Solarpedia Extract:* Mare Imbrium is a vast lava plain within the Imbrium crator basin, near Luna's northern polar region. It was the site of early Helium-3 mining regions, and one of the most contested. During the second Luna war the region became criss-crossed by a defensive lines, creating pockets of "no man's land", filled with smart mines, hidden missile launchers and killer drones. Today these areas are avoided, except by scavengers and pirates.


== Synopsis

In this one-shot adventure, the PCs are the crew of a small transport rig that carries passengers and cargo between the countless Luna settlements. The adventure begins part way through a journey from Nuvo Sputnika to Copernicus Arc. The transport is hit by a ground-based weapon, forcing a crash landing, right in the middle of a no man's land region that is littered with automated weapon systems left over from the second Luna War. The place is covered in smart jammers that make radio communication from the ground all but impossible, so there's no way to call for help. The PCs must try to lead their passengers to safety, walking across a trackless waste, filled with unseen dangers.

However, there's more going on...

=== What's going on?

One of the passengers, a mysterious middle-aged man called Jack Deringer told the PCs that he is carrying very sensitive research data. He fears that hostiles may try to intercept him during the journey. He offers to pay ten times his fare to fly to Copernicus "below the radar" and with their IFF beacon turned off. The PCs happily accepted because flying low, slow and quiet is safer. However, all is not what it seems. Jack Deringer's real name is Percy Brennan. He isn't an agent carrying secret research data, he's a retired farmer who now lives out the fantasy of being a secret agent. Locked in his secure case are some snacks, a couple of adventure sims and emergency toiletries.

At Nuvo Sputnika, Percy approached several transport services, specifically asking if they could provide an off-the-grid transit. This request was overheard by Sam Modey, a pirate working at Nuvo Sputnika's port who looks for high value targets for ambush. She assumes that Percy is carrying something of very high value, of such high value that she not only did she target Percy for ambush, she is risking travelling on the transporter herself, signing up as a passenger using a stolen identify (Zena Platts). Shortly after leaving Nuvo Sputnika, Sam activated a beacon in her dufflebag, sending the transport's position to her a pirate team. The beacon allows the pirates to quickly travel to one of several hidden weapon systems along the PC's route. When the PC's transport flies close, it is shot twice by a railgun emplacement. The shots are carefully targetted, so that the transporter is forced to make a hard landing, but is not so badly damaged that the transporter can't make a survivable landing. 

=== Journey facts

While it's possible to do the journey using a "hopper" that actually launches into space then comes back down anywhere on the moon in less than 20-minutes, it's super expensive to get the transit permits. Luna orbit is now a crowded place, and there are restructions due to the two space elevators that create exclusion zones on the equator. The journey of about 1000km is a little longer than normal for a small rig, but the rig will complete the journey in about 5-hours, cruising at 250 Kph, about 1000m above the surface.

The subject of the scenario is how the player characters deal with the crash and the dangers of finding a place to shelter. The pirate angle becomes apparent when, on finding a missing launch facility they identify that someone has put a beacon on their rig. Almost certainly one of the passengers as it would need to be activated some time after leaving polar traffic control.

The adventure is broken down into the following episodes:

=== Episode One: Moon crash

The PCs are introduced to their current situation. They don't get much time to prepare before their vehicle is hit by a small missile. Their rig immediately goes down. The PC piloting the vehicle gets to roll for how severe the crash is, and where exactly they land. On landing, it's clear that their vehicle is wrecked, and in danger of being shot at by any number of autonomous drones or hidden launchers. The PCs must decide how long they risk stripping equipment from the vehicle before a likely strike arrives. Eventually another missile is launched, resulting in the crashed vehicle being peppered by a cloud of penetrators. Potentially lethal for anyone still in the vehicle. 

The episode ends with the PCs deciding on a course of action. They might wait near the vehicle - not a good idea. They might head out and try to find some kind of refuge from where they can wait out until a search party arrives. Normally a personal communicator works fine, but the no mans land regions are usually covered by heavy jamming and interference. 

* *Player handout 1:* Shuttle manifest
* *Player handout 2:* Shuttle sheet (inc deck plans).
* *Player handout 3:* Regional map
* *Player handout 4:* Readout-1

=== Episode Two: Across the bright face

The PCs have a map of the region. They must decide where to walk. They're on foot and have limited air and water. Enough for 48 hours. As they travel across the lunar no man's land they roll on an encounter table each hour of travel. They may encounter discarded equipment, derelict shacks, killer drones or even pirates.

At some point the players will roll 6 on the facilities table, at which point they find Missile Silo 792, which takes them to Episode 3.


=== Episode Three: Oasis

Eventually, the PCs find the entrance to some kind of underground base. It's a hidden missile silo, apparantly intact and operational - the missiles are gone, but someone has rigged a railgun into the missile launcher. It's the strongest source of local jamming and although there's a functional communication system but it is locked down with encryption, the jammer itself could be modified to send out an S.O.S. signal. The PCs can spend time exploring the base, learning a little about people who once mannned the station. At some point a group of pirates rigged the silo to launch missiles at low flying or ground vehicles.

If they manage to modify the jammer to send a signal, the first people to turn up won't be a rescue party, it will be a contingent of pirates wanting to know who is messing with their missile silo. A fight will ensue.

This episode is part puzzle, part who-done-it. Sam/Zena is a member of the pirate gang that has wired this this station up as part of a network of weapon systems that it uses to bring down low-flying traffic. As such, Sam's arrival at the station unlocks most of the security. The station's computer will say that station security is now disabled, now that authorized personnel have arrived. At some point the PCs will realise that this actually means that someone in the group is part of whichever gang set the site up. 

Sam will send a message through the encrypted hardline saying that she needs a team sending out to the site to extract her and the booty.


=== Episode Four: Moon Siege

An alarm triggers. Two vehicles are driving towards the bunker. They're just over an hour away. Remote sensors indicate the vehicles are medium-sized armoured transporters. They look like pirates. The PCs have about an hour to prepare for an attack on the bunker. During their journey in Episode 2, several useful items were encountered that might help in the bunker's defense. A ground of combat drones. Small arms from a drop pod. The PCs could hack the bunker's railgun

=== Episode Four: Moon Cavalry

If the PCs lose the fight, a rescue party will arrive just in time to save them. If the PCs hold off the pirates long enough, the rescue party drives away the pirates.

=== Epilogue

The PCs are taken to the nearest settlement where the local security force will debrief them. 


== Episode One: Moon crash

.*Player handout-1:* Travel Manifest
____
* Luna Excursion Rig LER-21, Registration L-XP32-J12P, in transit to Copernicus City
* Carrying light cargo and five passengers.
Passenger Manifest: +
*Jack Derenger*, carrying precious cargo in a suitcase. Declared prototype scematics. +
*Zeena Platts*, 20-year-old interior designer, leaving the polar regions after a number of jobs improving various communes. +
*Anjar Sing*, 40-year-old surveyor, heading for early retirement after a couple of big mineral finds. +
*Trix Montang*, nonbinary folk singer and performance artist, returning from a tour. +
*Freddy Happyness Cheaplove*, journalist from the Azania archology, doing a backpacking tour of Luna. 
____

.*Player handout-2:* Shuttle sheet

image:https://dub01pap003files.storage.live.com/y4mhNnDnw0tWXMXhWlBhT5z_X_WuH3zv5k_i8YIUA5MOyRFDWdkvmXnH0jCZkP4NuCcPfAC_DAW1gWQ_NoT6YuMhtGrbtB_OsAtQdXoy8Af8T7Cxp1wjDva1eH8hIounpM4LAwaMA9IZyTLrj-fHpiMjlPanP8NP-T5OPyxHeJVrLqT8VNW49AdnaTCXN3TuK47?width=724&height=1024&cropmode=none[Bantam1]

The KV-79 Bantam Deltica is a modern Luna transporers that features a novel two-stage arrangement. The top Lift-section provides flight-to-luna-orbit capabilites, while the truck section can conduct surface operations for upto a week. This arrangement allows a crew to quickly reach an isolated region by flight, then the lift section can repeatedly return to base for fuel and supplies, while the truck remains on site. Both sections can be operated remotely or even autonomously.

=== Key

1. *Forward Airlock* - This is only used when the Bantum docks with a suitable airlock in a dust-free area. There's no anti-dust system built into the airlock chamber. There's pull-down ladder for accessing the roof hatch.
2. *Command Deck* - This area contains consoles and crew positions for a pilot and a mission controller. From here both the lift and truck sections can be controlled. The controls for both sections are duplicated, so it's possible to drive from the lift command deck, and it's also possible to fly from the Truck's command consoles. Also, both sections can operate autonomously. For example, a crew could all occupy the lift-section, then remotely drive the truck somewhere. In the centre of the space is the main airlock that leads down to the  Truck section (area 9). The accessway is only usable when the two sections are connected.
3. *Central Bay* - The cramped central bay contains an airlock that connects the lift-section deck to the airlock at the mid-section of the truck. There's a toilet cubicle and vending machine in the space.
4. *Lift-section passenger area* - There are six oversized couches, suitable for passengers wearing vacc-suits. At rest, the couches face inwards, but under acceleration the chairs turn to face the direction of accerlation. There are large overhead lockers to carry luggage or equipment. The centre of the bay has webbing to hold down extra cargo.
5. *Engineering bay* - Contains a mini-workshop and stores. There's a hatch that leads down to the rear section of the truck (area 13). This accessway in only usable when the two sections are connected.
6. *Emergency airlock* - The outer opening of the airlock is a square hatch, not a door. It's not intended for use on the ground.
7. *Truck command cabin* - This area has crew positions for a driver and a systems engineer. The cabin opens out to the passenger bay. 
8. *Truck passenger bay* - This contains eight counches. At rest, the couches face inwards, but under acceleration the chairs turn to face the direction of accerlation. There are overhead monitors and consoles. At the top of each couch headrest is a bracket that holds a vacc-suit helmet. Some variants of the Bantam Deltica reconfigure this section into a cargo area, with a floor-based elevator.
9. *EVA area* - Equipment for setting up vacc suits for space or surface operations. A ladder leads up to the lift section (area 3). 
10. *Decontamination* - powerful jets and extraction equipment blast entrants to ensure they don't bring in too much dust. This area leads to the main side airlock. While in drive mode, the airlock is 2 metres above the ground. An easy jump on the moon but in parking mode the suspension system  lowers the airlock door by a metre and a steps fold out from beneath the airlock's extrusion.
11. *Galley* - Food and drink stores and a toilet/wash cubical.
12.  *Storage area* - Lockers for passenger luggage.
13. *Cargo bay* - contains 5 large lockers, large enough to walk in. They contain various equipment for surface operations. 

.*Player handout-3:* Regional map

image:https://dub01pap003files.storage.live.com/y4mrvzjoAn2TKqykoGkkbnYgYRFPVYcKIflpHaKf63mBy36BGjhKVeucW-byGEp9Jty4m67A_Spv63xZ2q3xoM9LahmpMqXPFNu8oD8pjD7JzkBazEjY_1Fp5vngIzq6pjucbYdnN9IdY_KwqJa5I3EjXxCdso1M5fEXa7VNRXScUHS_N7wx69rAbevQjGLBvZp?width=1024&height=754&cropmode=none[alt=Map1,width=1024,height=754]



.*Player Handout-4:* Readout-1
____
*GM:* The LH41 Bantum flies over the baked white desert of Mare Imbrium, about halfway through the journey and about twenty minutes out from the next refuel stop. You attend to your flight monitoring responsibilites. Behind you, passengers chat.

*Player1:* We're passing over a no-mans-land region. This is where some of the fiercest fighting of the second Luna war happened. In fact this area is considered very dangerous as there's still a lot of autonomous weapon systems laying around. We're inside the area of smart jammers so don't panic if you're unable to connect to LUNAnet.

*Jack Derenger:* On that note, I'd like to thank everyone for letting me adjust the flight plan to take us this low, slow and with our IFF disabled. I think it only fair that I now explain that I'm an intelligence operator carrying highly sensitive data for the Copornicus City goverment. I needed to fly "off the grid" because there are most certainly operators working for adversary nations who might try to grab the information.

*Anjar Sing:* That's alright Mr Derenger. In fact, this flight profile is much safer! In the event of a propulsion system failure, flying fast and high results in a 750% increase in mortality. 

*Zeena Platts:* [Dismissive tone] In the event of propulsion failure. What about Mr Derenger's adversaries? What do they do to our odds?

*Jack Derenger:* Ha ha, well there you go.

*Trix Montag:* Dick move, Derenger. Shoula told us the truth before we set off.

*Jack Derenger:* I'm sorry, Trix. It was not my intention to deceive anyone. As Anjar says, this is actually safer -- if slower and more expensive, and I've covered the extra cost, and some.

*Zeena Platts:* Whatever, man. If you think you're a target, slower might not be safer. And you should have warned the passengers of the fact.

*Freddy:* I have to warn you Mr Derenger, I'm an investigative reporter. Could I persuade you into giving me an interview, when we reach Copurnicus City?

*Jack Derenger:* I couldn't divulge anything about the operation, but Yes, on condition that you withold publication until after my retirement.

*Freddy:* [Giggles]

*GM:* There's a loud thud. Then a second. Then a third. The Bantum's engines have stopped and the everyone feels a steady downward acceleration. The command consoles light up with countless emergency symbols. An automated message plays out "Warning! Catastrophic engine failure. Automated recovery system enabled. Emergency burn in 3 seconds. Landing speed will be faster than is optimal. Please brace for impact....
____


== Episode Two: Across the bright face

The PC's group are making an effort to walk to any kind of shelter or settlement. They might formulate a plan amongst themselves, or just walk in a random direction. They have the regional map, with their approximate position marked on. The episode is managed by making an roll on the Encounter Table each hour the group spends travelling. Each time that a roll is made on one of the sub-tables (crash sites, ruins and facilities) then  add a cumulative +1 to the next roll on the table. For example, if you make three rolls in the ruins table, then the fourth roll will be D6+3. This makes it very unlikely for the group to run out of air before they find Oasis and move to episode three.

[width=50%]
|===========================
1D6 | *Encounter Table*
|1        | No encounter, rock, dust and the black sky.
|2        | Small surface debris. Roll on the *Debris Encounter Table*.
|3        | Small surface debris. Roll on the *Debris Encounter Table*. Add +1 to the roll.
|4        | Crash site. Roll on the *Crash Site Encounter Table*.
|5        | Small ruin. Roll on the *Ruin Encounter Table*.
|6        | Small facility. Roll on the *Facility Encounter Table*.
|===========================

[width=50%]
|===========================
1D6 | *Debris Encounter Table* 
|1        | Scattered rocks
|2        | A small crater, about 10m in diameter surounded by rock fragments.
|3        | A large crater, about 50m in diameter. + 
Walking through the crater requires some checks against dexterity. 6+ to avoid a fall. 
|4        | Signs of fighting. + 
Metal casings and fragments are scatered around. Maybe some discarded pieces of equipment
|5        | Signs of a battle. Equipment and some empty magazines scattered around. Pieces of space suit. No bodies remain but you definitely get a feeling that people met their end here. 
|6        | An intact lander sits on the edge of a small crater. It doesn't look have been stripped, but the PCs quickly identify that tiny bomblets covering the area. Any attempt to get to the lander will likely result in your death. However, if the PCs are creative they can liberate about CR3000 from the site.
|===========================


[width=50%]
|===========================
1D6 | *Crash Site Encounter Table*  [_Each time you make a roll on this table, add an additional +1 to each subsquent roll._]
|1        | Debris from a crash vehicle. Nothing remains except for burnt fragments.
|2        | A wreck of a small rig. Looks like it came down hard and exploded. Nothing of value remains.
|3        | The wreck of a large lander. It looks like it made a soft landing but then took fire on the ground and was therefore abandoned. Inside the wreck are intact pieces of equipment. Roll on D6 times on the *Basic Equipment Table*.
|4        | A group of four tracked drone tanks. Someone removed their battery packs. They're too big to carry, so even though they are valuable, the PCS can't benefit from them *yet*.
|5        | The wreck of a light combat rig. Came in hard. There are live bombs and missiles attached to its ordnance racks. There is a small risk that the bombs and missiles might detonate if the site is disturbed. If the PCs risk exploring the rig, they can make the ordnace safe, they find 1D6x10,00CR.
|6        | Small facility. Roll on the *Small Facility Encounter Table*.
|===========================

[width=50%]
|===========================
1D6 | *Small Ruin Encounter Table*  [_Each time you make a roll on this table, add an additional +1 to each subsquent roll._]
|1        | A survival shelter. A solitary emergency tent equipped with a small porta-loo sized airlock. The shelter is deflated. It looks like it was punctured by shrapnel. No bodies or equipment inside. Nothing of note.
|2        | A collection of six emergency shelters. The shelters are intact but there's nothing but litter, the remains of emergency provisions and some sunblasted artifacts.
|3        | A Cabin shelter, about the size of a caravan. It's been stripped of anything valuable, expect its oxygen supply which remains at 20% capacity. Enough for everyone in the party to reset their air capacity to 100%.
|4        | A small trench, about 20m long and 2m deep, with two dugout chambers. Both chambers are breached and filled with jagged metal. There's a body in a vacc-suit that looks to have suffered a catastrophic puncture. There's not much of value in the chambers. Random equipment from what looks to have been an observation nest.
|5        | A mooncrete platflorm, about 10m square and 1m high. There's an airlock in its sloped wall. On top of the platform are several fist sized holes. Their airlock is smalled open. A tunnel leads down 2m to a pile of rubble. It looks like a penetrator strike has collapsed the interior of whatever this was.
|6        | Small facility. Roll on the facilties table.
|===========================

[width=50%]
|===========================
1D6 | *Small Facility Encounter Table*  [_Each time you make a roll on this table, add an additional +1 to each subsquent roll._]
|1        | A small recharging station. A bank of solar arrays, about the size of an olypic swimming pool, attached to a charging bay. The facility looks to be about 150-years old. It's functional but only provides a trickle of power due to various failures. It's enough to fully recharge the group's suits in about an hour.
|2        | A small automated turret, about the size of a car. It tracks and engages the group but fortunately hasn't enough power for its laser to penetrate anyone's suit. A cable on the side of the unit has been disconnected. Reconnecting the capble will being a recharge of the laser which will start shooting 1D6 minutes after reconnection. It will then take a shot at a random target every three minutes, doing 3D6 damage.
|3        | A landing pad surrounded by large cargo canisters and equipment. There's various peices of equipment laying around. Roll 1D6 times on the *Random Equipment Table*.
|4        | A sloped ramp leads down to a bay door. The heavy door looks to open only on the inside. There are no other means of entry. There's no way in. The more time the PCs spend here, the more air they will waste.
|5        | A missile launch bunker. The launcher has risen out of a hole in the ground that looks to have a sliding cover sculptured to look like moon rock. It looks like missiles in the launcher exploded, causing catastrophic damage. Near the launcher are fist sized holes and a larger hole where the ceiling of an underground bunker has collapsed. It's possible to scramble down the slope and into the remains of the bunker. Everything is shattered and ruined, although there are two pistols, still stored in boxes. 
|6        | Oasis! Start Episode three.
|===========================

[width=50%]
|===========================
1D6 | *Random Equipment Table*
|1        | Supplies. Small oxygen tanks. Small Water tanks and some emergency equipment.
|2        | A case filled with first aid equipment.
|3        | A handheld scanner. It can detect manmade objects such as burried mines or hidden turrets at about 1000m. It has to run off a vaccsuit's internal battery and takes quite a lot of power. Ten seconds of operation takes 2 minutes of suit power.
|4        | A field repair kit. A large rucksack filled with tools and repair equipment. 
|5        | A body in a damanged vacc-suit, still holding a loaded pistol, along with two additional magazines on a belt.
|6        | An M81 Guass rifle. A powerful high-penetration rifle. It's operation but only has 1D6+1 rounds left.
|===========================

[width=50%]
|===========================
1D6 | *Fall Table*
|1        | No damage or injury
|2        | Minor damage, no immediate effect. 
|3        | Moderate damage. Radio fails for a few seconds intermittently
|4        | Minor danage to helmet. Another fall on the helmet is likely to cause a crack that may result in a leek or exposive fracture.
|5        | Tiny leak. The suit's remaining operating time is halved.
|6        | Catastrophic damage resulting in immediate suit failure. Other members of the party can perform two very difficult engineering rolls to put a temporary fix in place.
|===========================

== Episode Three: Oasis

.READOUT-2
____
*GM:* The lead person in the group suddenly feels a change to their feel of their footfall. Looking closely at the ground, it's immediately apparent that the dusty lunar rock is actually a molded metal plate.
____

If the PCs check out the area they notice a large circular rim, about 4m in diameter. There's no obvious way of moving the plate but a closer look at a nearby boulder reveals a manhole hidden in the boulder's shadow. A ladder leads down three meters to a small chamber with an airlock. The airlock will be locked from the inside but the moment Zena/Sam enters the chamber, her identity is detected and the airlock will unlock. It shouldn't be apparent at first. It will look like the door just unlocked.

image:https://dub01pap003files.storage.live.com/y4mVZchui5cdnW7BkCDhRgyx2a_l7AXl-H6m7mErydMBMqYhsj9_qLedIW3jSwlC8or6RNNNaKXYZvrQ9Gp94KG-CgEDa_SfXH61vTni-zhJeKV0rUZAFJ3ShuMZz9hHv5Rqm8QjV2Hil41byIhh5JVUBxmJPMx4CNBtv8_o6cPuhp5dFFiYB4GABxFL_E2KtWr?width=1200&height=675&cropmode=none[Cutaway]

The Silo 08-C1S "Oasis" was built more than a hundred years ago, when the region was still being fought over for access to Helium-3. The battles long since ended, but the battlefield has remained a dangerous place because it's covered in autonomous weapons. The danger is even greater then people realise. Pirate groups have set up ambush traps, where their attacks are mistaken for random mine or missile strikes. One such pirate gang has taken over and networked together a number of hidden weapon emplacements that can bring down flying vehicles or criple ground vehicles along a wide range of the no man's land.

Oasis is equipped with a pop-up missile launch system. However, the actual missile launcher is out of commission, so the pirate group have mounted a modern medium railgun on top of the launcher.

=== Key

The silo is located in a flat but boulder-strewn area. The personnel access tunnel is obscured by a large boulder that somewhat overhangs the tunnel entrance. A heavy-duty ladder runs from the surface to about 6m below, leading to a square chamber that looks to have been laser-cut out of luna rock with a smooth fuzed rock walls.
The room is completely bare, except for a heavy-duty airlock and a small screen.

image:https://dub01pap003files.storage.live.com/y4mV8bcU_eCg9CbqHL97StqEbtaoPub05nk1pAaJ-TGe-sfBX5jbALi2sL-HaTUAZ2Dykq15XZry01r-5FbyvMOrXVTrKyNlgPwIdN4jO5VIfO_46ppBlPkXPqFYFgoTEaz_zEKM0RPPAuhL4iAAKKTDjeafQz4u4wrvp6HwoFm47Q3SZSxQ4_uTfy6t8PLnlZH?width=1024&height=724&cropmode=none[MAP1]

The facility is locked-down and the airlock secured against entry. However, when Zena/Sam enters the chamber the airlock will automatically unlock.

*DECON:* The first room is equipped with high-pressure air jets an extraction system that removes lunar dust from all entrants. The system is automated and appears to be still working. On one wall is a large mirror window. There are dried blood splatters along the floor and what look like streak where bodies where pulled away.

____
*Anjar:* [SHOUTS] We're going to live, we're going to live.

Anjar does a little jig dance as air blasts remove dust from your space suits. He looks down at the floor and notices a mass of dried blood, splatters and streaks where bodies must have been dragged away.
____

*EVA GALLERY:* This room is filled with racks for supporting vaccsuits and equipment for going onto the surface. There are various vacc suit parts but no full suits. There is a system for filling air supply and water tanks. The PCs might take time to replemish their vacc suits.

*DOOR CONTROL:* The room is filled with heavy machinary and some control surfaces in the inner wall. It appears to control the opening of the large circular sliding door that the group encountered on the surface. schematics on the walls confirm that the station is a hidden surface to space missile site. The diagrams show a central cyclindrical chamber that goes down to a depth of about thirty metres. Four levels of Donut-shaped chambers ring the central cylinder. The group are currently standing in Level -1. 
If the PCs investigate the chamber they find that extra cabling and system cases have been wired up. Either to replace broken equippment, or more like to provide a kind of remote control for the operation of the door.

*ACCESS BAY:* [SOUTHERN] There's a northern and a southern access bay on each level. The room has plain white structural molding and heavy duty hatches. These hatches have no manual controls and require user authentication. It just happens that as soon as Sam Modey entered the site all the doors except those of the Security room unlocked. It won't be clear to the PCs that this is the case. At least not initially.

*STORAGE:* A storage space. The area is completely empty except for broken storage boxes. There's the trace of a bad smell in this area. The smell is strongest near a large hatch on the outer wall.

*STORE 1B:* This storage bunker is cut into the rock. If the large double-sized door hatch is opened, four body bags have been thrown against the far wall. The room smells putrid. The bodies belong to crew belonging to a competing pirate gang who died trying to defend the site from the current pirate gang.

*MAINTENANCE BAY:* The chamber contains repair benches and some printers for making replacement parts. There's a single operator console but it looks like someone smashed its screen with heavy tools.

*STORE 1A:* A duplicate of STORE 1B, except this one has a large elevator system at the back. The elevator still works and runs between all four levels. There are boxes of missile components. Only casings and basic systems. There are no warheads anywhere on the site.

*ACCESS BAY:* [NORTHERN] The access bay leads through to a second bay that is equipped with a small elevator. The elevator is functional and can be used to access any of the levels.

*SECURITY:* *The hatch into the security room can only be opened with a command keycard.* Even Sam can't access the room. The PCs can try to put together a laser cutter or they might search the bodies for a keycard, otherwise this room will remain out-of-bounds. _Getting access to the security room is the only way the PCs can get inside the *FIRE CONTROL CENTRE* on Level -3._

The security room is a self-contained accomodation for a security team. It has three work consoles, one monitors the station, another monitors the region surounding the site and the third looks to monitor the status of the site's crew. The screen looks to be faulty but watching it you can make out that twelve listed crew all have a killed in action (KIA) status, the last death was recorded to have happened 75 years ago.

From the security room it is possible to lock and unlock all areas of the site. You can monitor any room, and watch for activity nearby.

image:https://dub01pap003files.storage.live.com/y4mxXIn4rZmnH7dusCyDP8qjj5HQCfkmgPphyjJllJLTB3oQ2ZgzRKgJuV239jFvsvrCZQYSOAPg2u3L5CtdvLwlpUahjouPWQ7ZawqbHL-vBWkIGP0CxkXbUuvHb-9hzG0yBS31aZLh6Z3g2IGWc1yG4LDHBtNTwdDK6vZhoelrPXNjWHD4httN27XKZny0Bvv?width=1024&height=724&cropmode=none[MAP2]

*ACCESS BAYS:* [NORTHERN] The access bay separates a large storage area that takes up half the level. There are neatly stacked crates in the centre of the room that contain general supplies, replacement parts such as bulbs and electronics, as well as tools and equipment. There is a STORE 2A and a STORE 2B that correspond with those on the level above. 

*ORDNACE WORKSHOP:* This area takes up about half the level. It contains machinary for assembling missiles. There are tables and work benches that contain partly assembled missings but they look old. At the end of the room is a large heavy duty hatch labelled with "DANGER: WARHEAD STORAGE". The door ha status lights and environment readouts. The readouts indicate that the temperature inside is -60 degrees. If the hatch is openned the PC find that the room is completely stripped, except for a chair at the end of the chamber in which a dead man sits, frozen solid. It looks like he was beaten up.

image:https://dub01pap003files.storage.live.com/y4mOj4FDVQcUOMuqpwYCrNC5JOvQiTRGQo_MphEz6f_CJUzugUQoiiOeVQFiHjDVYvD0wdideLkcdf812znoMhPFeM1VEnTbUuGHRkxTdrvuGfXdG7Ih4DNRkEs8N5iWeQnRr_GorQr21Azu-jCbBZ1Mx3Gmr3CHtmLSdrFxYgHYYWu3onmmx-OSLPTCa-IeKcA?width=1024&height=724&cropmode=none[MAP3]

*ACCESS BAYS:* [NORTHERN] The access bay separates a utility room from a recreation room.

*REC ROOM:* This room contains VR suites, exercise equipment and a wall mounted entertainment screen. There look to be bullet holes across the screen which occasionally flickers to life then goes dark again. There are signs that a fight took place small amounts of blood and some shell casings.

*COMMON ROOM 1:* This area has purple walls and orange furnishings. It contains a large central table, stools and wall mounted "bunk tunnels". These are like "coffin hotels" that provide a bed and limited space for dressing. They are arranged four banks across each with a stack of two bunks, making for eight in total. To the side is a small toilet and shower room. There's a "MENS" symbol on the door. 

*COMMON ROOM 2:*

*COMMON ROOM 1:* This area contains is a large central table, stools and wall mounted "bunk tunnels". These are like "coffin hotels" that provide a bed and limited space for dressing. They are arranged four banks across each with a stack of two bunks, making for eight in total. To the side is a small toilet and shower room. There's a "WOMENS" symbol on the door. 

*GREEN ROOM:* This room is equipped with a wall-to-wall and ceiling screens, creating a good illusion of sitting in a terrestrial enviroment. There's a large collection of plant pots in the room but all the plans have withered away. This type of room is very common in small isolated outposts and stations. Allowing inhabitants to sit an enjoy bright simulatd sunlight, a breeze. It was found that these are important for long-term mental health. The screens have faded so it's hard to tell what's actually being projected but there's the sound of dirds playing.

*ACCESS BAYS:* [SOUTHERN] The access bay separates the GREEN ROOM from the TRAINING ROOM.

*TRAINING ROOM:* A large room devoted to various practice operations, such as gunnery control, damange control, maintanence. There are VR rigs and a large screen on the outer wall. 

*FIRE CONTROL CENTRE:* This chamber has been dug out of the rock and is equipped with an immensely strong hatch. It quickly becomes apparent that this door can't be openned manually. The PCs will need to find a way to open the door.

*UTILITY ROOM:* A storage area that contains a broad range of equipment equippment for various tasks. 

image:https://dub01pap003files.storage.live.com/y4mTKSI68m1BhDNydHY3Jokd5HEyM860IXNbvQBYUkC7q5E6jWCnPziM45Vph-e9IdIph__0y6tOrFniRV0yEcUYfBMb9LTCZG6ZDDSxr-PAztEskbXg68BbUPDA6uMXY9TcoHO_3rLf5eYBPNpzQR5RQt-s4GFR4jlTRrbCsCNVDxSj7EgvdU8_0oFDourGoRL?width=1024&height=724&cropmode=none[MAP4]


== Operating on Luna

Operating on Luna introduces the following challenges, that should factor into many of the actions that the PCs may wish to take:

* *Gravity:* You weigh about 16% of your mass. If you're not wearing a heavy vacc-suit then much care is required while walking or running as there's a serious danger of hitting your head when you take too big a step. 

* *Temperature:* Under the constant glare of the sun, the surface reaches 120 celsius Celsius. At the night side, temperatures drop to -180 C. Permanently shadowed regions (PSRs) are extremely cold (minus 240 C). Vacc-suits are not optional.

* *Dust:* Luna is covered in a dust that is much like fine volcanic ash. Its a serious irritant, toxic and damaging after long-term exposure. It clogs up machinary and causes a wide range of problems. All habitats need extensive must removal systems to prevent contamination.





== None-Player Characters

---
====
*Zeena Platts* (Realname: Sam Modey)  +

[width=500px]
image:https://dub01pap003files.storage.live.com/y4m2DgiBlAJFBUTftFn3UivMdlowj_f-3B2WqxnMrQksY4YCpxoriFGBrnLwF8hYcGG_4UXbbPDAoV-ICwOu3Hp7YhIoKA7toufZdP0PrKglDtx5PvGJMt6diIcVJ1UajmIkPcWZYaR9csjRhUTbO3WKk7ABTA1tvLuJq_h7tcgC4bIuG_G7Wy9uid7zQ98VNHj?width=660&height=660&cropmode=none[alt=Zena,width=340,height=340]

*UPP:* 896A38	Age 22 +
Interior Designer (actually, Pirate (1 terms) Rank 2 - Lieutenant) +
Electronics-0 , Energy Pistol-1 , Engineering-1 , Space Vehicle-0 , Piercing Weapons-0 , Piloting-1 , Streetwise-1 , Survival-0 , Turret Weapons-2 , Zero-G-1 +
5,000 cr +
Vacc Suit

Zeena is a "Jonah". A passenger who operates as an insider for pirates.

*Playing Zeena/Sam:* +

Zena is an act. Sam maybe overdoes the dizzy young woman act. Playing stupid. It's easy in stressful moments for the facade to slip. Celebrating your supreme ignorance about something, then later showing you know a lot about it. Sam tries to keep to herself, not chat. However, she is jubulant because she thinks that she has marked her first big score, so she is a little giddy and by half-way through the journey has become all together too chatty.

She is moderate and shows calm under stress. However, she isn't very good at hiding distain or anger.

*Trix Quotes:* +
"Whatever, man". +
"Listen, mister. I didn't pay my hard earned resource credits to get borning lectures from you". +
"Well this isn't boring, I'll say that".


====

---
====

*Jack Deringer* (Real name: Percy Brennan)



[width=500px]
image:https://dub01pap003files.storage.live.com/y4mUdEJq0h4RbeoloWvV_ElWyMwkaqMInzdaW9ihUgGDVclZmKryg2RHGPmFuq45094ieWt4wXzbqVRe4XConNk37Pgs12a9dIjBKkM4eOPJ76uoacT-k3liFvFtBzngN8KpyFj8r4fX4WHPVIbUsmRLwdO6BxpUQxFXlyZTJ4aBkvqjHyleEzpefk63Y3_Eu-V?width=660&height=660&cropmode=none4[alt=Percy,width=340,height=340]

*UPP* 455D79	Age 50 +
Colonist (5 terms) Rank 5 - Lieutenant Governor +
Drifter (3 terms) +
Admin-0, Electronics-1 , Farming-3 , Gambling-1 , Liaison-1 , Mechanics-1 , Natural Weapons-1 , Recon-1 , Shotgun-1 , Streetwise-1 , Survival-2, Tracked Vehicle-1 , Zero-G-0 +
235,000 cr Pension 10,000 cr

Percy spent his life working diligently in hydroponic farming. He got really good and made a modest fortune. A few years ago he realised that what he really wanted was to be an espionage agent. Too old and with the wrong skillset, Percy instead turned to a life of deception. He travels the solar system under different aliases pretending to be spies, pirates or just damned mysterious. He doesn't use his deception to rob people, he just wants people to see him as an interplantary man of mystery, not a moderately successful hydroponics engineer.
====

*Playing Jack/Percy:* +

Jack is an act. One based on watching far too many spie VRs. Jack is supremely confident, authorative and exudes leadership qualities. Ironically, these are not part of the act, Percy was an effective leader in the world of hydroponics, he just yearned for a life of adventure. When things get stressful, the act just gets stronger and stronger. Percy won't snap, he'll thrive on the danger. 

Jack is looking for attention and will attempt to be a leader for the group. However, while Jack does a great talk, not all of his plan hold water.

The problem will be when he is finally found out, when the group learn that he's not an agent but a retired farmer he will become crestfallen and a little angry.

*Jack/Percy Quotes:* +

"I got a bad feeling about this". +
"I can smell trouble when it's 30 blocks away". +
"Stay calm, if you're in the presense of the grim reaper, don't make it easy for him."



---

*Anjar Singh* 

[width=500px]
image:https://dub01pap003files.storage.live.com/y4mQ52Kt3GHfFuWFr8swiDF22MmKwTfSBqWKstpDWv1v3F3iBk1RVcswO6F_FRirxFb4QbFGpOFst_FiNg81CbI36m-r9dVDMwOeQYt61ZKggOTNPbCYhNhcVC5y9C5QUy6rNUVCIQvBn44S76xVgUcXcHi9g2YDNw33PkwoNx-J9SxhpTKD_qTupydFDg0cw_-?width=943&height=953&cropmode=none[alt=Anjar,width=340,height=340]

*UPP* 657B66	Age 34 +
Belter (4 terms) +
Comms-0 , Demolitions-3 , Electronics-1 , Energy Pistol-0 , Heavy Weapons-0 , Mechanics-0 , Physical Sciences-0 , Piloting-2 , Zero-G-2 +
35,000 cr +
Mid Passage +

Anjar is a asteroid miner. A pretty good one. He has sizable shares in several valuable mines. Having nearly come close to death three times in his career, Anjar has decided to cash in and find another life. Sadly his brush with death has left Anjar suffering from mild paranoia and panic attacks. Nothing serious, but it makes him likely to call out wild suspicions.


*Playing Anjar:* +

Anjar is the group comedy character. He's constantly quipping and making observations based on a deep knowledge of risk probabilities and safety best practices. However, under stress, Anjar suffers from mild panic and paranoia. Suddenly he flips from good humour to wild and angry accusations.


*Anjar Quotes* +

"It's fate, it's fate. She wants me dead. I left asteroid mining because I'd experienced two near death events and I decided I wasn't going to hang around for a third. Damn it!" +
"What's in the case, Jack. WHAT IS IN THE CASE? Did you cause this? IS THIS YOUR FAULT, JACK?" +
"Sloppy vacc suit operation still accounts for 37% EVA deaths. Always check everything three times, then get someone you trust to check for you."

====
---

*Trix Montang* 

[width=500px]
image:https://dub01pap003files.storage.live.com/y4m_l4CAUDGgoUee0jv-tteaWL0DOiM3esotYJZzm110OBO4gcJQmpWP6ALc0a5BN4DIbasYRMD6CR3L11tmrc0L_kQcsV0H1A1kukRA3FyrxcZU31z6pLmPODl-n8QigNxCfGqpU3epZyb0MSLwaumX4WY1_P-ziLtgn_fjzMVFKQxmrftlWbh8jhLgqSyT41U?width=660&height=660&cropmode=none[alt=Trix,width=340,height=340]

*UPP* 46AA9A	Age 34 +
Entertainer (4 terms) +
Admin-1 , Athletics-1 , Bribery-1 , Carousing-2 , Gambling-1 , Liaison-2 , Linguistics-1 , Social Sciences-0 , Survival-0 , Tracked Vehicle-0 +
1,120,000 cr +

Trix is a non-binary folk singer, guitarist and writer. Trix started out as a rebellious punky sort of solo performer. Now they've started to struggle for new material having become critically and commercially successful. Today, Trix is having to act the part of a young, angry and hungry performer. They have a tendency to over-amp anger and angst which come run past edgy and into, well a bit scary. Songs about burning it all down, dropping anti-matter bombs on Earth and generally doing over-the-top things have given her a reputation as song writer for budding revolutionaries. A reputation that has kept her busy visiting various small mining colonies. 

*Playing Trix:*

Trix is an anarchist. Can't abide authority figures, especially ones that wear suits. Has a tendency to say outrageous things. 

*Trix Quotes*

"Well aint you a little thunderbird." +
"Oh Oh, I predict a riot" +
"If wishes were horses, you nonpats would ride to the stars." +
"I'm going to write an angry little song about you. Hope you won't like it." 
====
---

*Freddy Happyness Cheaplove* 

[width=500px]
image:https://dub01pap003files.storage.live.com/y4mW7hLop0ZOEJT2mRECXSJ3ruPazquavNmRK7F9Jiw7evQSorYLkKw3pvdbljMUBMfjRWqQAIGDH8xAHkTLTRU6yA5mnpPcAUOj-fpL3YGkOf06f0kYKYLO3UySJuxXYP8MHkBMMIf70RO1savu-ADOsi-Al1UygCzfnIiox9Sf-kwVu6kfDQtKt37s_eN6Z5j?width=660&height=660&cropmode=none[alt=Trix,width=340,height=340]

*UPP* 67B4B9	Age 26 +
Journalist (2 terms) Rank 3 - Investigative Reporter +
Admin-0 , Bribery-1 , Carousing-0 , Computer-0 , Leadership-1 , Linguistics-1 , Piercing Weapons-1 , Streetwise-1 , Tracked Vehicle-1 +
15,000 cr +

Freddy is an investigative journalist, working for a news service that operates out of The Central African Archologies. He's been investigating corruption amongst the polar mining settlements. He's started to annoy a number of criminal sorts. His editor has caught wind of the incidents and has recalled Freddy to the Copernican office. Freddy is a natural information differ. He has a great instincts for a story, and is a good reader of people's motives.

*Playing Freddy:*

Freddy is a backup for the PCs. If they're wildly missing clues, Freddy can step in and ask a question to direct their thinking. Freddy is sharp, ambitious and very skilled. He uses his chearful and chatty persona to give the impression of something not to be taken too seriously. People soon drop their guard when in Freddy's company. Always looking for a story, Freddy will ask questions, but he favours listening to others rather than interrogating people.

*Freddy Quotes* +

"I ward love to hear your opin-EE-ons on dis thing." +
"Can I quote you on that?"
