= Moon Crash

== Introduction

A one-shot adventure for Orbital Elements Science Fiction Role Playing Game.

*Setting:*  Mare Imbrium (Sea of Rain) basin. Old Helium-3 mining regions, criss-crossed with contested "no man's land".

== Synopsis

The PCs are carrying a small group of passengers in their light rig across the lunar landscape when a ground-launched missile hits them. The PCs are forced to crash land their rig, landing in a no man's land region that is littered with dangerous automated weapon systems and ruthless pirate gangs. They must survive long enough to reach a place of relative safety, then figure out a way to either make their way to the nearest settlement or call for a rescue.

One of the passengers, a Percy Brennan says that he is carrying sensitive information. He offers to pay a significant bonus of the PCs turn off their IFF signal, so they can't be easily tracked, and fly at low altitude to keep off radar. Such requests are not unusual. Luna is now less of a war zone than it was, but people are still nervous travelling across the surface. It's no unheard of for travellers to complete a journey across Luna by travelling to orbit and then coming all the way down. More miles but less worry about encountering trouble.



The adventure is broken down into the following episodes:

=== Episode One: Moon crash

The PCs are introduced to their current situation. They don't get much time to prepare before their vehicle is hit by a small missile. Their rig immediately goes down. The PC piloting the vehicle gets to roll for how severe the crash is, and where exactly they land. On landing, it's clear that their vehicle is wrecked, and in danger of being shot at by any number of autonomous drones or hidden launchers. The PCs must decide how long they risk stripping equipment from the vehicle before a likely strike arrives. Eventually another missile is launched, resulting in the crashed vehicle being peppered by a cloud of penetrators. Lethal for anyone still in the vehicle. 

The episode ends with the PCs deciding on a course of action. They might wait near the vehicle - not a good idea. They might head out and try to find some kind of refuge from where they can wait out until a search party arrives. Normally a personal communicator works fine, but the no mans land regions are usually covered by heavy jamming and interference.

=== Episode Two: Across the bright face

The PCs have a map of the region. They must decide where to travel. They're on food and have limited air and water. Enough for 48 hours. As they travel across the lunar no man's land they roll on an encounter table each hour of travel. They may encounter discarded equipment, derelict shacks, killer drones or even pirates.

=== Episode Three: Oasis

Eventually, the PCs find the entrance to some kind of underground base. It's a hidden missile silo, intact and operational. It's the strongest source of local jamming and although there isn't a functional communication system, the jammer itself could be modified to send out an S.O.S. signal. The PCs can spend time exploring the base, learning a little about people who once mannned the station. At some point a group of pirates rigged the silo to launch missiles at low flying or ground vehiles.

If they manage to modify the jammer to send a signal, the first people to turn up won't be a rescue party, it will be a contingent of pirates wanting to know who is messing with their missile silo. A fight will ensue.

=== Episode Four: Moon Cavalry

If the PCs lose the fight, a rescue party will arrive just in time to save them. If the PCs hold off the pirates long enough, the rescue party drives away the pirates.

=== Epilogue

The PCs are taken to the nearest settlement where the local security force will debrief them. 


== Episode One: Moon crash

Read-out-1
'''
Luna Excursion Rig LER-21, Registration L-XP32-J12P, in transit to Copernicus City
Carrying light cargo and five passengers.
Passenger Manifest:
Percy Brennan, carrying precious cargo in a suitcase. Declared prototype scematics.
Zeena Platts, 20-year-old interior designer, leaving the polar regions after a number of jobs improving various communes.
Anjar Sing, 40-year-old surveyor, heading for early retirement after a couple of big mineral finds.
Trix Montang, nonbinary folk singer and performance artist, returning from a tour.
Freddy Happyness Cheaplove, journalist from the Azania archology, doing a backpacking tour of Luna. 
'''

