== Space vehicles

Orbital Elements is a game about space travel, so space vehicles are a very big deal. You notice we don't call them ships? Well that nautical analogy didn't manage to survive the 21st century. There are no oceans to travel, no round windows in the hull, no sails -- actually sometimes there are sails, but we're not calling them ships. There are no battleships, no cruisers. Space vehicles fall into the following classification system:

=== Rig

A rig is a simple, cheap to build and maintain space vehicle. They're suitable for transporting small payloads between facilities that are both situated in the same locality. Some Heavy rigs can make a full interplanetary journey, but really only between planets in the inner system. Rigs are the space trucks that zip people and packages between orbitals and space-based destinations on or around a planet. Larger rigs can make interplanetary trips, although they're not the best fit for long distance travel.

==== Light Rig

image:https://db3pap001files.storage.live.com/y4m0r957IJ8IJX2aFCyh7_HGphF7-ymF7wHJZen-b0wZLIUd4HLO7ZOxn0VcoXc06izEKLzZ2xBluKtxWQ7L2b8ZRjCOI61Jz2xL_F6lNnE6a1xgaYXr_bH44OU9DrCn0YK9D0Hqx2CGHGwM1IBOGwggjOW-WEp8fmooSe2MUMrmKwDsd4JQ8VTjOpTFVX4yGDl?width=1024&height=360&cropmode=none[image]

* *Displacement:* 5-49 tons. 

* Sometimes referred to as a gig, this is the smallest available class of space vehicle for carrying people. Drone carriers are smaller, but they typically don't have crew. The light rig is essentially a "space car" or transit van. They're cheap enough to be available for enthusiasts and private individuals. While outright ownership of vehicles by the public is rare, many people have a share of or a lease on one.

* *Types include:* Landers, Lifters, Orbiters, Taxis, Shuttles, Small Utility Vehicles (vans).

==== Medium Rig

image:https://db3pap001files.storage.live.com/y4mfZCdIis5qLJymBn-qGu-bCDaUAZVfSJtyp72iMBzDDTfIrUK9tdLpjE8zbqQWrrZihcyS2ruRbR3FvsQhPx1IrLh8EauI24Lm59rQJqDlBBmXbL1z-wMc0byHDrjWCrVF4OTWetyPTN06wi8SvSsComIwZmcic0BFF2qBXwxuC3OR1pX2NHJvoiF98d8ko5K?width=660&height=495&cropmode=none[image]

* *Displacement:* 50-100 tons. 

* Medium rigs are the workhorse class of space vehicles. Older rigs in this class would be limited to travel between locations in the inner system, but recent models have an operating range that allow travel to the outer planets, although not to the Keiper belt, beyond.

* *Types include:* Module transporters, Explorers, Mobile Outposts. 

==== Heavy Rig 

image:https://db3pap001files.storage.live.com/y4mnKoPTX4ut9cWJ-Cwk6YLRNsfLuUO5t6JpzbKW1sBAkJQqwpODDNmGHIUKZGZbFwqU6EwvR5t2vsQt1vREQV8Dl9_V07L8O9fkRCmFbxtxg7s92PsDXgY7mco_L73-n5dDHVVuAuLC2LkRiDrCiE-BlhI2ZU0d4vKZX4yr9sqVmKJd4Ag7LtSQwC8Le6WPLYe?width=660&height=433&cropmode=none[image]

* *Displacement:* 101-500 tons. 

Heavy Rigs 

* *Types include:* Tugs, Heavy lifters, Mobile Repair vehicles, Gunships (military), Modular transporter.

=== Space planes

image:https://db3pap001files.storage.live.com/y4mALkVd1wLnYsJ4RDW9wPi4eAG3bPFWwAcW9OUFfNc3uU22dCVDviuWtPweXOivXsouaR2JicI9sHTtn5YHUhGrFr_lJrxXVQa0WkVWYqtI0-vtaTQROqhqOJqGd7XVrK0MiTvu__842MDNNiyR1n7EUVtsjQg18R00bhwaZVL2e1msX2VJnhWcms5aexFgDWJ?width=660&height=660&cropmode=none[image]

* *Displacement:* 50-200 tons.

* Space planes are specialised vehicles that operate both in atmosphere and low orbit. There are only a few places where wings provide any benefit, so space planes are rare. Also, those planets with atmospheres are all wildly different, so each planet has its own spaceplane design. For example, Mars has almost no atmosphere so Space planes need massive wingspans and generate most of their lift using vectored thrust. While Venus has a super thick atmosphere, making anything with modest lift generating surfaces into a potential space plane. However, Venus and Mars have not magnetosphere, so their space planes require shielding that isn't required on Earth-rated space planes.


=== Heavy Transports


image:https://db3pap001files.storage.live.com/y4m8B_8y1gikAibDipU60sv2nzF3D8WSqnereMCVgEeOXeCZvw6v7lneJiDU3U-JSAoAfxpEYWc-V41pVgOfuyhbk_5RD8bRSHlrnydjOiSVyFJ2aCW2k6hJnQH4yHwXrPQsxtP-q7bCIBDF1rEztdha8p1HZ-lL7S1ZvAPteaKN2H5zveMegaOWTVrfYhucbz_?width=660&height=313&cropmode=none[image]

image:https://db3pap001files.storage.live.com/y4m0mpZaPPShUEFt-6nnAWpoIolU1JXeWndb1NLz-pGNnMqw2a7_xGjGskXdF_JtJNhTLccde5myINLw8tdDiV69IcHhqFMF49QUblpBfXbwtGTNEm-FROIKiiFQ9BITuoa7pXZGdFpggJ_5h4tcraoyJir_UanirvSUivAxzPyYox29JiDJJf9vmxO-HzzMU6D?width=660&height=221&cropmode=none[image]


* *Displacement:* 1000-10,000 tons.

The heavy transports are the largest general space vehicles in operation. Larger vehicles are small in number and are purpose built, so can't be generalised. The majority of heavy transports carry raw materials or large numbers of shipping containers. 

* Types include:* Bulk carriers, Tankers, Mobile factories, Drone carrier (civilian and military types), Troop carrier (military) Mobile defense platform (military).

=== Cyclers

image:https://db3pap001files.storage.live.com/y4mLm90QYTX8Eg7s1g1xj6fVyN4tAGOaj51fjLZPfJdgbjBy977W4HtnglpQlBJQSMv4n0Zu6DxVZAlcPyXtu-JkamrjtuiiVBiT5prGOTlLHI2RxHz68GRwGedXaKlJJl2lc1wNqSp05vcRmclOSStIefhQFWukFu_zn7FbEQ0m7DRipF5SRtvbpwcMX3N3mKc?width=660&height=303&cropmode=none[image]

* *Displacement:* 200,000 tons

Increasingly redundant, the cycler is a very large ship that is set on a orbit between Earth and Mars and between Earth and Jupiter. Once established, these ships would make the journey between these destinations in a few weeks, without needing to expend much fuel. While most ships slow down to enter orbit with their destination, instead powerful shuttles are deployed to handle to transit of cargo and personnel.

In the past century space vehicles have massively increased their travel speeds, negating the need for cyclers. However, they're now very cheap to travel on, and now have a cruise ship vibe, because they are so roomy and are focused on passenger comfort and entertainment. 

=== Sail Ships

image:https://db3pap001files.storage.live.com/y4mM_wgTaZhyzvWwYCzA55sQbG6ZbFSyX4S7-t1jpfWmzPhGoXHkyV4p173rgKXV5Zu1BZ8n_mwTcC7vKNv86hYrGa7mm4ieI5dat8E9VdRyIWO6LO8BFP-a1HKbqI_zXmhPIaPJ8Ms4HoyxiJN205NRbQ4HcYP8QKYo8UQ8lzXgyrNl24WmcvF_qBVQb94trht?width=660&height=495&cropmode=none[image]

* *Displacement:* 200-20,000 tons.

Sound quaint, don't they? Well they're not, they were the fastest ships available before matter anhilation drives arrived, about 50-years-ago. High powered lasers, based throughout the system gently push sail ships towards their destination. Other laser systems at the destination then slow the ships down. As the ship doesn't need to carry propulsion and the lasers can provide thrust indefinitely, a sail ship could  reach a good fraction of the speed of light. 

* *Types include:* Bulkers.


=== Mobile Stations

Extremely large vessels are rare, but many space-based colonies are capable of moving to completely new locations, either using tugs, bolt-on engines or deployable sails. These monsters employ weeks or months of constant low acceleration to build up delta-V. 
