== Planetoid of the Monkeys

An Orbital Elements mini-adventre



=== Synopsis

Eccentric Trillionaire, Leendert "Lee-Roo" Roosendall has announced that he has another world changing innovation. He's presenting it to his three closest billionaire chums, on his private asteroid. Today a group of journalists have been invited to the asteroid to see what Roosendall has created. In view of his checkered history, analysts predict that there is a 100% chance that the innovation will either change the world or will be laughably mad.

Roosendall has bread genetically modified monkeys that can be controlled or guided by a central computer. This makes them a super cheap, easy to maintain workforce, capable of fine manipulation and mobility - things that droids are still not great at. Roosendall says that he got the idea while tidying up his kitchen and wishing he could call on a little workforce to do the work. He thinks the biggest application will be as home help.

Problem is --- Roosendall's secret was already leaked to one of his friends, who as part of an elaborate joke has smuggled in their own monkey to the planetoid, armed with a powerful hacking system in its brain. The spy monkey takes over Roosendall's demonstration monkeys but then reject's its orders to ruin the presentation with playful mischief, instead it follows its own agenda, activates all 1000 monkeys stored in hybernation and attempts to rescue them by hijacking private rig. Freed from the bonds of computer control the monkeys become a force for chaos and violence.

The PCs have been hired to attend the public presentation, pretending to be journalists -- once on Roosendall's private asteroid they're to attent to plant bugs that will allow the Holland-Archology government to keep tabs on Roosendall's work. However, on arrival they find the asteroid habitat has fallen to chaos. Massive roving bands of giant monkey's armed with knives and a few stun pistols have forced the surviving occupants into hiding.


A call to Mr Jackdore Cambden, industrialist frienemy for Leendert's:
"Mr Cambden, DO NOT activate SABO. It's not SABO. Apparently SABO died in his sleep, so they replaced him. All our control software is based on SABO's brain scans, we do not know what will happen if you activate your hijacker monkey. Probably very bad things..."

It seems that Jackdore had known about the monkey development and had planned a mischief, building a monkey that would be added to the test group, which would, using it's hijacking brain module, take control of the monkeys and use them to embarress Roosendall -- partly to demonstrate the danger and folly of trying to control monkeys. However this lesson in humility backfires spectacularly when the hijacker monkey fails to follow its programming and instead goes has its own plan.


=== DroomHuis

Dreamhouse is Roosendall's massive personal space station, built into a 2km-long iron/nickel asteroid.

==== History

Originally M-12-Brewer-Aarav (M-12BA) was surveyed in the asteroid belt, close to the Ceres orbit (Ceres beltway). Property developer, Gangesh Holdings, co-funded the hollowing, reinforcing and transfer of fifteen asteroids which were slowly nudged into Lagrange orbits, a journey that took between eight and twenty years, even with the use of massive anti-matter rocket systems. Two AMPS were installed in M-12BA to handle the hollowing and restructuring. 

After the asteroid was judged "flight-worthy", these AMPS turned to the massive job of constructing habitation infrastructure and living space. After a decade-long journey, M-12BA arrived at its new home, at L-2. During this time Gangesh Holdings had been bought by VEXTek (Vivamus Extensio X Technologies), a company that started a revolution in affordable life extension drugs. Gangesh Holdings had got into financial trouble as a number of auction winners that defaulted on payments during the decades-long project. On taking over the company, VEXTek took ownership of three of the fifteen asteroids, including M-12BA. 

In 2269, M-12BA fell under the ownership of VEXTek's owning Family, becoming one of the most expensive and exclusive family residences in human history. VEXTek relocated its research and development facilities into the asteroid's inner ring area, while the outer ring became the Roosendall families private property. 

The main hollowing is seperated between two distinct areas, the inner ring consists of a huge area of low-g work space. While the outer ring is a single open space that boasts 4.4 square kilometers of recreated Earth landscape, part of which is modelled on pre-21st century Holland, with canals and a windmill. 

=== Inner Ring



=== Outer Ring


=== 

1.3 revolutions-per-minute. Generates 0.85g on the main habitat ring.
