= Moon Crash

== Introduction

A one-shot adventure for Orbital Elements Science Fiction Role Playing Game.

*Setting:*  Mare Imbrium (Sea of Rain) basin. Old Helium-3 mining regions, criss-crossed by a contested "no man's land".

== Synopsis

The PCs are the crew of a transport shuttle, carrying a small group of passengers across the lunar landscape when the shuttle is suddenly hit by a ground-launched missile. The PCs are forced to come down in a no man's land region that is littered with dangerous automated weapon systems and ruthless pirate gangs. They must survive long enough to reach a place of safety, then figure out a way to either make their way to the nearest settlement or call for a rescue.

One of the passengers, a Percy Brennan says that he is carrying sensitive information. He offers to pay a significant bonus of the PCs turn off their IFF signal, so they can't be easily tracked, and fly at low altitude to keep off radar. Such requests are not unusual. Luna is now less of a war zone than it was, but people are still nervous travelling across the surface. It's no unheard of for travellers to complete a journey across Luna by travelling to orbit and then coming all the way down. More miles but less worry about encountering trouble. In fact, Percy is a fantasist who travels through the system pretending to be either an espionage agent or someone carrying a mysterious suitcase. The suitcase contains some sims, stims and emergency toiletries. However, one of the other passengers is a Jonah. An old nautical term for someone who was thought to bring bad luck on a ship. In modern parlance, the term specifically refers to someone who is working for criminals who intend to ambush or rob a vehicle during a journey. The Jonah is usually a passenger or recent hire who will sabotage the vehicle, plant a tracking device, or will take direct control. In this case, Zeena Platts is working for a pirate gang. She caught wind of Brennan asking for a transport to fly "off the grid". She assumes that he is carrying something of enormous value, so has decided to risk signing on as a passenger, so that she can be on the ground when the value of the cases contents is discovered. When she discovers that there is no precious cargo, she'll have a minor breakdown. 

The subject of the scenario is how the player characters deal with the crash and the dangers of finding a place to shelter. The pirate angle becomes apparent when, on finding a missing launch facility they identify that someone has put a beacon on their rig. Almost certainly one of the passengers as it would need to be activated some time after leaving polar traffic control.

The adventure is broken down into the following episodes:

=== Episode One: Moon crash

The PCs are introduced to their current situation. They don't get much time to prepare before their vehicle is hit by a small missile. Their rig immediately goes down. The PC piloting the vehicle gets to roll for how severe the crash is, and where exactly they land. On landing, it's clear that their vehicle is wrecked, and in danger of being shot at by any number of autonomous drones or hidden launchers. The PCs must decide how long they risk stripping equipment from the vehicle before a likely strike arrives. Eventually another missile is launched, resulting in the crashed vehicle being peppered by a cloud of penetrators. Potentially lethal for anyone still in the vehicle. 

The episode ends with the PCs deciding on a course of action. They might wait near the vehicle - not a good idea. They might head out and try to find some kind of refuge from where they can wait out until a search party arrives. Normally a personal communicator works fine, but the no mans land regions are usually covered by heavy jamming and interference. 

Player handout 1: Shuttle manifest

Player handout 2: Regional map

=== Episode Two: Across the bright face

The PCs have a map of the region. They must decide where to walk. They're on foot and have limited air and water. Enough for 48 hours. As they travel across the lunar no man's land they roll on an encounter table each hour of travel. They may encounter discarded equipment, derelict shacks, killer drones or even pirates.

[width=50%]
|===========================
2+ | *Encounter Table*
|1        | No encounter, rock, dust and the black sky.
|2        | Small surface debris. Roll on the *Debris Encounter Table*.
|3        | Small surface debris. Roll on the Debris Encounter Table*. Add +1 to the roll.
|4        | Crash site. Roll on the Crash Site Encounter Table*.
|5        | Small ruin. Roll on the *Ruin Encounter Table*.
|6.       | Small facility. Roll on the Facility Encounter Table*.
|===========================

[width=50%]
|===========================
2+ | *Debris Encounter Table*
|1        | Scattered rocks
|2        | A small crater, about 10m in diameter surounded by rock fragments.
|3        | A large crater, about 50m in diameter. Walking through the crater requires some checks against dexterity. 6+ to avoid a fall.
|4        | Signs of fighting. Metal casings and fragments are scatered around. Maybe some discarded pieces of equipment
|5        | Signs of a battle. A few 
|6.       | Small facility. Roll on the facility table.
|===========================




=== Episode Three: Oasis

Eventually, the PCs find the entrance to some kind of underground base. It's a hidden missile silo, intact and operational. It's the strongest source of local jamming and although there isn't a functional communication system, the jammer itself could be modified to send out an S.O.S. signal. The PCs can spend time exploring the base, learning a little about people who once mannned the station. At some point a group of pirates rigged the silo to launch missiles at low flying or ground vehiles.

If they manage to modify the jammer to send a signal, the first people to turn up won't be a rescue party, it will be a contingent of pirates wanting to know who is messing with their missile silo. A fight will ensue.

=== Episode Four: Moon Cavalry

If the PCs lose the fight, a rescue party will arrive just in time to save them. If the PCs hold off the pirates long enough, the rescue party drives away the pirates.

=== Epilogue

The PCs are taken to the nearest settlement where the local security force will debrief them. 


== Episode One: Moon crash

Read-out-1
'''
Luna Excursion Rig LER-21, Registration L-XP32-J12P, in transit to Copernicus City
Carrying light cargo and five passengers.
Passenger Manifest:
Percy Brennan, carrying precious cargo in a suitcase. Declared prototype scematics.
Zeena Platts, 20-year-old interior designer, leaving the polar regions after a number of jobs improving various communes.
Anjar Sing, 40-year-old surveyor, heading for early retirement after a couple of big mineral finds.
Trix Montang, nonbinary folk singer and performance artist, returning from a tour.
Freddy Happyness Cheaplove, journalist from the Azania archology, doing a backpacking tour of Luna. 
'''

