== Free fallin



The following mini-adventure is a great way to introduce new players to Orbital Elements. 



=== Adventure Summary (Game Master's eyes only)

This adventure is designed to start off a new play group. At the beginning of the story the PCs are not a party, but in the first chapter they are thrown together and must quickly learn to rely on each other in a deseperate struggle for survival.

In the opening chapter, the player characters are prisoners of a paramilitary force that holds a contract with Lanserda Yeocan, the nearby industrial settlement on Jupiter's moon, Calisto. The player's only crime was to be passengers on a passenger carrier that the paramilitary group accused of piracy. The ship was impounded and both crew and passengers arrested. Three weeks into their incarceration the patrol vechicle is setting course for its base. The twenty four prisoners who were just passengers are loaded onto two shuttles and launch to who knows where.

However, the shuttle on which the PCs are situated makes a detour after the four crew become agitated. Rumous pass between the passengers that the shuttle has been ordered to investigate a transport ship that has gone dark after broadcasting an SOS. Soon, the PCs are selected by drawing straws for a potentially dangerous mission to board an apparently deralict transport vehicle. The PCs make the 300-metre trip to the apparently lifeless transport vehicle. The moment the players board, some kind of munition launches, destroying the shuttle that they were travelling on. The PCs now seem to be alone.

At this poing the adventure opens out to allow the PCs to explore the deralict, ITV Golden Goose.

==== So what happened on the deralict?

Some of the transporter's crew, loitering around the cargo deck decided to tamper with the wrong package, a robotics system. The system is an advanced humanoid robot of unusual complexity. The crew members activated the robot for poops and giggles, not knowing that contrary to the manufest, the robot wasn't a "labour droid". When they tried to have some fun ordering the robot around they were attacked and immobilized. The robot is a prototype anti-piracy droid, intended to act as security onboard transports. However, the unit is not supposed to be activated without first being programmed with the identities of the crew. Consequenty, on being activated the droid is classifying all of the crew as hostiles. In the ensuing fracas, the crew is mostly immobilized and captured or scatters and hides away on the ship.

==== Explore the ship

The PCs must explore the ship and try to work out what happened. They must unravel the mystery of the Golden Goose and find a way to take control of the ship before it coasts out of range and ends up floating into a deep system orbit.

There are several ways of beating the anti-piracy droid. Firstly, they could mount a physical attack using well thought out improvised weapons. They are unarmed but they might locate the ship's locker which will contain a number of non-penetrating but effective firearms. Possibly other weapons like stickyweb guns that fire a web of powerful glue.

They might try to trick the droid into a location that they can lock, although the droid can effectively blow-torch its way through internal walls given enough time. If it escapes it initiates PLAN-BETA, it heads to the cargo module and activates three standard labour droids which it reprograms to become its minions.

However, if the PCs game access to the mainframe, located in engineering, they can force a firmware update that will categorise the PCs as crew members. This provides a satisfyingly simple conclusion, though heading to the engineering section will also activate PLAN-BETA, bringing additional droids into play.

There are a number of entry points into the Golden Goose. There's a full airlock in the command module and each of the hab rings. There's an airlock at each end of the vehicle's stem and two airlocks in each cargo module. Finally, there's an emergency lock in engineering.

T





After encountering the PCs, the drone decides that it needs reinforcements, so it has gone into the hold and activated two other robots which it has reprogrammed to act as servants.








In this starter adventure, the PCs are prisoners on board a paramilitary craft that works for Lanserda Yeocan (blue picnic),  a large chinese industrial colony on Callisto. The story goes, that the PCs were passengers on a transporter that was flagged as having taken part in piracy. The paramilitary boarded the transportter, then arrested everyone. So its three weeks later. The PCs are part of a group of 12 prisoners that have been moved onto a heavy shuttle for transfer "elsewhere". Some prisoners believe that they are being transferred to a free station to be released. Others offer a more worrisome story -- apparently some PMC do a background check on prisoners that they pick up. Anyone who doesn't appear to have rich or influencial friends end up being sold into slavery - their arrest record is deleted by criminal hackers.

The crew and guards of the shuttle become agitated, the following conversation is hearded.

**Guard 1:** I'm not risking my neck going onto a deralict, I didn't sign up to fight pirates. +
**Guard 2:** Ha ha, won't be any risk. Captain says the boarding crew is getting decided by a prisoner lottery. +
**Guard 1:** NO WAY, I already lost one vacc suit this year when I was forced to lend it to a prisoner. +
**Guard 2:** You don't loan a suit, you don't get a cut. It's a big ITV, a 10 thousand-tonner. Even if its empty there will be a million in salvage each. +
**Guard 1:** A million. Okay, but better be right about this.

The twelve prisoners are escorted to the main operations deck and sat at a large table. Each prisoner draws a lazily fashioned straw. The PC's each draw a short straw. Before this moment, the PCs live separate lives, now their lives are link by a momentary act of chance.

The Executive Officer tells the PCs that they have just won the chance to earn their "expedited release" along with a bonus. All they need to do is check out a transport ship that sent out a rescue request three days ago. Nobody on the ship is communicating, now. There's a chance the ship was completely abandoned or maybe the crew are awaiting rescue, trapped on a room somewhere. They might all be dead from a deadly radiation leak, but it that happended we would surely detect it immediately and call off the rescule.

The PCs are kitted out in vacc suits and strapped to a "huskie" a drone that astronaughts attach themselves to, while it handles the maneuvers of an EVA.

The PCs transfer 3000m between their Shuttle and the Transport Vehicle. The PCs now have free reign to decide how and where they enter the vehicle.

Shortly after they enter, some kind of munition launches, blowing up the heavy shuttle. 

== I think we're alone now


== Dancing in the Dark


=== Every Breath you take


=== Under Pressure
