== Solar Gazetteer

image:https://db3pap001files.storage.live.com/y4mF6J7uTJFMEg352kCGKuxS_WAlsWwQhSMh332HDzWNRgTgcUl1Z0Z9DN0Jux20s7qtj7RMTAw2TNd-uXuJHvLguZ-vN2kd8FPdxZ60Wpb-fLh_Mh-ErSDjZ5QUZKm3Q1MTuOVjBM3Rcq4Lqt3qWNHYTYqAnNlTN6KMHZxANhEjXqRJFPt6jgiiLfD8uEibQxB?width=1024&height=354&cropmode=none[image]

The following guide covers all the planets and major masses in the solar system, along with their corresponding stations and colonies.

=== Sun

=== Icurus Station

|=======================
2+| **Icurus**      
|*Diameter:*   |2 km
|*Mass:*      |Negligable  
|*Gravity:*    |Negligable   
|*Escape velocity:* | Negligable
|*Atmospheric pressure:* |0 (vacuum)
|*Surface temperature:*|-10/+800
|*Surface radiation:*|20 SDU
|*Solar Day:* 10 minutes
|*Year:* 30 days
|*Distance from Sun:* 0.2 
|=======================

There are no settlements inside the orbit of Mercury. There is a large reseach and monitoring facility built inside Icurus, a small captured asteroid that was manoeuvred into its close solar orbit to provide a shielded location for a monitoring station. Icurus rotates to simulate gravity and to ensure that the intense heat felt at that location is applied evenly across its surface. The station's habitats are burried deep to provide adequate heat and radiation shielding. The station manages an array of solar monitoring satellites that ring the Sun and perform deep scans, to provide reliable predictions of storms. Satellite maintainence, monitoring and solar reseach keep about 100 staff occupied, with most staff working three-month assignment before returning various Earth universities. Icurus station is an isolated place to work, only very specialised, heavily shielded vehicles can reach it and they follow a four trips per-year schedule.

NOTE: There's now an inflatable heat blanket that can be deployed across the hull of suitable space vehicles, allowing them to travel closer to the Sun. The heat shield is intended for short emergency transit as more than a few days of heavy neutron exposure is dangerous. 


[cols="10%,90%"]
|===
2+|Settlement profile: Icurus Station

|*Function:*
|Science Outpost

|*Founded:
|3rd July 2255

|*Alignment:
| International. The outpost provides a vital service for everyone in the solar system. As such, the station is managed by a board of directors made up of senior academics and AIs from all of Earth's biggest universities.

|*Type:
|Asteroid-spun

|*Tech-level:
|Old-standard

|*Class:
|Cozy

|*Population:* 
|20 + 80 guest reseachers/engineers on 3-month tours.

|*Government Type*
|Civil Service Bureaucracy

|*Law Level*
|Very strict

|*Attitude:*
|Closed

|*Social Type*
|Centrist
|===

=== Mercury

image:https://db3pap001files.storage.live.com/y4mkuAzdlP8JesFStGctLgQKY51eEwSPrjWGnb8S_YyS3nR-AMOjqMdTvoH4i6_Frx09GJ7uyObNzx39z65Gfqmc6yFm-F9H0t7obid-kTzDsbZfJfkDiO1roOXODThGl3MJCNqbL-k4CilpOST7wQRFie1KVb7z9xZ-75Gpe5T7f2DkLcCZBDwq7WeLtbuJnEY?width=1280&height=600&cropmode=none[image]

|=======================
2+| **Mercury**      
|*Diameter:*   |4880 km
|*Mass:*      |0.055 Earths    
|*Gravity:*    |0.38g     
|*Escape velocity:* | 4.3km/s
|*Atmospheric pressure:* |0 (vacuum)
|*Surface temperature:*|-180/+430
|*Surface radiation:*|7 SDU
|*Solar Day:* 176 days
|*Year:* 88 days
|*Distance from Sun:* 0.4 
|=======================

The smallest planet in the system, and the closest to the Sun, Mercury is characterised by extreme heat (450 degrees Celsius under the midday sun) and extreme cold (minus 170 C in the evershades). Geologists have long agreed that Mercury is a planetary remnant -- the core of a larger planet that lost much of its rocky mantle coat in ancient punch-up, probably a collision with another proto-planet. Mercury has almost no axial tilt but its eccentric (egg-shaped) orbit creates extreme seasonal temperature variations.

==== Settlement

A research outpost was established in the northern polar region, on the wall of a crater that never falls under direct sunlight. Large deposits of water were found there, a discovery that makes resource extraction economically feasible, as large water deposits allow any settlements to create fuel locally and be essentially self sustaining.  Mercury has accumulated lots of minerals from asteroid and comet strikes, making it a buffet of useful construction materials. However, counting against early settlement and exploitation was the fact that reaching Mercury's orbit requires a lot of Delta-v. Mercury is essentially zipping around the sun at at very high speed. Vehicles that travel to Mercury need to burn a lot of fuel to get into oribit. Then, if they want to land on Mercury they have to burn more fuel get rid of their speed. The lack of atmosphere means that you can't slow down using atmospheric breaking, like with Earth or Mars reentry. For these reasons, Mercury was settled relatively late, long after the other inner planets and the asteroid belt. 

In 2288 there are just two medium-sized settlements on the planet, mostly supporting water, Helium-3 and mineral mining. A further complication for colonization are the frequent quakes, caused by the fact that Mercury is contracting as its liquid core cools.

*Ground Settlements*

==== Demmeuter

*Alignment:* Controlled by German and Italian archologies. +
*Population:* 75,000 +
German-Italian colony, situated on the northern pole. The settlement is deep underground, occupying an artificial cavern. +

==== Hidayatullah

*Population:* 50,000 +
Indian settlement that oversees water and rare earth metal mining. The settlement stretches through an extensive tunnel system. While it has a smaller population than Demmeuter, it currently has about twice the available living space. There are plans to try to double the population in the next decade.

==== AMP DX229-71

*Population:* 10 +
Autonomous Manufacturing Plant DX229-71 processes various raw materials, then launches them into an orbital stockpile using a mass driver. A caretaker contingent of humans live at the station. The station is mostly surface-based. 

==== Other settlements

There are between thirty and fifty independent mining settlements. These pop up and then dissapear as they're mostly looking for small lodes of rare earth metals delivered to the surface by asteroid impact.


*Orbital Settlements*

==== Idunn

*Population:* 7000 +
Originally a German-built research station. When the research ended, the station was sold a Swiss businessman who expanded the station to become a Swiss-German Colony.

==== Garaventa

*Population:* 12,000 +
Italian fledgeling colony, has the best orbital spaceport around Mercury which manages 90% of shipping to and from Mercury.

==== USEDS Finingley

*Population:* 300 +
United States of Europe Defense Station, monitors the inner system. Maintains two active warships.


=== Venus

image:https://db3pap001files.storage.live.com/y4mKcorB-1QUXlBxbd1rUsaAJhDEmuaYm-DkpRCqDl0w1AC0x2B0JnnbRY2x016rKgWqhp7WvZ4VTggsw63D0I-O8ghy2aCAV4oFsZ-sb5MpAMqPiGPPAZLXqh6YCZ1Nx256NKPZzOwTRWjWNNRxYjZCDfbQP_DVBXHakb-9EbD1u2xXzmNqdZDFwIOoLz62NTi?width=1024&height=480&cropmode=none[image]

|=======================
2+| **Venus**      
|*Diameter:*   |4880 km
|*Mass:*      |0.94 Earths 
|*Gravity:*    |0.8     
|*Escape velocity:* | 10.4km/s
|*Atmospheric pressure:* |92 
|*Surface temperature:*| +475
|*Surface radiation:*|20 SDU
|*Solar Day:* 116 days
|*Year:* 225 days
|*Distance from Sun:* 0.723
|=======================

A planet named for its beauty, Venus is a hellish world with some of the most hostile surface conditions in the entire solar system. It's so hot down there on the Venusian surface that anything not made of a high-melting point metals or ceramics ends up melted or erroded. There have been several attempts to begin terraforming operations but each has ended up discontinued, in part because of the difficulty of operating in such hostile conditions.

==== Experimental Atmospheric Outpost

Historical site. Like a floating museum, maintaining the original research output.

*Atmopheric Settlements*

==== Pegasus Station

*Population:* 1500 +

An under-construction fully-fledged colony. The pegasus project is constructing a vast floating platform, situated 70km above the burning surface of Venus. While the surface of Venus is like the inside of a kiln, the upper atmosphere has a zone where settlers can walk around with just an oxygen mask and acid resistent suit. When completed, Pegasus will provide more than a square kilometer of surface area on which to construct inflatable habitats. The top of the habitation is used for greenhouses and a shuttle recovery platform.

*Ground Settlements*

==== Hadius Base

*Population:* 70,000 +

The Hadius base was built by a specially designed AMP which landed on the surface then quickly tunneled underground to avoid being melted. The AMP dug out a huge pressure-sealed actively cooled tunnel system. The original aim was to create a very large colony. However, getting on and off Venus is still difficult. The heat and pressure force surface operations to be very limited. Only specialised rocket systems can be used to land on Venus, and these rockets wear out quickly. As a result Hadius base never become a large-scale colony. 



=== Earth

image:https://db3pap001files.storage.live.com/y4mXKWsSvSC82ILeraxpa5VA29HZxhNc2c1ykwld0LT4b97dRuoJPwp2bb6Qkl5NSVTFLG58vTEOcIB8Lvza_i6n9MW17QoKh-BLEXD1W6LchAN_S5jTBGPqTH-Faf2y4JculfVneyqgUhIKk9KZFc9mS0vDgVMVgFW4sYolAAXvBu2iHKfI5wLms8MDF9vFoWo?width=1024&height=480&cropmode=none[Earth Header]

|=======================
2+| **Earth**      
|*Diameter:*   |12,700 km
|*Mass:*      |1 Earths 
|*Gravity:*    |1     
|*Escape velocity:* | 11.2km/s
|*Atmospheric pressure:* |1
|*Surface temperature:*| +15
|*Surface radiation:*|1 SDU
|*Solar Day:* 24 hours
|*Year:* 365 days
|*Distance from Sun:* 1
|=======================


image:https://db3pap001files.storage.live.com/y4mVH80D8qYEGpGJt9tiTHyTisxxqr4TmW5wqnBHROA6J91TErF0t0pPFgqfooEZMqPeNcgy6kFBqmvOfoh5SiHyXkvnnIkHK4Og_ySld9unJl5SDMZNVkxPJIjZiO3tU5DA21Pxf_tAUMeFzj85s1BxSZXop6Ba6ISu_b4i-x1QqOfaMGYtAlrSBsuE1xG1NLR?width=1024&height=795&cropmode=none[image of the world]

*Archologies* 

More than ninety percent of Earth's inhabitants live in fewer than 100 archologies. The near colapse of Earth's biosphere, along with the constant hurricanes generated by the heat-wrecked atmosphere forced humanity to huddle in cramp, highly vertical city-structures. Anyone not living in an archology is living in so-called Bunker communities, these are networks of underground habitats. Compared to the archologies, these are much smaller with fewer facilities, inhabited by those who valued space and freedom over convenience. Tiny number of people live outside of these two types of habitation. Living "off the grid" means a constant battle for survival, facing savage weather, living off sterilized soil and poisoned water. However, even after hundreds of years, there is money to be made exploring the ruins of the old cities, just don't go unarmed. Things can get wild out there.

There are broadly three types of archology:

**Dome clusters**, where existing cities where covered in vast domes, supported by tower pillars. These are more sprawling, covering larger land areas and being somewhat less developed then the purpose built structures. 

**Tower Structures**, Single or multiple tower structures, these massive buildings incorporate everything required to sustain the inhabitants, automated manufacturing plants supply most manufactured goods, automated farms create the food. Power is supplied from a combination of renewables, fusion power and orbital solar provide energy. 

**Deep Wells**, Some Archologies were dug downwards, creating cavernous habitats that support artificially sustained forrests, lit by huge sunlamps. An approach to living space that was imported from the extra-terrestrial colonies.

Life in the archologies is reasonably comfortable and safe, but for most inhabitants, day-to-day living is highly regulated, with limits on personal freedom. Employment rates are below 25%, leaving the majority of people to occupy themselves through leisure, hobbies or self employment producing artifacts.

Most archologies are extremely insular. Built to be completely self-sufficient, and following very similar plans, so life in one archology is pretty much the same as another. The exceptions are the archologies at the base of the two space elevators, Cayambe in Equador and Mame no ki, 

Raising families remains popular, although most archologies limit family sizes to keep population growth under control. Couples wanting more than two children are encouraged to emigrate to a colony/habitat. 

By the 2280s most archologies have become rundown. While automated systems continue to repair essential infrastructure, the massive scale of these structures make the task of renovation or replacement extremely difficult. Most archologies have shifted to space emigration to handle population pressure. 

=== Low Earth Orbit

There are hundreds of small to medium sized stations in low Earth orbit. Larger stations are not built there because of the need to occasionally adjust orbits would be difficult. Larger stations are built at the Lagrange points, where orbits are stable.

==== Gateway stations


==== Luna

image:https://db3pap001files.storage.live.com/y4mIyqf2rVrPc0HCNc6hsvE_a7Ty9_ZTzXJdH-5tpwo2zfUV-hgZW5Egu9bxhMNq_JCR6icjcbrtQaZSjgdY1WDDUpfWOsZV0cej3MMwpmfDOSQPj-hJgQVFKKmGXmZAtj21xmVQ1XJlXszHK2ZPokwwNVTqseu4ATj22leNs16RSAWelCwcmbrFWBUxxH8XWEE?width=1024&height=480&cropmode=none[image]

|=======================
2+| **Luna**      
|*Diameter:*   |3476 km
|*Mass:*      |0.012 Earths 
|*Gravity:*   |0.165g     
|*Escape velocity:* | 2.38km/s
|*Atmospheric pressure:* |1
|*Surface temperature:*| +124/-173
|*Surface radiation:*|10 SDU
|*Solar Day:* 29.3 hours
|*Year:* 365 days
|*Distance from Sun:* 1
|=======================

The Earth's moon, now commonly called Luna, given that people are living on dozens of moons, is one of the most developed and populous places in the solar system. It was the location of the first perminent space settlement, it then because the main industrial hub for both space development and metal resources for Earth. Over the last two centuries six large settlements have grown to become nations in their own right. This development didn't run smoothly, Luna was the first readily available source of Helium-3, the crucial ingrediant for low-neutron-emission Fusion. Helium-3 was seen as stategically vital resouce -- if you had it, you had a foothold in the future, if you didn't, your nation would be left behind. In the early days, Luna saw nations scuffle over mining rights, then full-blown conflicts.

Mining saw the construction of hundreds of small  temporarly settlements, build quickly and with not much care. The infamous Jobesville massacre occured when the desperate inhabitats of one such settlement suffered life support failure, a band of engineers lead of Tommy Logan travelled to the neighbouring Jobesvill to persaude the occupants to provide technical assistance and parts. The occupants of Jobesville refused to help as their own settlement's infrastructure was close to collapse. The resulting tussle turned bloody, resulting on Jobesville's destruction and the death of its entire population. It was seen as the darkest day in human space colonisation, the larger colonies tried to introduce a legal framework to ensure that future conflicts could be avoided, but nothing could be agreed. There was an on-going cold war among the Luna colonies and no colony wanted to be constrained from "defending" its own rights.

Outside of the protected borders of each colony, Luna is a no man's land of deserted mining settlements and surviving failed-state settlements that breed piracy and cover the activities of the big criminal organizations.

**Apollo City** US Luna hub city, located 

**Chang-Er** Chinese Luna settlement, less developed than Appollo but spread over a larger area, located in the southern pole.  

**Tsiolkovskygrad** Russian industry-focused colony 

**Dubois** Jointed European colony, colonised by all European archologies.

**Azania** Colonised by the African Federation

**Tsukuyomii** Japanese colony

==== Other settlements

There are hundreds of smaller settlments dotted ado

==== Orbitals

The following colonies are massive structures, or captured asteroids built at the Lagrange to house colonists from Earth's archologies. Most are now over 100 years old.



=== Mars

image:https://db3pap001files.storage.live.com/y4msK-xtuAOedDcgosE57w_YQ4tpe87VYrly4cSQsNnEC1lZuC55BKkiO1SLHsDYXps80Lkp1o_gSVlT20EbsyXSuLsvWimC9r1TV6dA5WUg0zf4JXW-mZVg8urVI5bJGNHcSpFIM24yyzzoCIs-Q9QaBB8ioPTTMVUkJKdFqbOKQOFVMQlgUczJfdW_342IOQz?width=1024&height=480&cropmode=none[image]

==== Phoebos

image:https://db3pap001files.storage.live.com/y4mt8-96g06h6RKW1xz25JN0cBdK2oT8s4pPdoLTl5KexY2-BeHtpAwxcoB3zNo3jNpIzYEX-ajNXE0TxPM8IpaCNOo_yr9zfSq9KU6wq37y4QpBibEh6-xAX3qzLG6KxTaiL5hyP-MU1ggAJ4Xd3nOrDhEQKjNJc6dAfmHb0bGVD9NYjs8DmA-W95axUF3PXo3?width=1024&height=480&cropmode=none[image]

==== Deimos

image:https://db3pap001files.storage.live.com/y4mTr2himi63sBjKkNwWT_n-w9qJpMIP3HFtm5xrYrAdldPWmJIHoar7x4mfLqgeIbgl5X25iTp9fR78zm0KXtyqRpZZtc9v8zwSq3nR9pheFO3f73u44_UkDPOG3cSXB9KUy8-uWoyCwDr2hzhdqNkfTs30JvwmctImfrRAqTUtXvEBtBcGuTEdyxnPCUk03If?width=1024&height=480&cropmode=none[image]

=== The Belt

==== Ceres

==== Pallas

==== Vesta

==== Hygiea

=== Jupiter

==== Io

==== Europa

==== Ganymede

Ganymede's surface is exposed to 800 mSv per day. The relocation of people away from Chernobyl was based on the threshold of 350 mSv. You don't walk on the surface of Ganymede, you run into the deepwell underground settlements as quickly as you can. These outpost

==== Callisto



=== Saturn

==== Mimas

==== Enceladus

==== Tethys (trojans: Telesto and Calypso)

==== Dione (trojans: Helene and Polydeuces)

==== Rhea

==== Titan

==== Hyperion

==== Iapetus

==== Phoebe

=== Uranus

==== Miranda

==== Ariel

==== Umbriel

==== Titania

==== Oberon

=== Neptune

==== Rings of Neptune

==== Proteus

==== Triton

==== Nereid


