---

== Orbital Elements - Mini-campaign 1: Sleeping Dragons

=== Summary

After the events of the starter-adventure, the PCs find themselves on Jupiter Gateway, a large space station in orbit around Calisto that operates as the regional cargo distribution point. At the start of play the PCs learn that a black-ops mercenary unit sneaked onto the Golden Goose and destroyed all evidence of the rogue droid. It seems that whoever created the droid wanted to keep its nature a secret.

The PCs are waiting for credit transfers to complete, so that they have money to travel onwards, however they each receive two requests for contact. One is from Manfred "Manny-hands" Royo, the owner of the Sugarhill, the ship the PCs were travelling on that was impounded by the Lanser Yertan security force. The other request for contact is extremely mysterious, it just states that an anonymous party wishes to discuss a business proposition in virtua (virtual reality). The request is signed by Johaness Razili. The man the PCs meet in virtua is a shell, an avatar for the AI "Razili" that secrety runs Jupiter Gateway. 



==== Royo adventure thread

It seems that Royo, a gregarious caribbean man, is dealing with the aftermath of having some of his passengers die after being taken into custody. He expresses great relief that the PCs surived the incident, he claims that he is attempting to take the mercernary unit to court for damages, but this will not be successful given that the group is working for the Lanser Yertan colonial government. However, he feels compelled to give the PCS something of great potential value as compensation for the danger then fell into.

NOTE: *Royo Backstory:* The Sugarhill was impounded on trumped-up charges of piracy. In fact the impounding was part of an elaborate smuggling operation, carried out with acomplices in the Lanser Yertan security force. It seems that impounded ships are not swept for contriband as they're transported straight to a secure docking facility. Once the piracy charges are dropped, the Sugarhill quietly transfers to a civilian dock, where its crew could offload illegal goods.

Royo offers the PCs a packet of encrypted data that he describes as the location of a storage container that contains a crate of precious metals. It belongs to Royo but neither Royo or his people can get to the container as the location is controlled by Royo's "business rivals" (read: competing band of smugglers.) 

Royo is essentially a gangster, although one who avoids violence and foul behavior unless he business interests are endangered.


==== Razili Adventure Thread

