== Free fallin



The following mini-adventure is a great way to introduce new players to Orbital Elements. 



=== Adventure Summary (Game Master's eyes only)

This adventure is designed to start off a new play group. At the beginning of the story the PCs are not yet a party, but in the first chapter they are thrown together and must quickly learn to rely on each other in a deseperate struggle for survival.

In the opening chapter, the player characters are prisoners of a paramilitary force that holds a contract with Lanserda Yeocan, the nearby industrial settlement on Jupiter's moon, Calisto. The player's only crime was to be passengers on a passenger carrier that the paramilitary group accused of piracy. The passenger carrier was impounded and both crew and passengers arrested. Three weeks into their incarceration the patrol vehicle is sets course back to its base. The twenty four prisoners who were just passengers are loaded onto two shuttles and launch to who knows where.

The shuttle on which the PCs are situated makes a detour after the four crew become agitated. Rumous pass between the passengers that the shuttle has been ordered to investigate a transport ship that has gone dark after broadcasting an SOS. Soon, the PCs are selected by drawing straws for a potentially dangerous mission to board an apparently deralict transport vehicle. The PCs make the 300-metre trip to the apparently lifeless transport vehicle. The moment the players board, some kind of munition launches, destroying the shuttle that they were travelling on. The PCs now seem to be alone.

At this poing the adventure opens out to allow the PCs to explore the deralict, ITV Golden Goose.

==== So what happened on the deralict?

Some of the transporter's crew, loitering around the cargo deck decided to tamper with the wrong package, a robotics system. The system is an advanced humanoid robot of unusual complexity. The crew members activated the robot for poops and giggles, not knowing that contrary to the manufest, the robot wasn't a "labour droid". When they tried to have some fun ordering the robot around they were attacked and immobilized. The robot is a prototype anti-piracy droid, intended to act as security onboard transports. However, the unit is not supposed to be activated without first being programmed with the identities of the crew. Consequenty, on being activated the droid is classifying all of the crew as hostiles. In the ensuing fracas, the crew is mostly immobilized and captured or scatters and hides away on the ship.

==== Explore the ship

The PCs must explore the ship and try to work out what happened. They must unravel the mystery of the Golden Goose and find a way to take control of the ship before it coasts out of range and ends up floating into a deep system orbit.

There are several ways of beating the anti-piracy droid. Firstly, they could mount a physical attack using well thought out improvised weapons. They are unarmed but they might locate the ship's locker which will contain a number of non-penetrating but effective firearms. Possibly other weapons like stickyweb guns that fire a web of powerful glue.

They might try to trick the droid into a location that they can lock, although the droid can effectively blow-torch its way through internal walls given enough time. If it escapes it initiates PLAN-BETA, it heads to the cargo module and activates three standard labour droids which it reprograms to become its minions.

However, if the PCs gain access to the mainframe, located in engineering, they can force a firmware update that will categorise the PCs as crew members. This provides a satisfyingly simple conclusion, though heading to the engineering section will also activate PLAN-BETA, bringing additional droids into play.

There are a number of entry points into the Golden Goose. There's a full airlock in the command module and each of the hab rings. There's an airlock at each end of the vehicle's stem and two airlocks in each cargo module. Finally, there's an emergency lock in engineering.

==== PLAN-BETA

After encountering the PCs, the drone decides that it needs reinforcements, so it has gone into the hold and activated three other robots which it reprograms to act its minions. These other drones are standard labour drones, they don't have a lot to contribute in terms of subdueing the PCs. They can hold and subdue the PCs but they don't have any weapons and will not strike the PCs. 


=== Chapter One - The Breaks

==== Scene-1 

Three weeks ago, you were heading for Mars aboard a scruffy but incredibly cheap transporter. Before you could decide what to spend the money you saved on, the transporter was intercepted by a military patrol vehicle working out of the Chinese colony on Callisto. Apparently the Chinese defense force personnel believed IPS Sugerhill, the cheap transporter has been involved in piracy. Everyone on the Sugerhill was handcuffed and taken aboard the patrol vehicle.

A few hours ago you and eleven other Sugerhill passengers were loaded onto a shuttle, destination unknown. The rumour was that the Defense vehicle was heading back to Callisto so prisoners were to be transferred to a prison bus. Twelve prisoners secured in a passenger cabin with three guards.

Some of the prisoners say that they believe that they are being transferred to a free station to be released. Others whisper a more worrying story -- apparently some private military contractors do a background check on prisoners that they pick up. Anyone who doesn't appear to have rich or influencial friends end up being sold into slavery - their arrest record is deleted by criminal hackers.

The guards of the shuttle become agitated. The following conversation is hearded.

**Guard 1:** We're being retasked. Apparently a transporter reports a possible pirate attack but the ship then went dark and hasn't changed course. I'm not risking my neck going onto a deralict, I didn't sign up to fight pirates. +
**Guard 2:** Ha ha, won't be any risk. Captain says the boarding crew is getting decided by a prisoner lottery. +
**Guard 1:** NO WAY, I already lost one vacc suit this year when I was forced to lend it to a prisoner. +
**Guard 2:** You don't loan a suit, you don't get a cut. It's a big ITV, a 30-thousand-tonner. Even if its empty there will be a million in salvage, each. + 
**Guard 1:** A million. Okay, but better be right about this.

The twelve prisoners are escorted to the main operations deck and strapped to seating at a large table. Each prisoner draws a lazily fashioned straw. The PC's each draw a short straw. Before this moment, the PCs live separate lives, now their lives are link by a momentary act of chance.

The other prisoners appear visibly relieved. Many of the shoot you with concerned looks. Nobody speaks to you but their eyes are saying "it was nice knowing you."

The shuttle's XO gathers you and leads you to the EVA bay and airlock. You are dressed in slightly worn mid-range vacc suits.

The officer, a wirely chinese man in his late 50s grins grimly at you. "Nine times out of ten, everything fine. Everyone happy. Good odds! You not heroes, you not take risks. Go in, report on what you find. If danger obvious, report and withdraw."

Fran gives him a steely look. "One in ten is NOT good odds. If it was good odds you wouldn't need to use impressment. By the way, impressment is ILEGAL."

The XO's face blanked, making the man's mood unreadible.

"You must think I am a bad man. I am NOT a bad man. But I am a hard man. My duty is to protect my crew, above all else. I'm not impressing you, I'm making you all deputies. Regulation 275.9 'During an emergency situation, the command officers may deputize any passengers if there are insufficient crew to fulfil mission requirements safely.'"

A klaxon sounds. Pumps being to pressureise the airlock. A guard checks over the PC's space suits. To one PC he tells them not to pull hard on the left sleave as the seam may have a micropuncture.

"All you need to do is check out the transporter for survivors. Nobody on the ship is communicating, now. There's a chance the ship was completely abandoned or maybe the crew are awaiting rescue. Or they might all be dead from a deadly radiation leak, but it that happended we would surely detect it from your suit sensors the moment that you enter.

=== Scene-2 Free fallin

The PCs are strapped to a "huskie", a drone that astronaughts attach themselves to, that handles the maneuvers of an EVA. Ideal for people with little or no E.V.A experience.

The PCs transfer 3000m between the shuttle and the transport vehicle. The PCs now have free reign to decide how and where they enter the vehicle.

Pass out the deck arrangement sheet. The airlocks are displayed on the left-hand side. The Huskie will maneuver them to any location that they specify.

The PC's may choose to enter at different points. While this is challenging to run, it shouldn't be discouraged. A group of PCs that split up can seriously up the tension as they fend for themselves.

Once the PCs select an entry point (or a number of entry points) then proceed to the section that corresponds with that location.

The moment that someone opens an airlock, there's a glow of light. A small module, about 2m long fires a projectile in the direction of the shuttle. Instantly the shuttle turns into a cloud of burning glass. Nothing is left, just streaking fragments o red hot hull. Gone in a blink.

== I think we're alone now

The PC's all go into shock. Their breathing becomes erratic and they need to make a difficult endurance role or suffer from panic. This increases the difficulty of all actions by 1 or 2 for D6 minutes.


== Dancing in the Dark


=== Every Breath you take


=== Under Pressure
