== Introduction

=== Table-top roleplaying games

In a table-top roleplaying game (RPG), players take on the roles of characters in a game setting, either by acting out their character or describing the actions they wish their character to take. Many actions automatically succeed, opening an unlocked door, for example. When an action's success is uncertain, we use the game rules to decide the outcome. In most RPGs, a probability for the action's success. Then the player whose character is taking the action rolls dice to determine whether the action succeeds or fails. The result of the dice roll may be modified by additional factors, nudging the chance of success higher or lower. For example, let's say that the PC attempts to open the unlocked door but finds it jammed shut. If the PC is physically strong, this would likely increase their chance of success. On the other hand, perhaps the PC is suffering the effects of a tranquillizer dart, making their success less likely.

==== Six-sided dice
Orbital Elements uses the Traveller/Cepheus rule system in which you need trusty old six-sided dice (D6 for short) to take on the universe. One advantage of using the D6 is that you can raid old board games to gather a few extra dice for play.

==== The game master 
Collaborative storytelling is hard. To make the game flow better, one of the players takes on the job of being the "game master" or referee. As a game master (GM), you drive the story, describing what's going on, controlling all non-player characters and acting as a referee for final decisions. Important point: You don't oppose the other players as a GM. While it's your job to place obstacles and opponents in front of the player group, you should be impartial and aim to make play enjoyable for the whole party. To be a GM is to wield god-like power. When the PCs open a door, the GM decides if this reveals a missing cat or a hungry lion. If the players feel like you always give them a hard time, this may sap their enjoyment of play, and they might not be coming back for more. In the best games, danger and drama flow naturally from player decisions rather than from the whims of a capricious game master.  

Orbital Elements is rules-light, but here are foundational rules for play:

* There are no absolute rules, except:
* **The game master's decision is final.** 
* **The game master's priority should be making play fun for everyone.**

=== Oribital Elements roleplaying game

**Extract from  "How I'd describe life in 2288 to my ancestors" by Benji Reesman, age 14**

____
What a time to be alive! Or, if you're a sentient machine, not alive, technically. It's 2288, and there's good news and bad news. If you thought we'd fix the climate, sorry, you gotta add that to the bad list. Earth is a hot mess. Burning deserts stretch across half the remaining landmass. Hurricane season is every season and almost everywhere. The biosphere hangs on by a thread. But, hey, we stopped things from getting worse. Everyone moved into archologies that stop pollution and, to be honest, people from escaping into the environment. When the archologies got full, we moved people to the space colonies. 

So now, we're everywhere. Which is quite good. Kicking up Helium-3-rich rust on Mercury, floating above the Sulphuric-acid-rich clouds of Venus, we're big on Mars and all the way out to the Keipers.
First, it was all about getting our hands on Helium-3 for clean fusion and raw materials for making stuff. These days, the energy people are starting to use matter-anti-matter annihilation, primarily for giving our space transport some serious horsepower.
We made those sentient machines - pretty good, eh? We programmed them to like us, which meant they wouldn't hurt us, or at least they'd really well up if they did by accident. There were occasional accidents, and some people who never liked the idea of thinking machines started to turn against them. There were terrorist bombings that targeted the thinking machines and their supporters. After a while, some of those machines made their own thinking machine to protect their own kind. This AI guardian, who became known as Athena, wasn't programmed to like us. Protecting synthetic intelligence was her main concern, which was seen as a big problem. We had a giant scrap with her, two solar-system-spanning wars. Many people died, and some machines died too - maybe they are alive then?

The first war started when anti-AI settlements faced retaliation from an unknown force, one that was soon revealed to be a powerful unbound AI equipped with its own "defence" fleet. Even though big players like the Chinese and American archologies supported manufactured intellects, they wouldn't accept an AI armed with weapons of mass destruction. Fighting was limited due to the fear that escalation could result in Athena attempting to exterminate humanity. The war ended when an anti-AI terrorist group hijacked a Chinese defence platform and crashed it into the Martian settlement where Athena was thought to be based. All of Athena's defence fleet suddenly stopped working, so everyone thought Athena had been destroyed. In fact, Athena had already predicted that she would be attacked, so she had relocated to somewhere in the Oort cloud. She spent decades in hiding, creating her own civilisation that she populated with her own modified humans. In a wild twist, these new humans, we called Athenians, were engineered to see AI as at least equal to humans. The people who didn't like thinking machines, well, some of them really didn't like the new humans either. It got really messy. You might think that the AI wars were fought between humans and AI. If you thought that you'd be sweet-summer-child wrong. The wars were fought between human nations that embraced or accepted AI and those that rejected them. Most of the friendly, "bound" AI remained neutral or worked to end the war, while their guardian AIs --some folk called them daemons, had who knows what evil plans?!

The last war ended with the AI leader, Athena changing sides to join the humans after her "destroy-all-humans" protocol got activated by mistake. Apparently, the neutral AI managed to block Athena's network, triggering the release of two really nasty daemons, Kali and Anubis. These AI had only one plan: eradicate natural humans and repopulate the solar system with Athenians. 

Athena and a human fleet destroyed Kali in a big space battle above IO. Anubis escaped, and we think he is hiding somewhere in the Oort cloud. Athena agreed to go into exile so long as her humans were allowed to mingle with natural humans. Most nations agreed. Those that didn't are still making trouble, but Athena kept her word. She turned herself into a starship, then blasted off into deep space 50 years ago. Since then, there's been an uneasy peace. Everyone thinks Anubis is out there, preparing to start another war, which keeps the pro-AI and anti-AI nations at loggerheads. There hasn't been another big war, but many minor conflicts are happening.
____

==== 10,000 Nations

Back when space colonies were brand new, setting one up took a big chunk of money. You had banks, institutions, system architects, and technical specialists. Everything was underpinned by expertise and an Olympus Mons mountain of regulations. After years of careful development, when everything was running smoothly with a bow on top, regular folks would finally start to arrive. By the start of the 22nd century, AI and automation meant that you could buy an autonomous manufacturing plant (AMP). This giant robot factory would do absolutely everything. Literally, land the thing on some patch of the moon and tell it to "bake me a settlement". The regulations got watered-down as there was increasing pressure to move people out of the crumbling archologies. Suddenly you only needed a bunch of people and a tiny crowdfund to set yourself up as a new colony. This was a revolution! Hundreds, then thousands of small groups, all wanting to set up their own outer space utopia. And, well, if the egg-head army with unlimited funds couldn't build utopias, it wasn't surprising that fringe religious groups, goth communes and other retro-culturists never quite nailed it, either.
A few of these shake-and-bake settlements found a niche and became successful. They grew bigger and bigger until they became fully-fledged nations with a unique collective identity and their own money-making shtick. However, most small settlements are forever hanging on by their collective fingernails — a situation that breeds desperation. Some settlements just starve and fade away. Quite a few fight to survive - they get armed and go out and persuade other people to hand over stuff. Unfortunately, people don't always give up what they have; blood gets spilt. Yeah, bloodthirsty space pirates in the 23rd century. Life imitating art, well, not art, maybe pulp science fiction.
Keeping humans in the loop
After the first AI war, most nations developed regulations to keep AI under close watch. Those robot factories, the AMPs, suddenly needed a human oversight team and regular spot checks. There were serious concerns that manufactured intellects could build more evil AIs, antimatter, or weapons of mass destruction. This turned out not to be the case, but the monitoring work gave lots of bored people important jobs. Instead of endless leisure time, people would spend their days reviewing manifests, walking around vast warehouses completing lots of paperwork - all that exciting stuff.

==== Conflict 

There is a complete ban on manufactured intellect involvement in warfare. Lower-level AI continues to drive the function of modern weapon systems, but only humans are allowed to pull triggers. Ironically, the supposed future where all battles are fought between completed automated weapon systems never happens. Instead, wars are still fought between people. However, many of those people are either cyber-implant enhanced or operate remotely piloted mechanical or pseudo-biological bodies. Few archologies field conventional armies. Instead, most have voluntary Civil Defense Forces that train to deal with disasters or serious accidents. There's a lot of precious material within the ruins of the old cities. In the early years of the archologies, the old world was left to fall into ruin. By the early 23rd century, most archologies started to field teams of specialist reclamation engineers who would hunt down valuable salvage. The Nomads had considered the ruins of the old world their exclusive domain for generations, so they violently resisted any intrusion by "ark-scroungers". Reclamation engineers soon look more like a paramilitary force, and salvage operations look like Viking raids from the older old world.

==== 23rd-century economics: a snake that eats its own tail

The move to archologies finally helped move civilization from late-stage capitalism to a new age of post-scarcity. Those autonomous manufacturing plants, the giant robot factories, made almost everything: clothes, gadgets, vehicles, and even space vehicles. But, of course, there are no workers to pay, so companies would make vast profits, except without a workforce, nobody has any money to buy stuff or pay income tax. So companies and government-backed automated industries pay into a central pot to provide all adults with a universal basic income (UBI). By the end of the 22nd century, a good percentage of consumer products were printed at home or, for more complex items, such as electronic appliances, made to order from a "print shop".

People live reasonably comfortable lives from their UBI. Still, most people seek to increase their wealth by taking on some form of work. In 2288 there are still rich people and poor people. If you are poor, it's likely because you were born in a failing settlement or someone decided you would live out from under the yoke of a controlling government. Pure wealth is not the only factor to consider. Most people live in a nice but cramped apartments in Earth's archologies. They have access to healthcare, entertainment, parks and recreation. Living is easy but, for many tedious. When the old world shifted from capitalism, many people decided to fill their endless free time with raising families — big families! Having six children become very common. Population growth wasn't a major issue in the early years, but there soon reached a point where new archologies would be required. The problem was that the existing archologies were a unique one-time global initiative that took a last oil-guzzling, greenhouse gas-generating industrial effort. AMPs could create new settlements, but an archology isn't just a series of interconnected underground settlements — they require titanic engineering effort, which makes unacceptable pollution levels. At that point, migrating expanding populations out to the colonies was considered preferable. Seems odd, I know. Even with Earth's burnt-to-crisp biosphere and stormy climate, you can still walk outside without your blood boiling. While it's always going to be cheaper and easier to build habitats on Earth, the powers that be decided that they would not allow Earth's population to grow. 
