= Moon Crash

== Introduction

A one-shot adventure for Orbital Elements Science Fiction Role Playing Game.

*Setting:*  Mare Imbrium (Sea of Rain) basin. Old Helium-3 mining regions, criss-crossed by a contested "no man's land".

== Synopsis

The PCs are the crew of a transport shuttle, carrying a small group of passengers across the lunar landscape when the shuttle is suddenly hit by a ground-launched missile. The PCs are forced to come down in a no man's land region that is littered with dangerous automated weapon systems and ruthless pirate gangs. They must survive long enough to reach a place of safety, then figure out a way to either make their way to the nearest settlement or call for a rescue.

One of the passengers, a Percy Brennan says that he is carrying sensitive information. He offers to pay a significant bonus of the PCs turn off their IFF signal, so they can't be easily tracked, and fly at low altitude to keep off radar. Such requests are not unusual. Luna is now less of a war zone than it was, but people are still nervous travelling across the surface. It's no unheard of for travellers to complete a journey across Luna by travelling to orbit and then coming all the way down. More miles but less worry about encountering trouble. In fact, Percy is a fantasist who travels through the system pretending to be either an espionage agent or someone carrying a mysterious suitcase. The suitcase contains some sims, stims and emergency toiletries. However, one of the other passengers is a Jonah. An old nautical term for someone who was thought to bring bad luck on a ship. In modern parlance, the term specifically refers to someone who is working for criminals who intend to ambush or rob a vehicle during a journey. The Jonah is usually a passenger or recent hire who will sabotage the vehicle, plant a tracking device, or will take direct control. In this case, Zeena Platts is working for a pirate gang. She caught wind of Brennan asking for a transport to fly "off the grid". She assumes that he is carrying something of enormous value, so has decided to risk signing on as a passenger, so that she can be on the ground when the value of the cases contents is discovered. When she discovers that there is no precious cargo, she'll have a minor breakdown. 

The subject of the scenario is how the player characters deal with the crash and the dangers of finding a place to shelter. The pirate angle becomes apparent when, on finding a missing launch facility they identify that someone has put a beacon on their rig. Almost certainly one of the passengers as it would need to be activated some time after leaving polar traffic control.

The adventure is broken down into the following episodes:

=== Episode One: Moon crash

The PCs are introduced to their current situation. They don't get much time to prepare before their vehicle is hit by a small missile. Their rig immediately goes down. The PC piloting the vehicle gets to roll for how severe the crash is, and where exactly they land. On landing, it's clear that their vehicle is wrecked, and in danger of being shot at by any number of autonomous drones or hidden launchers. The PCs must decide how long they risk stripping equipment from the vehicle before a likely strike arrives. Eventually another missile is launched, resulting in the crashed vehicle being peppered by a cloud of penetrators. Potentially lethal for anyone still in the vehicle. 

The episode ends with the PCs deciding on a course of action. They might wait near the vehicle - not a good idea. They might head out and try to find some kind of refuge from where they can wait out until a search party arrives. Normally a personal communicator works fine, but the no mans land regions are usually covered by heavy jamming and interference. 

Player handout 1: Shuttle manifest

Player handout 2: Regional map

=== Episode Two: Across the bright face

The PCs have a map of the region. They must decide where to walk. They're on foot and have limited air and water. Enough for 48 hours. As they travel across the lunar no man's land they roll on an encounter table each hour of travel. They may encounter discarded equipment, derelict shacks, killer drones or even pirates.

[width=50%]
|===========================
1D6 | *Encounter Table*
|1        | No encounter, rock, dust and the black sky.
|2        | Small surface debris. Roll on the *Debris Encounter Table*.
|3        | Small surface debris. Roll on the *Debris Encounter Table*. Add +1 to the roll.
|4        | Crash site. Roll on the *Crash Site Encounter Table*.
|5        | Small ruin. Roll on the *Ruin Encounter Table*.
|6        | Small facility. Roll on the *Facility Encounter Table*.
|===========================

[width=50%]
|===========================
1D6 | *Debris Encounter Table*
|1        | Scattered rocks
|2        | A small crater, about 10m in diameter surounded by rock fragments.
|3        | A large crater, about 50m in diameter. + 
Walking through the crater requires some checks against dexterity. 6+ to avoid a fall.
|4        | Signs of fighting. + 
Metal casings and fragments are scatered around. Maybe some discarded pieces of equipment
|5        | Signs of a battle. Equipment and some empty magazines scattered around. Pieces of space suit. No bodies remain but you definitely get a feeling that people met there end here. 
|6        | An intact lander sits on the edge of a small crater. It doesn't look have been stripped, but the PCs quickly identify that tiny bomblets covering the area. Any attempt to get to the lander will likely result in your death. However, if the PCs are creative they can liberate about CR3000 from the site.
|===========================


[width=50%]
|===========================
1D6 | *Crash Site Encounter Table*
|1        | Debris from a crash vehicle. Nothing remains except for burnt fragments.
|2        | A wreck of a small rig. Looks like it came down hard and exploded. Nothing of value remains.
|3        | The wreck of a large lander. It looks like it made a soft landing but then took fire on the ground and was therefore abondonded. Inside the wreck are intact pieces of equipment. Roll on *Basic Equipment Table*.
|4        | A group of four tracked drone tanks. Someone removed their battery packs. They're too big to carry, so even though they are valuable, the PCS can't benefit from them.
|5        | The wreck of a light combat rig. Came in hard. There are live bombs and missiles attached to its ordnance racks. There is a small risk that the bombs and missiles might detonate if the site is disturbed. If the PCs risk exploring the rig, they can make the ordnace safe, they find 1D6x10,000 cewsee
|6        | Small facility. Roll on the facility table.
|===========================






=== Episode Three: Oasis

Eventually, the PCs find the entrance to some kind of underground base. It's a hidden missile silo, intact and operational. It's the strongest source of local jamming and although there isn't a functional communication system, the jammer itself could be modified to send out an S.O.S. signal. The PCs can spend time exploring the base, learning a little about people who once mannned the station. At some point a group of pirates rigged the silo to launch missiles at low flying or ground vehiles.

If they manage to modify the jammer to send a signal, the first people to turn up won't be a rescue party, it will be a contingent of pirates wanting to know who is messing with their missile silo. A fight will ensue.

=== Episode Four: Moon Cavalry

If the PCs lose the fight, a rescue party will arrive just in time to save them. If the PCs hold off the pirates long enough, the rescue party drives away the pirates.

=== Epilogue

The PCs are taken to the nearest settlement where the local security force will debrief them. 


== Episode One: Moon crash

Read-out-1
'''
Luna Excursion Rig LER-21, Registration L-XP32-J12P, in transit to Copernicus City
Carrying light cargo and five passengers.
Passenger Manifest:
Percy Brennan, carrying precious cargo in a suitcase. Declared prototype scematics.
Zeena Platts, 20-year-old interior designer, leaving the polar regions after a number of jobs improving various communes.
Anjar Sing, 40-year-old surveyor, heading for early retirement after a couple of big mineral finds.
Trix Montang, nonbinary folk singer and performance artist, returning from a tour.
Freddy Happyness Cheaplove, journalist from the Azania archology, doing a backpacking tour of Luna. 
'''


== None-Player Characters

---
====
*Zeena Platts* (Realname: Sam Modey)  +

[width=500px]
image:https://dub01pap003files.storage.live.com/y4mg6TSu_YyDx7AJXkNi03H9CoaW9G-wXaWT7MBuYSmcje6xXpvaUob2RqHLbvyqAUP8yuj_wwEO2zmE7evUb_gcluP3Wz4AcXHl8GC9XlJSMlDCFXoAMWEnjVIV4rRCWBzhcGVpTegLeemIPklC98FB_wC_Qpqt6yzCC_iBew51FLtpSJCNH9uRm34zZySmrH2-7qFlRpxe9vDEdeUAnuI3G8GHmu5Gkm2A10bo05WhiQ?encodeFailures=1&width=1024&height=1024[alt=Zena,width=340,height=340]

*UPP:* 896A38	Age 22 +
Interior Designer (actually, Pirate (1 terms) Rank 2 - Lieutenant) +
Electronics-0 , Energy Pistol-1 , Engineering-1 , Space Vehicle-0 , Piercing Weapons-0 , Piloting-1 , Streetwise-1 , Survival-0 , Turret Weapons-2 , Zero-G-1 +
5,000 cr +
Vacc Suit

Zeena is a "Jonah". A passenger who operates as an insider for pirates.
====

---
====

*Jack Deringer* (Real name: Percy Brennan)



[width=500px]
image:https://dub01pap003files.storage.live.com/y4mMIBAnRSe0_gWsv-tGvbo3fyzt2N7ex-NdF52eKjbldygX6DPzVwunJHAQpNFh-fWVhdY8xWxQ5VTj7jy9t2Q055g2pc3C483iyX0ZpDEEo_SBkj_cNEz_6xt5DbXB48u-c0u7fjQK6xBv5RbNWg0FfY4MbtVsex3EcUvKNeaNwvwL3xT4lvdiWfFZkeVBKX1?encodeFailures=1&width=1024&height=1024[alt=Percy,width=340,height=340]

*UPP* 455D79	Age 50 +
Colonist (5 terms) Rank 5 - Lieutenant Governor +
Drifter (3 terms) +
Admin-0, Electronics-1 , Farming-3 , Gambling-1 , Liaison-1 , Mechanics-1 , Natural Weapons-1 , Recon-1 , Shotgun-1 , Streetwise-1 , Survival-2, Tracked Vehicle-1 , Zero-G-0 +
235,000 cr Pension 10,000 cr

Percy spent his life working diligently in hydroponic farming. He got really good and made a modest fortune. A few years ago he realised that what he really wanted was to be an espionage agent. Too old and with the wrong skillset, Percy instead turned to a life of deception. He travels the solar system under different aliases pretending to be spies, pirates or just damned mysterious. He doesn't use his deception to rob people, he just wants people to see him as an interplantary man of mystery, not a moderately successful hydroponics engineer.


====

*Anjar Singh* 

---

[width=500px]
image:https://dub01pap003files.storage.live.com/y4mNXSiFyxq8HE1FldJvC9MsyHEF7i5jVIe6Q3qSMrWsSTTto2ZFGPu9OpiYzRixxR_SBXAQvnzZ-OOiNskqFrDfS05ZZStlu8Aoyko1LzmEJfw2ZrHWnhtYo4dXECLiEJ02lO-Y2VvYObTlMHZcIxfE9Lsl6OM4xNmN1GJeuf5fN6mkHKB4vQvyqBxR7l_ts26lgNa2xxPcqgzzzX1Om0ejNX5mGuvJB--AFswBRaTn8g?encodeFailures=1&width=943&height=953[alt=Anjar,width=340,height=340]

*UPP* 657B66	Age 34 +
Belter (4 terms) +
Comms-0 , Demolitions-3 , Electronics-1 , Energy Pistol-0 , Heavy Weapons-0 , Mechanics-0 , Physical Sciences-0 , Piloting-2 , Zero-G-2 +
35,000 cr +
Mid Passage +

Anjar is a asteroid miner. A pretty good one. He has sizable shares in several valuable mines. Having nearly come close to death three times in his career, Anjar has decided to cash in and find another life. Sadly his brush with death has left Anjar suffering from mild paranoia and panic attacks. Nothing serious, but it makes him likely to call out wild suspicions.


[width=500px]
image:https://dub01pap003files.storage.live.com/y4m7IEJ_UmS3OLIJNUz4fyeXj0Q0WxLwdfBU_Ct8mhH1RQ2TQ472ObWGmxBZKI49MCf5vmm0A4C5Rmf5OqlPdv4FjcMibxcqFZWw9osP5vau1baAZa7s-AVW_5TV8oy0MRbMAeDWw-wTjn-mn68UDQWg3zD4FiPistOU9PNI2sOOVUXoYM8jJVvemP0SbOSLFO1?encodeFailures=1&width=1024&height=1024[alt=Trix,width=340,height=340]

