== Solar Gazetteer

image:https://db3pap001files.storage.live.com/y4mF6J7uTJFMEg352kCGKuxS_WAlsWwQhSMh332HDzWNRgTgcUl1Z0Z9DN0Jux20s7qtj7RMTAw2TNd-uXuJHvLguZ-vN2kd8FPdxZ60Wpb-fLh_Mh-ErSDjZ5QUZKm3Q1MTuOVjBM3Rcq4Lqt3qWNHYTYqAnNlTN6KMHZxANhEjXqRJFPt6jgiiLfD8uEibQxB?width=1024&height=354&cropmode=none[image]

The following guide covers all the main stations and colonies located in the solar system.

=== Sun

=== Icurus Base

There are no perminent settlements inside the orbit of Mercury. There are a number of "weather" satellites maintained from Icurus Station that keep close watch on solar activity and provide early warning of solar storms. The asteroid, Icurus was nudged into its close solar orbit to provide shielding from the intense heat and radiation. It rotates to simulate gravity and to ensure that intense heat is applied evenly across it's surface, with the station's habitats burried deep to provide adequate shielding. The weather monitoring and solar reseach keep about 100 staff occupied, with most staff working three month terms before rotating back to Earth. Icurus station is a loney place, only very specialised, heavily shielded ships can reach it and they follow a three of four times a year schedule.

NOTE: There's now an inflatable heat blanket that can be deployed across the hull of a spaceship, allowing regular ships to travel closer to the Sun. The heat shield is intended for short emergency transit as more than a few days of heavy neutron exposure is dangerous. 



image:https://db3pap001files.storage.live.com/y4mojBnBia67mDUvFxNUnVkk-uYHeZUrZB0UvJmQ9czKCCjEiU7JbFsDlv6Li23yEb-oKOp3lzfSxCca2sopkbWg69rjddlwwEjqd3FqyRbRVgAqgyFi1-b3BH81flDcW-tZW49dIdSzOllvDHSMKvUP45_n7_KreqlD-F_qbXhpXBu8stDTqCxfVJ3NL7cDO5z?width=660&height=385&cropmode=none[image]

The planet closest to the Sun, Mercury is  characterised by extreme heat (450 degrees Celsius under the sun) and extreme cold (minus 170 C in the shade). A research outpost was established on a large crater wall, close to the south pole. Large deposits of water were found, which immediately makes getting resources off the planet a lot cheaper, as lots of water allow any settlements to create fuel locally and be essentially self sustaining.  Mercury has accumulated lots of minerals from asteroid and comet strikes, making it a buffet of useful construction materials. However, counting against early settlement and exploitation is the fact that reaching Mercury's orbit requires a lot of Delta-v. As the inner-most planet, it's zipping around the Sun at very high speed. Then, when a visitor arrives, they have to then ditch their high speed using fuel as there's no atmospheric breaking. For these reasons, Mercury was settled relatively recently, long after the other inner planets and the asteroid belt. 

There are medium-sized settlements on the planet, mostly supporting water, Helium-3 and mineral mining. A further complication for colonization are the frequent quakes, caused by the fact that Mercury is contracting as its core cools.

*Diameter:* 4880 km +
*Mass:* 0.055 Earths +
*Gravity:* 0.38 +
*Atmosphere:* Trace +

*Ground Settlements*

==== Demmeuter

*Alignment:* Controlled by German and Italian archologies. +
*Population:* 75,000 +
German-Italian colony, situated on the northern pole. The settlement is deep underground, occupying an artificial cavern. +

==== Hidayatullah

*Population:* 50,000 +
Indian settlement that oversees water and rare earth metal mining. The settlement stretches through an extensive tunnel system. While it has a smaller population than Demmeuter, it currently has about twice the available living space. There are plans to try to double the population in the next decade.

==== AMP DX229-71

*Population:* 10 +
Autonomous Manufacturing Plant DX229-71 processes various raw materials, then launches them into an orbital stockpile using a mass driver. A caretaker contingent of humans live at the station. The station is mostly surface-based. 

==== Other settlements

There are between thirty and fifty independent mining settlements. These pop up and then dissapear as they're mostly looking for small lodes of rare earth metals delivered to the surface by asteroid impact.


*Orbital Settlements*

==== Idunn

*Population:* 7000 +
Originally a German-built research station. When the research ended, the station was sold a Swiss businessman who expanded the station to become a Swiss-German Colony.

==== Garaventa

*Population:* 12,000 +
Italian fledgeling colony, has the best orbital spaceport around Mercury which manages 90% of shipping to and from Mercury.

==== USEDS Finingley

*Population:* 300 +
United States of Europe Defense Station, monitors the inner system. Maintains two active warships.


=== Venus

image:https://db3pap001files.storage.live.com/y4m0ua6XHTuQr3Qljcx1dy3_R12BoYp69Wvmr4KRyY6BSRwxgh8XYJ3e1J7EusjcFUG_LdtuUKDXyhZBZG0b-VN1EtSkHnxt07kho07YKlAKkrfBgP6cgBXGqLMe0vzqWkN7B6uZ6XgjadjHAdIdcrMXa_d_8Ql-IIxDTIaastIbUx_3uYQuP03-sKBb2SzLsde?width=660&height=385&cropmode=none[image]

A planet named for its beauty, Venus is a hellish world with some of the most hostile surface conditions in the entire solar system. It's so hot down there on the Venusian surface that anything not made of a high-melting point metals or ceramics ends up melted or erroded. There have been several attempts to begin terraforming operations but each has ended up discontinued, in part because of the difficulty of operating in such conditions.

*Diameter:* 4880 km +
*Mass:* 0.94 Earths +
*Gravity:* 0.8 +
*Atmosphere:* 92 atmospheres

==== Experimental Atmospheric Outpost

Historical site. Like a floating museum, maintaining the original research output.

*Atmopheric Settlements*

==== Pegasus Station

*Population:* 1500 +

An under-construction fully-fledged colony. The pegasus project is constructing a vast floating platform, situated 70km above the burning surface of Venus. While the surface of Venus is like the inside of a kiln, the upper atmosphere has a zone where settlers can walk around with just an oxygen mask and acid resistent suit. When completed, Pegasus will provide more than a square kilometer of surface area on which to construct inflatable habitats. The top of the habitation is used for greenhouses and a shuttle recovery platform.

*Ground Settlements*

==== Hadius Base

*Population:* 70,000 +

Settlement built by a specially designed AMPs which landed on the surface then tunneled underground. Th e AMPs dug out a huge pressure-sealed tunnel system. The original aim was to create a very large colony. However, getting on and off Venus is still difficult. The heat and pressure force surface operations to be very limited. Only specialised rocket systems can be used to land on Venus, and these rockets wear out quickly. As a result Hadius base never become a large-scale colony. Instead it attracted groups that specifially wanted isolation, somewhere close to Earth but also hard to visit. The population of Habius base is actually spread over hundreds of miles of tunnels, although most of the bases essential facilities (hospital, manufacturing and agriculture is located at a central hub.

=== Earth

image:https://db3pap001files.storage.live.com/y4mVH80D8qYEGpGJt9tiTHyTisxxqr4TmW5wqnBHROA6J91TErF0t0pPFgqfooEZMqPeNcgy6kFBqmvOfoh5SiHyXkvnnIkHK4Og_ySld9unJl5SDMZNVkxPJIjZiO3tU5DA21Pxf_tAUMeFzj85s1BxSZXop6Ba6ISu_b4i-x1QqOfaMGYtAlrSBsuE1xG1NLR?width=1024&height=795&cropmode=none[image of the world]

*Archologies* 

More than ninety percent of Earth's inhabitants live in fewer than 100 archologies. The near colapse of Earth's biosphere, along with the constant hurricanes generated by the heat-wrecked atmosphere forced humanity to huddle in cramp, highly vertical city-structures. Anyone not living in an archology is living in so-called Bunker communities, these are networks of underground habitats. Compared to the archologies, these are much smaller with fewer facilities, inhabited by those who valued space and freedom over convenience. Tiny number of people live outside of these two types of habitation. Living "off the grid" means a constant battle for survival, facing savage weather, living off sterilized soil and poisoned water. However, even after hundreds of years, there is money to be made exploring the ruins of the old cities, just don't go unarmed. Things can get wild out there.

There are broadly three types of archology:

**Dome clusters**, where existing cities where covered in vast domes, supported by tower pillars. These are more sprawling, covering larger land areas and being somewhat less developed then the purpose built structures. 

**Tower Structures**, Single or multiple tower structures, these massive buildings incorporate everything required to sustain the inhabitants, automated manufacturing plants supply most manufactured goods, automated farms create the food. Power is supplied from a combination of renewables, fusion power and orbital solar provide energy. 

**Deep Wells**, Some Archologies were dug downwards, creating cavernous habitats that support artificially sustained forrests, lit by huge sunlamps. An approach to living space that was imported from the extra-terrestrial colonies.

Life in the archologies is reasonably comfortable and safe, but for most inhabitants, day-to-day living is highly regulated, with limits on personal freedom. Employment rates are below 25%, leaving the majority of people to occupy themselves through leisure, hobbies or self employment producing artifacts.

Most archologies are extremely insular. Built to be completely self-sufficient, and following very similar plans, so life in one archology is pretty much the same as another. The exceptions are the archologies at the base of the two space elevators, Cayambe in Equador and Mame no ki, 

Raising families remains popular, although most archologies limit family sizes to keep population growth under control. Couples wanting more than two children are encouraged to emigrate to a colony/habitat. 

By the 2280s most archologies have become rundown. While automated systems continue to repair essential infrastructure, the massive scale of these structures make the task of renovation or replacement extremely difficult. Most archologies have shifted to space emigration to handle population pressure. 

==== Luna

image:https://db3pap001files.storage.live.com/y4mOPiCDo26HbEBGetwt5JrFbQYwdobL4OaZN8QDYb_L5Afk1k5pCB2nsiXNDVMpZES-KyY25OlisPJbZNKr8Slmhy5dw9weDcsp6H2AA5Wc5M-TOgchf5OIOgFmoM6uNrYOejMTCIyIsIoFJHhdKAPYqCS92tY7iooKRZhDgpXkjEInspR5Ibpky72omElQlDZ?width=660&height=385&cropmode=none[image]

The Earth's moon, now commonly called Luna, given that people are living on dozens of moons, is one of the most developed and populous places in the solar system. It was the location of the first perminent space settlement, it then because the main industrial hub for both space development and metal resources for Earth. Over the last two centuries six large settlements have grown to become nations in their own right. This development didn't run smoothly, Luna was the first readily available source of Helium-3, the crucial ingrediant for low-neutron-emission Fusion. Helium-3 was seen as stategically vital resouce -- if you had it, you had a foothold in the future, if you didn't, your nation would be left behind. In the early days, Luna saw nations scuffle over mining rights, then full-blown conflicts.

Mining saw the construction of hundreds of small  temporarly settlements, build quickly and with not much care. The infamous Jobesville massacre occured when the desperate inhabitats of one such settlement suffered life support failure, a band of engineers lead of Tommy Logan travelled to the neighbouring Jobesvill to persaude the occupants to provide technical assistance and parts. The occupants of Jobesville refused to help as their own settlement's infrastructure was close to collapse. The resulting tussle turned bloody, resulting on Jobesville's destruction and the death of its entire population. It was seen as the darkest day in human space colonisation, the larger colonies tried to introduce a legal framework to ensure that future conflicts could be avoided, but nothing could be agreed. There was an on-going cold war among the Luna colonies and no colony wanted to be constrained from "defending" its own rights.

Outside of the protected borders of each colony, Luna is a no man's land of deserted mining settlements and surviving failed-state settlements that breed piracy and cover the activities of the big criminal organizations.

**Apollo City** US Luna hub city, located 

**Chang-Er** Chinese Luna settlement, less developed than Appollo but spread over a larger area, located in the southern pole.  

**Tsiolkovskygrad** Russian industry-focused colony 

**Dubois** Jointed European colony, colonised by all European archologies.

**Azania** Colonised by the African Federation

**Tsukuyomii** Japanese colony

==== Other settlements

There are hundreds of smaller settlments dotted ado


=== Mars

==== Phoebos

==== Deimos

=== The Belt

==== Ceres

==== Pallas

==== Vesta

==== Hygiea

=== Jupiter

==== Io

==== Europa

==== Ganymede

==== Callisto



=== Saturn

==== Mimas

==== Enceladus

==== Tethys (trojans: Telesto and Calypso)

==== Dione (trojans: Helene and Polydeuces)

==== Rhea

==== Titan

==== Hyperion

==== Iapetus

==== Phoebe

=== Uranus

==== Miranda

==== Ariel

==== Umbriel

==== Titania

==== Oberon

=== Neptune

==== Rings of Neptune

==== Proteus

==== Triton

==== Nereid


