
== Synopsis

The PCs return from Mongers Knoll to find the city is now under the control of the prime elector. A few days ago the city guards found the bodies of the Master of Coin and the patrician's master of arms, and a bloody torn sleave belonging to the patrician. It is assumed that the Patrician has been taken hostage, although no demand has so far been made.


The PCs are recognised as agents of the patrician and are asked to make an attempt to track him down. The adventure introduces the PCs to their home city and takes them from the deepest sewers to the highest tower, as they uncover the mystery of the missing patrician.


== What's happened?

The Patrician has been stealing money from the city. His was one of the ruling seven families that have vied for control of the city over the last 300 years. Every five years the families submit a candidate for the patrician's role. The cities 12 electors and one prime elector then vote for which candidate will fill the powerful role.

The Patrician has control over the cities gold reserves and annual taxes but doesn't handle the money him or herself, that day-to-day control of finance rests with the Master of Coin, an independent position, usually filled by senior servents of the emperor.


The Patrician had managed to find various means of relocating tax monies to himself. Initially small amounts but over the course of the last year, the Patrician has managed to steal a fortune, doing a deal with a powerful criminal boss called  "La Tartaruga" (The Tortortise) who launders the money. The Patrician's bodyguard is really the left-hand-man of the Tortoise.

The master of coin caught wind of the theft but kept his head, instead collecting evidence in the form of copies of ledgers. When the master of coin confronted the Patrician with the news that large amounts of money w
