== Sword of Cepheus: Adventure 2

=== Mystery of Mengers Knoll


==== Synopsis

The adventurers are recently returned from recovering the patrician's strongbox from the bandit cave. The patrician is so appreciative of the PCs' efforts that he immediately assigns them to an even more dangerous task.

The distant village of Mengers Knoll has refused to pay its tithe (10% of its collective coinage) for the third year. The patrician had been ignoring the fact but THREE YEARS, damn it! So he had sent a five-man unit of his elite Tarnished legion to assist the village in finding some of the missing coins.

That was a  month ago. The fact that his elite soldiers have failed to return is considerable  more upsetting than the missing contribution, which would be a triffling amount compared to the worth of his soldiers.

The player characters are to take the north road until they reach the Red moors. The sleepy village of Mengers Knoll is located on a, well a small hill. Logical! That's what a knoll is, after all.

===== The fate of Menger's Knoll

Tam Battersworth, the village mayor was digging out his mansion's large cellar in order to add a new drainage pipe. He broke through into a hidden stone chamber, filled with luminous egg-shaped crystals. He filled a bucket with the beautiful objects and stored them in a bowl in his study, using their light to read at night.

Tam wasn't to know that he'd recovered Zharker seeds, stolen from a hostile alien dimension by a long-dead wizard. After a few weeks the seeds lost their glow, and Tam lost his interest in them. He handed out a few to some of the villagers as gifts, most were tossed into his back yard. When they fell into the dirt they took root and began to grow into a strange dark plant, as big as a man and made up of large clusters of head-sized balls, eld together by long waxy vines. Tam didn't know what to make of the growth, it looked freakish and smelled something rotten. Other villagers found similar growths where their own gifted seeds had ended up taking root, although these growths were small, not like Tam's which kept on growing to the size of a large tree.

Tam tried to have the growth destroyed, paying two of the village's biggest farm hands to chop and burn the thing down -- nobody could have known that it would fight back, grabbing the two men with its vines and strangling them. The men's corpses became wrapped in the plant-fiend's vines and nobody could summon up the courage to approach the demon plant again.

Panic spead throughout the village. Many fled right away.

